FROM node:alpine

WORKDIR /app

COPY package.json .

RUN npm install \
 && npm install typescript -g \
 && mkdir /dat-schema

COPY tsconfig.json .
COPY src/ src/

RUN tsc

CMD [ "npm", "run", "serve", "/dat-schema/"]
