type Shrines {
  Id: string @unique
  TimeoutInSeconds: i32
  ChargesShared: bool
  Player_ShrineBuffsKey: rid
  _: i32
  _: i32
  Monster_ShrineBuffsKey: rid
  SummonMonster_MonsterVarietiesKey: MonsterVarieties
  SummonPlayer_MonsterVarietiesKey: MonsterVarieties
  _: i32
  Duration: i32
  ShrineSoundsKey: ShrineSounds
  _: bool
  AchievementItemsKeys: [AchievementItems]
  IsPVPOnly: bool
  _: bool
  IsLesserShrine: bool
  Description: ClientStrings
  Name: ClientStrings
  _: bool
  _: rid
  _: [_]
}

type ShrineSounds {
  Id: string @unique
  StereoSoundFile: string @file(ext: ".ogg")
  MonoSoundFile: string @file(ext: ".ogg")
}
