type DivinationCardArt @tags(list: ["item:def"]) {
  BaseItemTypesKey: BaseItemTypes @unique
  ArtFile: string # Virtual path
  Effects: [CardAnimatedEffects]
  MaskFile: string
}

enum CardAnimatedEffects @indexing(first: 0) {
  SHAPER
  ELDER
  CRUSADER
  EYRIE
  BASILISK
  ADJUDICATOR
  ZANA
}
