type LabyrinthAreas {
  Id: string
  Normal_WorldAreasKeys: [WorldAreas]
  Cruel_WorldAreasKeys: [WorldAreas]
  Merciless_WorldAreasKeys: [WorldAreas]
  Endgame_WorldAreasKeys: [WorldAreas]
  _: i32
}

type LabyrinthBonusItems {
  BaseItemType: BaseItemTypes
  AreaLevel: i32
  LabyrinthName: string
}

type LabyrinthExclusionGroups {
  Id: string
}

type LabyrinthIzaroChests {
  Id: string @unique @files(ext: [".ot", ".otc"])
  ChestsKey: Chests
  SpawnWeight: i32
  MinLabyrinthTier: i32
  MaxLabyrinthTier: i32
}

type LabyrinthNodeOverrides {
  Id1: string
  Id2: string
  _: [i32]
  _: [i32]
}

type LabyrinthRewardTypes {
  Id: string @unique
  ObjectPath: string @files(ext: [".ot", ".otc"])
}

type Labyrinths {
  Tier: i32
  Name: string
  OfferingItem: BaseItemTypes
  QuestFlag: QuestFlags
  RequiredTrials: [LabyrinthTrials]
  AreaLevel: i32
  _: i32
  JewelReward: Words
  _: [i32]
  _: [i32]
  MinLevel: i32
  _: i32
  _: i32
  CraftingFontDescription: ClientStrings
}

type LabyrinthSecretEffects {
  Id: string
  MonsterVarietiesKey: MonsterVarieties
  Buff_BuffDefinitionsKey: BuffDefinitions
  Buff_StatValues: [i32]
  OTFile: string @file(ext: ".ot")
}

enum LabyrinthSecretLocations @indexing(first: 0) { _ }

type LabyrinthSecrets {
  Id: string
  Id2: string
  _: [i32]
  _: i32
  _: i32
  LabyrinthSecretEffectsKeys0: [LabyrinthSecretEffects]
  LabyrinthSecretEffectsKeys1: [LabyrinthSecretEffects]
  LabyrinthSecretEffectsKeys2: [LabyrinthSecretEffects]
  _: i32
  LabyrinthSecretEffectsKeys3: [LabyrinthSecretEffects]
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: bool
  Name: string
  AchievementItemsKey: AchievementItems
  LabyrinthTierMinimum: i32
  LabyrinthTierMaximum: i32
  _: bool
}

type LabyrinthSection {
  Id: string
  ExclusionGroup: LabyrinthExclusionGroups
  _: i32
  _: i32
  _: i32
  _: i32
}

type LabyrinthSectionLayout {
  LabyrinthSectionKey: LabyrinthSection
  _: i32
  LabyrinthSectionLayoutKeys: [LabyrinthSectionLayout]
  LabyrinthSecretsKey0: LabyrinthSecrets
  LabyrinthSecretsKey1: LabyrinthSecrets
  LabyrinthAreasKey: LabyrinthAreas
  Float0: f32
  Float1: f32
  LabyrinthNodeOverridesKeys: [LabyrinthNodeOverrides]
}

type LabyrinthTrials {
  WorldAreas: WorldAreas
  _: i32
  _: i32
  _: i32
  NPCTextAudioKey: NPCTextAudio
  _: string
  _: string
  _: i32
}

type LabyrinthTrinkets {
  BaseItemTypesKey: BaseItemTypes @unique
  LabyrinthSecretsKey: [LabyrinthSecrets]
  Buff_BuffDefinitionsKey: BuffDefinitions
  Buff_StatValues: [i32]
}
