type ArchitectLifeScalingPerLevel {
  Level: i32
  MoreLife: i32
}

type IncursionArchitect {
  MonsterVarietiesKey: MonsterVarieties
  MinLevel: i32
}

type IncursionBrackets {
  MinLevel: i32
  Incursion_WorldAreasKey: WorldAreas
  Template_WorldAreasKey: WorldAreas
  _: [f32]
  _: f32
  _: i32
}

type IncursionChestRewards {
  IncursionRoomsKey: IncursionRooms
  IncursionChestsKeys: [IncursionChests]
  ChestMarkerMetadata: string @files(ext: [".ot", ".otc"])
  _: i32
  _: i32
  _: i32
}

type IncursionChests {
  Id: string @unique
  ChestsKey: Chests
  UniqueChestsKey: UniqueChests
  MinLevel: i32
  MaxLevel: i32
  Weight: i32
  _: i32
}

type IncursionRoomBossFightEvents {
  Room: IncursionRooms
  _: string
  _: string
  _: string
  _: string
  _: string
  _: rid
}

type IncursionRooms {
  Id: string @unique
  Name: string
  Tier: i32
  MinLevel: i32
  RoomUpgrade_IncursionRoomsKey: IncursionRooms
  Mods: [Mods]
  PresentARMFile: string @file(ext: ".arm")
  HASH16: i32 @unique
  IncursionArchitectKey: IncursionArchitect
  PastARMFile: string @file(ext: ".arm")
  TSIFile: string @file(ext: ".tsi")
  UIIcon: string
  FlavourText: string
  Description: string
  AchievementItemsKeys: [AchievementItems]
  _: i32
  _: i32
  RoomUpgradeFrom_IncursionRoomsKey: IncursionRooms
  _: rid
}

type IncursionUniqueUpgradeComponents {
  _: rid
  BaseItemType: BaseItemTypes
}
