type Incubators {
  BaseItemTypesKey: BaseItemTypes @unique
  _: i32
  Description: string
  Hash: i32
  AchievementItemsKeys: [AchievementItems]
}

type LegionBalancePerLevel {
  MinLevel: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type LegionChestCounts {
  LegionFactionsKey: LegionFactions
  LegionRanksKey: LegionRanks
  _: i32
  _: i32
  _: i32
  _: i32
  MinLevel: i32
  _: i32
}

type LegionChests {
  ChestsKey: Chests
  LegionFactionsKey: LegionFactions
  LegionRanksKey: LegionRanks
  MonsterVarietiesKey: MonsterVarieties
  _: i32
}

type LegionFactions {
  Id: string @unique
  _: i32
  LegionBalancePerLevelKey: LegionBalancePerLevel
  _: f32
  _: f32
  BuffVisualsKey: BuffVisuals
  MiscAnimatedKey1: MiscAnimated
  MiscAnimatedKey2: MiscAnimated
  MiscAnimatedKey3: MiscAnimated
  AchievementItemsKeys1: [AchievementItems]
  MiscAnimatedKey4: MiscAnimated
  MiscAnimatedKey5: MiscAnimated
  _: f32
  _: f32
  AchievementItemsKeys2: [AchievementItems]
  StatsKey: Stats
  Shard: string
}

type LegionMonsterCounts {
  LegionFactionsKey: LegionFactions
  LegionRanksKey: LegionRanks
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

enum LegionMonsterTypes @indexing(first: 0) { _ }

type LegionMonsterVarieties {
  MonsterVarietiesKey: MonsterVarieties
  LegionFactionsKey: LegionFactions
  LegionRanksKey: LegionRanks
  _: i32
  MiscAnimatedKey: [MiscAnimated]
  _: i32
  _: i32
  _: [i32]
  _: [i32]
  _: [i32]
  _: [i32]
  _: [i32]
  _: [i32]
  _: i32
  _: i32
  _: [rid]
  MonsterVarietiesKey2: MonsterVarieties
}

type LegionRanks {
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  LegionBalancePerLevelKey: LegionBalancePerLevel
  _: i32
  _: i32
}

enum LegionRankTypes @indexing(first: 0) { _ }

enum LegionRewardTypes @indexing(first: 0) { _ }

type LegionRewardTypeVisuals {
  IntId: i32 @unique
  MinimapIconsKey: MinimapIcons
  _: string
  MiscAnimatedKey: MiscAnimated
  _: f32
  Id: string
}
