type BlightBalancePerLevel {
  Level: i32
  _: i32
  _: [i32]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type BlightBossLifeScalingPerLevel {
  Level: i32
  MoreLife: i32
}

type BlightChestTypes {
  ChestsKey: Chests
}

type BlightCraftingItems {
  Oil: BaseItemTypes
  Tier: i32
  Achievements: [AchievementItems]
  UseType: i32
}

type BlightCraftingRecipes {
  Id: string @unique
  BlightCraftingItemsKeys: [BlightCraftingItems]
  BlightCraftingResultsKey: BlightCraftingResults
  BlightCraftingTypesKey: BlightCraftingTypes
}

type BlightCraftingResults {
  Id: string @unique
  ModsKey: Mods
  PassiveSkillsKey: PassiveSkills
}

type BlightCraftingTypes {
  Id: string @unique
  _: i32
  _: bool
}

type BlightCraftingUniques {
  WordsKey: Words
}

type BlightedSporeAuras {
  BuffDefinitionsKey: BuffDefinitions
  _: [i32]
  _: i32
  _: [i32]
  _: i32
}

type BlightEncounterTypes {
  Id: string @unique
  Icon: string
  IsGeneric: bool
  Weight: i32
}

type BlightEncounterWaves {
  MonsterSpawnerId: string
  EncounterType: BlightEncounterTypes
  _: i32
  _: i32
  _: i32
  Wave: i32
}

type BlightRewardTypes {
  Id: string @unique
  Icon: string
}

type BlightTopologies {
  Id: string @unique
  BlightTopologyNodesKey: BlightTopologyNodes
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type BlightTopologyNodes {
  Id: string @unique
  _: [i32]
  Size: i32
  Angle: i32
  _: [i32]
  _: [i32]
  _: [i32]
  _: [i32]
  _: [i32]
  _: [i32]
  _: i32
}

type BlightTowerAuras {
  Id: i32 @unique
  BuffDefinitionsKey: BuffDefinitions
  _: i32
  MiscAnimatedKey: MiscAnimated
}

type BlightTowers {
  Id: string @unique
  Name: string
  Description: string
  Icon: string
  NextUpgradeOptions: [BlightTowers]
  _: i32
  Tier: string
  Radius: i32
  _: i32
  SpendResourceAchievement: AchievementItems
  StatsKey: Stats
  StatsKeys: [Stats]
  StatsKeys2: [Stats]
  _: bool
}

type BlightTowersPerLevel {
  BlightTowersKey: BlightTowers
  _: i32
  MonsterVarietiesKey: MonsterVarieties
  Cost: i32
  _: i32
}
