type AlternateQualityTypes @tags(list: ["item:def"]) {
  Id: string
  Description: string
  Item: BaseItemTypes
  _: rid
  MapStats: [Stats]
  _: i32
  IsCatalyst: bool
  HASH16: i32
  CatalystMod: Mods
}
