type AtlasExileBossArenas {
  Conqueror: AtlasExiles
  WorldArea: WorldAreas
}

type AtlasExileInfluence {
  Conqueror: AtlasExiles
  Sets: [AtlasInfluenceSets]
}

type AtlasExiles {
  Id: string
  _: i32
  InfluencedItemIncrStat: Stats
  MapIcon: string @file(ext: ".dds")
  MapIcon2: string @file(ext: ".dds")
}
