type AfflictionBalancePerLevel {
  _: i32
  _: f32
  _: f32
  _: f32
  _: f32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: f32
  _: f32
}

type AfflictionEndgameWaveMods {
  ModsKey: Mods
  _: i32
  _: i32
  _: i32
}

type AfflictionFixedMods {
  Rarity: i32
  Mod: Mods
  _: rid
}

type AfflictionRandomModCategories {
  Id: string @unique
  _: bool
}

type AfflictionRewardMapMods {
  ModsKey: Mods
  _: bool
}

enum AfflictionRewardTypes @indexing(first: 0) { _ }

type AfflictionRewardTypeVisuals {
  AfflictionRewardTypes: AfflictionRewardTypes
  Id: string
  Name: string
}

type AfflictionSplitDemons {
  _: i32
  MonsterVarietiesKey: MonsterVarieties
  AfflictionRandomModCategoriesKey: AfflictionRandomModCategories
}

type AfflictionStartDialogue {
  WorldAreasKey: WorldAreas
  NPCTextAudioKey: NPCTextAudio
  _: [rid]
}
