enum HarvestColours @indexing(first: 0) { _ }

type HarvestCraftOptionIcons {
  Id: string @unique
  DDSFile: string @file(ext: ".dds")
}

type HarvestCraftOptions @tags(list: ["crafting"]) {
  Id: string @unique
  Text: string
  Tier: HarvestCraftTiers
  Command: string
  Parameters: string
  _: [_]
  HASH16: i16
  Description: string
  IsEnchant: bool
  LifeforceType: i32
  LifeforceCost: i32
  SacredCost: i32
  _: bool
  Achievements: [AchievementItems]
  _: i32
}

type HarvestCraftTiers {
  Id: string @unique
  FrameImage: string
  FrameHighlight: string
}

type HarvestCraftFilters {
  Id: string
  BaseItem: BaseItemTypes
  Name: string
}

type HarvestInfrastructure {
  Object: string
  _: i32
  ClientStringsKey: ClientStrings
}

type HarvestPerLevelValues {
  Level: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type HarvestLifeScalingPerLevel {
  Level: i32
  Life: i32
}

type HarvestSeeds {
  Id: string
  Monster: MonsterVarieties
  Tier: i32
  _: i32
  _: [i32]
  Achievements: [AchievementItems]
  SeedAnimation: string @file(ext: ".ao")
  _: i32
  HatchAnimation: string @file(ext: ".ao")
  SeedType: i32
}

type HarvestSeedItems @tags(list: ["item:def"]) {
  Id: i32
  BaseItem: BaseItemTypes
  DropStat: Stats
}
