enum HarvestColours @indexing(first: 0) { _ }

type HarvestCraftOptionIcons {
  Id: string @unique
  DDSFile: string @file(ext: ".dds")
}

type HarvestCraftOptions {
  Id: string @unique
  Text: string
  _: rid
  Command: string
  Parameters: string
  AchievementItemsKeys: [AchievementItems]
  _: bool
  _: i32
  HarvestCraftOptionIconsKeys: [HarvestCraftOptionIcons]
  Description: string
  DDSFile: string @file(ext: ".dds")
  _: bool
  _: bool
}

type HarvestCraftTiers {
  Id: string @unique
  FrameImage: string
  FrameHighlight: string
}

type HarvestDurability {
  HarvestObjectsKey: HarvestObjects @unique
  Durability: i32
}

type HarvestEncounterScaling {
  Level: i32
  Multiplier: f32
  StatsKeys: [Stats]
  StatsValues: [i32]
}

type HarvestInfrastructure {
  Object: string
  _: i32
  ClientStringsKey: ClientStrings
}

enum HarvestInfrastructureCategories @indexing(first: 0) { _ }

enum HarvestMetaCraftingOptions @indexing(first: 0) { _ }

type HarvestObjects {
  BaseItemTypesKey: BaseItemTypes @unique
  AOFile: string @file(ext: ".ao")
  ObjectType: i32
}

type HarvestPerLevelValues {
  Level: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

enum HarvestPlantBoosterFamilies @indexing(first: 0) { _ }

type HarvestPlantBoosters {
  HarvestObjectsKey: HarvestObjects @unique
  Radius: i32
  _: rid
  Lifeforce: i32
  AdditionalCraftingOptionsChance: i32
  RareExtraChances: i32
  HarvestPlantBoosterFamilies: i32
}

type HarvestSeeds {
  Id: string
  Monster: MonsterVarieties
  Tier: i32
  Description: string
  _: [rid]
  _: i32
  _: [i32]
  _: [i32]
  _: i32
  SeedAnimation: string @file(ext: ".ao")
  _: i32
  HatchAnimation: string @file(ext: ".ao")
  SeedType: i32
}

type HarvestSeedTypes {
  HarvestObjectsKey: HarvestObjects @unique
  _: rid
  GrowthCycles: i32
  AOFiles: [string] @file(ext: ".ao")
  _: [i32]
  _: i32
  Tier: i32
  RequiredNearbySeed_Tier: i32
  RequiredNearbySeed_Amount: i32
  WildLifeforceConsumedPercentage: i32
  VividLifeforceConsumedPercentage: i32
  PrimalLifeforceConsumedPercentage: i32
  Text: string
  HarvestCraftOptionsKeys: [HarvestCraftOptions]
  _: i32
  _: [i32]
  AchievementItemsKeys: [AchievementItems]
  OutcomeType: i32
}

type HarvestSpecialCraftCosts {
  _: rid
  _: i32
  _: i32
}

type HarvestSpecialCraftOptions {
  _: rid
  _: i32
  _: rid
}
