type InfluenceModUpgrades {
  InfluenceMod: Mods
  UpgradedMod: Mods
  _: bool
}

type MavenDialog {
  Id: string
  TextAudioT1: NPCTextAudio
  TextAudioT2: NPCTextAudio
  TextAudioT3: NPCTextAudio
  TextAudioT4: NPCTextAudio
  TextAudioT5: NPCTextAudio
  _: bool
  TextAudioT6: NPCTextAudio
}

type AtlasSkillGraphs {
  Id: string
  SkillGraph: string
  RegionName: string
  Achievements: [AchievementItems]
}

type MavenFights {
  Id: string
  WitnessesRequired: i32
  AreaLevel: i32
  _: i32
  _: i32
  BaseItemType: BaseItemTypes
  _: i32
  MinMapTier: i32
  _: QuestFlags
  _: i32
  WitnessAreas: [WorldAreas]
  _: i32
  _: QuestFlags
  _: bool
  _: [_]
  CompletionAchievements: [AchievementItems]
}

type MavenJewelRadiusKeystones {
  Keystone: PassiveSkills
}
