type InfluenceModUpgrades {
  InfluenceMod: Mods
  UpgradedMod: Mods
}

type MavenDialog {
  Id: string @unique
  TextAudioT1: NPCTextAudio
  TextAudioT2: NPCTextAudio
  TextAudioT3: NPCTextAudio
  TextAudioT4: NPCTextAudio
  TextAudioT5: NPCTextAudio
  _: bool
}

type AtlasSkillGraphs {
  Id: string
  SkillGraph: string
  RegionName: string
  Achievements: [AchievementItems]
}

type MavenFights {
  Id: string @unique
  AtlasRegionsKey: AtlasRegions
  _: i32
  Level: i32
  _: i32
  _: i32
  _: i32
  BaseItemTypesKey: BaseItemTypes
  AtlasSkillGraphKey: AtlasSkillGraphs
  _: i32
  _: i32
  _: i32
  _: i32
  WorldAreasKey: [WorldAreas]
  _: i32
  _: i32
}
