type RitualBalancePerLevel {
  MinLevel: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: f32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type RitualConstants {
  Id: string @unique
  Value: f32
}

type RitualRuneTypes {
  Id: string @unique
  MiscAnimatedKey1: MiscAnimated
  SpawnWeight: i32
  LevelMin: i32
  LevelMax: i32
  BuffDefinitionsKey: BuffDefinitions
  _: [i32]
  SpawnPatterns: [RitualSpawnPatterns]
  ModsKey: [Mods]
  _: [i32]
  _: [i32]
  MiscAnimatedKey2: MiscAnimated
  EnvironmentsKey: Environments
  _: i32
  Achievements: [AchievementItems]
  Type: string
  Description: string
  DaemonSpawningDataKey: DaemonSpawningData
  _: bool
}

type RitualSetKillAchievements {
  Achievement: AchievementItems
  KillBosses: [MonsterVarieties]
}

type RitualSpawnPatterns {
  Id: string @unique
  _: i32
  SpawnOrder: [string]
  _: bool
}
