type ExpeditionAreas {
  Area: WorldAreas
  PosX: i32
  PosY: i32
  Tags: [Tags]
  _: [i32]
  _: bool
  TextAudio: NPCTextAudio
  CompletionAchievements: [AchievementItems]
}

type ExpeditionBalancePerLevel {
  Level: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type ExpeditionCurrency {
  BaseItemType: BaseItemTypes
  Tier: i32
  NPC: ExpeditionNPCs
  LootSound: SoundEffects
}

enum ExpeditionDealFamilies @indexing(first: 1) {
  REROLL_PREFIXES_BEST
  REROLL_SUFFIXES_BEST
  VALUES_AFFIXES_LUCKY
  VALUES_PREFIXES_LUCKY
  VALUES_SUFFIXES_LUCKY
  VALUES_IMPLICITS_LUCKY
  UPGRADE_HIGHEST_TIER
  UPGRADE_ONE_TIER
  REMOVE_LOWEST_LEVEL
  ADD_PREFIX_BEST
  ADD_SUFFIX_BEST
  FILL_EMPTY_MODS
  REFORGE_SOCKETS
  REFORGE_LINKS
  APPLY_INCUBATOR
  APPLY_RANDOM_QUALITY
  SET_QUALITY
  APPLY_ANOINTMENT
  CORRUPT
  ADD_INFLUENCE
  REMOVE_ALL_PREFIXES
  REMOVE_ALL_SUFFIXES
}

type ExpeditionDeals {
  Id: i32 @unique
  Function: string
  Arguments: string
  TextAudio: NPCTextAudio
  Description: string @localized
  BuyAchievements: [AchievementItems]
  _: rid
  DealFamily: ExpeditionDealFamilies
}

type ExpeditionFactions {
  Id: string @unique
  Name: string
  FactionFlag: string
  _: i32
  FactionIcon: string
  MonsterVarieties: MonsterVarieties
  Progress1: NPCTextAudio
  Progress2Vaal: NPCTextAudio
  Progress3Final: NPCTextAudio
  Tags: Tags
}

type ExpeditionMarkersCommon {
  Id: string @unique
  AOFile: string
}

type ExpeditionNPCs {
  Id: string
  NPCs: [NPCs]
  RerollItem: BaseItemTypes
  _: i32
  _: i32
  _: QuestFlags
  Faction: ExpeditionFactions
  Reroll: NPCTextAudio
  AllBombsPlaced: NPCTextAudio
  BombPlacedRemnant: NPCTextAudio
  BombPlacedTreasure: NPCTextAudio
  BombPlacedMonsters: NPCTextAudio
  BombPlacedGeneric: NPCTextAudio
  EncounterComplete: NPCTextAudio
}

enum ExpeditionRelicModCategories @indexing(first: 0) {
  GENERIC
  RUNIC
  REWARD_CHEST
  REWARD_PACK_SIZE
}

type ExpeditionRelicMods {
  Mod: Mods
  Categories: [ExpeditionRelicModCategories]
  DestroyAchievements: [AchievementItems]
}

type ExpeditionRelics {
  Id: string @unique
  Name: string
  ItemTag: Tags
  AOFile: string
  MinLevel: i32
  MaxLevel: i32
}

type ExpeditionStorageLayout {
  Id: string
  BaseItemType: BaseItemTypes
  PosX: i32
  PosY: i32
  _: i32
  _: i32
  Width: i32
  Height: i32
  _: i32
  _: bool
  _: rid
}

type ExpeditionTerrainFeatures {
  Id: string @unique
  ExtraFeature: ExtraTerrainFeatures
  ExpeditionFaction: ExpeditionFactions
  MinLevel: i32
  MaxLevel: i32
  _: i32
  Area: WorldAreas
  ExpeditionAreas: [ExpeditionAreas]
  _: i32
  _: bool
  UnearthAchievements: [AchievementItems]
}
