
type HellscapeAOReplacements {
  Original: string @file(ext: ".ao")
  HASH32: i32
  Replacement: string @file(ext: ".ao")
}

type HellscapeAreaPacks {
  WorldArea: WorldAreas
  MonsterPacks: [MonsterPacks]
  _: i32
  _: i32
}

type HellscapeExperienceLevels {
  Level: i32
  Experience: i32
}

type HellscapeFactions {
  Id: string @unique
  _: Environments
  _: Environments
  _: [Environments]
  _: i32
  _: [MonsterVarieties]
  _: string @file(ext: ".ao")
  Boss: MonsterVarieties
}

type HellscapeImmuneMonsters {
  Monster: MonsterVarieties
}

type HellscapeItemModificationTiers {
  Tier: i32
  IsMap: bool
  _: i32
  MinItemLvl: i32
}

type HellscapeLifeScalingPerLevel {
  AreaLevel: i32
  Scale: i32
}

type HellscapeModificationInventoryLayout {
  Id: string @unique
  Column: i32
  Row: i32
  IsMapSlot: bool
  _: i32
  Width: i32
  Height: i32
  Stat: Stats
  StatValue: i32
  UnlockedWith: HellscapePassives
  Quest: Quest
}

type HellscapeMods {
  Mod: Mods
  TiersWhitelist: [i32]
  TransformAchievement: AchievementItems
  ModFamilies: [ModFamily]
}

type HellscapeMonsterPacks {
  Id: string @unique
  MonsterPack: MonsterPacks
  Faction: HellscapeFactions
  IsDonutPack: bool
  IsElite: bool
  MinLevel: i32
  MaxLevel: i32
}

type HellscapePassives {
  Id: string @unique
  Name: string @localized
  Stats: [Stats]
  StatsValues: [i32]
  Points: i32
  HASH16: i32
  Icon: string
  IconMaxed: string
  SoundEffect: SoundEffects
  _: i32
  Quest: Quest
}

type HellscapePassiveTree {
  Id: string @unique
  AllocationsRequired: i32
  Passives: [HellscapePassives]
}
