
type ArchnemesisMetaRewards {
  Id: string
  RewardText: string @localized
  RewardGroup: i32
  ScriptArgument: string
  MinLevel: i32
  MaxLevel: i32
}

type ArchnemesisModComboAchievements {
  Achievement: AchievementItems
  Mods: [ArchnemesisMods]
}

type ArchnemesisMods {
  Mod: Mods
  _: i32
  Name: string @localized
  Visual: ArchnemesisModVisuals
  TextStyles: [string]
  _: bool
  _: bool
}

type ArchnemesisModVisuals {
  Id: string
  _: MiscAnimated
  _: rid
  _: rid
  _: [BuffVisuals]
  _: [MonsterVarieties]
  _: [MiscAnimated]
  _: [rid]
}

type ArchnemesisRecipes {
  Result: ArchnemesisMods
  Recipe: [ArchnemesisMods]
  _: i32
}
