type SanctumAirlocks {
  Floor: SanctumFloors
  _: i32
  _: [i32]
  Area1: WorldAreas
  Area2: WorldAreas
}

type SanctumDefenceIcons {
  Id: string
  Stat: Stats
  DefenceIcon: string
  DefenceBrokenIcon: string
  BrokenStat: Stats
  Description: string
}

type SanctumDeferredRewardCategories {
  Item: BaseItemTypes
  NamePlural: string
  ScriptReward: string
}

type SanctumDeferredRewards {
  Id: string
  DeferralIcon: string
  DeferralCategory: SanctumPersistentEffectCategories
  RewardCategory: SanctumDeferredRewardCategories
  Count: i32
}

type SanctumFloors {
  Id: string
  Area: WorldAreas
  Title: ClientStrings
  RoomIcon: string
  BossIcon: string
  Description: string
  Summary: ClientStrings
  Itemised: BaseItemTypes
}

type SanctumFodderLifeScalingPerLevel {
  Level: i32
  _: i32
}

type SanctumLifeScalingPerLevel {
  Level: i32
  _: i32
}

type SanctumPersistentEffectCategories {
  Id: string
  Frame: string
  Popup: string
  Glow: string
  Curse: bool
  Boon: bool
  Icon: string
  Name: string
  Deferral: bool
}

type SanctumPersistentEffects {
  Id: string
  Stats: [Stats]
  StatValues: [i32]
  Name: string
  Icon: string
  _: i32
  _: bool
  EffectCategory: SanctumPersistentEffectCategories
  NextEffect: SanctumPersistentEffects
  _: string
  BoonDesc: string
  CurseDesc: string
  _: i32
  _: i32
  _: bool
  _: [rid]
  Guard: [MonsterVarieties]
  FirstEffect: SanctumPersistentEffects
  _: i32
  _: i32
  _: bool
  _: bool
  HASH16: i32
}

type SanctumRooms {
  Id: string
  ArmFile: string
  RoomType: SanctumRoomTypes
  Script: string
  Floor: SanctumFloors
  Area: WorldAreas
}

type SanctumRoomTypes {
  Id: string
  _: bool
  _: bool
  _: rid
  _: rid
  _: bool
  Icon: string
  _: bool
  Description: string
  _: [string]
  Rooms: [SanctumRooms]
  _: string
  _: bool
}

type SanctumSelectionDisplayOverride {
  Id: string
  Reward: string
  Icon: string
  Downside: string
  Item: BaseItemTypes
  Count: i32
  RewardCategory: SanctumDeferredRewardCategories
}
