type WeaponPassiveSkillTypes {
  Id: string
  _: i32
}

type WeaponPassiveTreeBalancePerItemLevel {
  Level: i32
  Bar1: i32
  Bar2: i32
  Bar3: i32
  Bar4: i32
  Bar5: i32
}

type WeaponPassiveTreeUniqueBaseTypes {
  UniqueBase: BaseItemTypes
  _: i32
}

type WeaponPassiveSkills {
  Id: string
  Tier: i32
  Mod: Mods
  _: [_]
  _: [_]
  Icon: string
  Type: WeaponPassiveSkillTypes
  Achievements: [AchievementItems]
}

type CrucibleDifficulty {
  Number: string @unique
  Name: string @unique
  _: i32
  _: i32
  _: i32
  _: i32
}

type CrucibleEndgameMonsterPacks {
  Tier: string @unique
  _: [_]
  _: i32
  _: i32
  _: bool
}

type CrucibleLifeScalingPerLevel {
  Level: i32
  Life: i32
}

type CruciblePlayerClassOffsets {
  _: rid @unique
  _: i32
  _: i32
}

type CrucibleTags {
  Tag: string @unique
  _: bool
}
