type AncestralEmbraceVariations {
  Id: string
  Minion: MonsterVarieties
  BuffTemplate: BuffTemplates
}

type AncestralLifeScalingPerLevel {
  Level: i32
  MoreLife: i32
}

type AncestralTrialChieftains {
  Tribe: AncestralTrialTribes @unique
  Monster: AncestralTrialMonsters
}

type AncestralTrialDialogue {
  Tribe: AncestralTrialTribes
  TrialEvent: AncestralTrialDialogueEvents
  _: i32
  TextAudio: [NPCTextAudio]
  Character: Characters
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
}

type AncestralTrialDialogueEvents {
  Id: string
  _: i32
}

type AncestralTrialFieldItems {
  Unit: AncestralTrialUnits
  Object: MiscObjects
  HASH32: u32
  Description: string
  Achievement: [AchievementItems]
  SoundEffectPurchase: SoundEffects
  SoundEffectPlace: SoundEffects
}

type AncestralTrialItems {
  Id: string
  HASH16: i32
  Name: string
  Image: string
  Tribe: AncestralTrialTribes
  _: i32
  Mods: [Mods]
  FlavorText: string
  _: i32
  _: [_] # All rows empty
  SoundEffectPurchase: SoundEffects
  SoundEffectEquip: SoundEffects
}

type AncestralTrialMonsters {
  Unit: AncestralTrialUnits
  Monster: MonsterVarieties
  Animation: MiscAnimated
  _: i32
  Achievement: [AchievementItems]
  _: bool
  _: bool
  _: bool
  _: bool
}

type AncestralTrialPositionType {
  Id: string
  PlayerTotemIcon: string
  Name: string
  EnemyTotemIcon: string
  PlayerTotemSmallIcon: string
  EnemyTotemSmallIcon: string
}

type AncestralTrialShopSlotEntries {
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: i32
  _: bool
}

type AncestralTrialTribeOpinions {
  SourceTribe: AncestralTrialTribes
  TargetTribe: AncestralTrialTribes
  Opinion: AncestralTrialOpinionTypes
}

type AncestralTrialTribes {
  Id: string @unique
  NPCHub: NPCs
  Portrait: string
  TribeIcon: string
  TribeName: string @unique
  FavourTracker: string
  _: [rid]
  Name: string
  QuestFlagLike: QuestFlags
  QuestFlagDislike: QuestFlags
  QuestFlagFightLost: QuestFlags
  QuestFlagFightWin: QuestFlags
  Achievement: [AchievementItems]
  MinimapIcon: MinimapIcons
  AchievementRuthless: [AchievementItems]
  _: i32
  _: i32
  _: i32
  _: i32
  NPCArena: NPCs
}

type AncestralTrialUnitPositions {
  Id: string
  _: i32
  _: i32
  _: i32
  _: i32
}

type AncestralTrialUnits {
  Id: string
  Name: string
  Tribe: AncestralTrialTribes
  Image: string
  TotemImage: string
  HASH16: i32
  _: i32
  Description: string
  _: i32
  _: i32
  Position: AncestralTrialUnitPositions
}

type ChieftainLifeScalingPerLevel {
  Level: i32
  MoreLife: i32
}

type PassiveSkillTattoos {
  Tattoo: BaseItemTypes
  Override: PassiveSkillOverrides
  Set: PassiveSkillTattooTargetSets
  Tribe: i32
  OverrideType: PassiveSkillOverrideTypes
}

type PassiveSkillTattooTargetSets {
  Id: string
  Set: [i32]
  Name: string
  Qualifier: string
}
