type AfflictionDustedMonsterCurrencyDropWeightingByItemRarity {
  Rarity: Rarity
  CurrencyDropWeighting: f32
}

type AzmeriCounterQuests {
  Id: string
  Ascendancy: Descendancy
  QuestFlagStart: QuestFlags
  QuestFlagEnd: QuestFlags
  _: i32
}

type AzmeriFeatureRooms {
  _: i32
  _: i32
  _: string
  _: string
  Achievements: [AchievementItems]
  _: bool
}

type AzmeriLifeScalingPerLevel {
  Level: i32
  MoreLife: i32
}

type AzmeriWoodsDustType {
  Id: string @unique
  BaseItemType: BaseItemTypes
  _: string
  _: string
  ChargeAnimation: MiscAnimated
  ReleaseAnimation: MiscAnimated
  Stats: Stats
  BeamArt: MiscBeams
  WeatherArt: MiscAnimated
  Text: string
}

type CorpseTypeTags {
  Tag: Tags
  Name: string @localized
  RavenousBuff: BuffDefinitions
  Icon: string
  _: i32
  TypeTag: TypeTags
  _: string
  MinimapIcon: MinimapIcons
}

type Descendancy {
  Id: string
  Name: string
  BackgroundImage: string
  FlavourText: string
  CoordinateRect: string
  RGBFlavourTextColour: string
  UnlockCondition: string
  SoundEffectOpen: SoundEffects
  SoundEffectAccept: SoundEffects
  _: i32
  PassiveTreeUIArt: PassiveSkillTreeUIArtAscendancy
  UIArt: UIArtAscendancy
}

type ItemisedCorpse {
  BaseItem: BaseItemTypes @unique
  MonsterVariety: MonsterVarieties
  MonsterAbilities: string @localized
  MonsterCategory: CorpseTypeTags
}

type Tinctures {
  BaseItem: BaseItemTypes @unique
  "1 stack of Mana Burn is applied every x milliseconds"
  DebuffInterval: i32
  Cooldown: i32
}
