type AfflictionDustedMonsterCurrencyDropWeightingByItemRarity {
  _: rid
  _: i32
}

type AzmeriCounterQuests {
  _: string
  _: rid
  _: rid
  _: rid
  _: i32
}

type AzmeriFeatureRooms {
  _: i32
  _: i32
  _: string
  _: string
  _: [_]
  _: bool
}

type AzmeriLifeScalingPerLevel {
  _: i32
  _: i32
}

type AzmeriWoodsDustType {
  _: string
  _: rid
  _: string
  _: string
  _: rid
  _: rid
  _: rid
  _: string
  _: i32
  _: rid
  _: i32
  _: string
}

type CorpseTypeTags {
  _: rid
  _: string
  _: rid
  _: string
  _: i32
}

type Descendancy {
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: rid
  _: rid
}

type ItemisedCorpse {
  _: rid
  _: rid
  _: string
  _: rid
}

type Tinctures {
  BaseItem: BaseItemTypes
}
