type AfflictionDustedMonsterCurrencyDropWeightingByItemRarity {
  _: rid
  _: i32
}

type AzmeriCounterQuests {
  _: string
  _: rid
  _: rid
  _: rid
  _: i32
}

type AzmeriFeatureRooms {
  _: i32
  _: i32
  _: string
  _: string
  _: [_]
  _: bool
}

type AzmeriLifeScalingPerLevel {
  _: i32
  _: i32
}

type AzmeriWoodsDustType {
  _: string
  _: rid
  _: string
  _: string
  _: rid
  _: rid
  _: rid
  _: string
  _: i32
  _: rid
  _: i32
  _: string
}

type CorpseTypeTags {
  Tag: Tags
  Name: string @localized
  RavenousBuff: BuffDefinitions
  Icon: string
  _: i32
}

type Descendancy {
  Id: string
  Name: string
  BackgroundImage: string
  FlavourText: string
  CoordinateRect: string
  RGBFlavourTextColour: string
  UnlockCondition: string
  _: rid
  _: rid
  _: i32
  UIArt: PassiveSkillTreeUIArtAscendancy
  _: rid
}

type ItemisedCorpse {
  BaseItem: BaseItemTypes @unique
  MonsterVariety: MonsterVarieties
  MonsterAbilities: string @localized
  MonsterCategory: CorpseTypeTags
}

type Tinctures {
  BaseItem: BaseItemTypes @unique
  "1 stack of Mana Burn is applied every x milliseconds"
  DebuffInterval: i32
  Cooldown: i32
}
