type ItemisedNecropolisPacks {
  Item: BaseItemTypes @unique
  Pack: NecropolisPacks
  Description: string
}

type NecropolisCraftBases {
  Id: string
  BaseItem: BaseItemTypes
  UniqueCraft: NecropolisUniqueCrafts
  _: bool
  _: i32
  CraftItemType: NecropolisCraftItemTypes
  Name: string
  CraftTag: Stats
  _: bool
}

type NecropolisCraftingMods {
  Id: string
  _: i32
  Stats: [Stats]
  StatsValues: [i32]
  CraftingItemType: NecropolisCraftItemTypes
  _: i32
  CorpsesNotConsumed: bool
  CraftingItemTypes: [NecropolisCraftItemTypes]
  Achievements: [AchievementItems]
  MatchingMonsters: i32
}

type NecropolisCraftingModsFromStats {
  Stat: Stats
  CraftingMod: NecropolisCraftingMods
}

type NecropolisCraftItemTypes {
  Id: string
  ExorciseIcon: string
  Name: string
  _: i32
  IllustratuionIcon: string
  TextAudioLong: NPCTextAudio
  Achievements: AchievementItems
  TextAudioShort: NPCTextAudio
  _: rid
}

type NecropolisPackAdditionalPacks {
  _: rid
  _: rid
}

type NecropolisPackImplicitClass {
  Id: string
  MoreImplicit: NecropolisPackImplicits
  LessImplicit: NecropolisPackImplicits
}

type NecropolisPackImplicits {
  Id: string
  Text: string
  Icon: string
}

type NecropolisPackMods {
  Mod: Mods
  Tier: NecropolisPackModTiers
  NextTier: NecropolisPackMods
  PrevTier: NecropolisPackMods
}

type NecropolisPackModTiers {
  Id: string
  Icon: string
  Name: string
  TextColours: [string]
  SpecialTier: bool
}

type NecropolisPacks {
  Id: string
  Name: string
  Icon: string
  Description: string
  PackLeader1: string
  PackLeader2: string
  Mod: Mods
}

type NecropolisPacksPerArea {
  _: rid
  _: [rid]
  _: [i32]
}

type NecropolisUniqueCrafts {
  Id: string
  Stats: [Stats]
}

type PackFrequencyNames {
  Id: string
  Frequency: f32
  Text: ClientStrings
}
