type CurrencyExchange {
  Item: BaseItemTypes
  Category: CurrencyExchangeCategories
  SubCategory: CurrencyExchangeCategories
  _: bool
  EnabledInChallengeLeague: bool
  GoldPurchaseFee: i32
  _: bool
  _: bool
}

type CurrencyExchangeCategories {
  Id: string
  Name: string
}

type SettlersLifeScalingPerLevel {
  Level: i32
  MoreLife: i32
}

type VillageAssignWorkerTextAudio {
  Job: VillageJobs
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
}

type VillageBalancePerLevelShared {
  MaxAccountLevel: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type VillageExports {
  Id: string
  Name: string
  ShippingValue: i32
  Icon: string
  _: i32
  _: i32
  Icon2: string
  Name2: string
  IconCombined: string
  Result: VillageExports
  _: i32
}

type VillageFarmAdjacency {
  Plot: i32
  AdjacentPlots: [i32]
}

type VillageJobs {
  JobType: VillageJobTypes
  _: i32
  Status: string
  Stat: Stats
  StatValue: i32
}

type VillageJobSkillLevels {
  JobLevel: i32
  PlayerLevelRequired: i32
}

type VillageJobTypes {
  Id: string
  Icon: string
  StateText: string
  MaxWorkersStat: Stats
  _: bool
  JobSpeedStat: Stats
}

type VillageMappingBonusStats {
  Stats: Stats
  PercentChance: i32
}

type VillageMappingPerTier {
  Id: i32
  _: i32
  _: i32
  _: i32
}

type VillageProduction {
  Id: string
  Input: VillageResources
  Output: VillageResources
  BaseProductionTime: i32
  Job: VillageJobs
}

type VillageRecruitBalancePerTier {
  Id: i32
  _: i32
}

type VillageResources {
  Id: string
  Export: VillageExports
  _: i32
  PopupIcon: WorldPopupIconTypes
}

type VillageSharedConstants {
  Id: string
  Value: i32
}

type VillageShippingFailures {
  Id: string
  Text: string
  Resource: [VillageResources]
  ResourceLostPercent: i32
  PortBonusLostPercent: i32
  _: i32
  CrewMembersLost: i32
  _: i32
  SubText: string
  _: i32
}

type VillageShippingPorts {
  Id: string
  Name: string
  FlagArt: string
  MapLineArt: string
  ReturnMessage: string
  _: bool
  PositionX: i32
  PositionY: i32
  _: i32
  _: i32
  DistanceFromPort: i32
  _: bool
  RiskMultiplier: f32
  _: rid
}

type VillageTownLayout {
  Id: string @unique
  Job: VillageJobs
  JobType: VillageJobTypes
  MapButtonArt: string
  Name: string
  PositionX: i32
  PositionY: i32
  Resource: VillageResources
}

type VillageUniqueDisenchantValues @tags(list: ["item:droptable"]) {
  UniqueName: Words @unique
  Value: f32
  RuthlessValue: f32
}

type VillageUpgradeCategories {
  Id: string
  ScriptArgs: string
  Name: string
  Icon: string
  Text: string
  JobType: VillageJobTypes
}

type VillageUpgrades {
  Category: VillageUpgradeCategories
  Tier: i32
  Text: string
  _: i32
  UpgradeResource: [VillageResources]
  UpgradeResourceCount: [i32]
  GoldCost: i32
  RuneItem: [BaseItemTypes]
  _: [i32]
  Stats: [Stats]
  StatsValues: [i32]
  UpgradeTextAudio: NPCTextAudio
}

type VillageBaseStats {
  Stat: Stats
  StatValue: i32
}

type RecombinableClasses {
  Id: ItemClasses
  _: i32
}
