type MercenaryClasses {
  Id: string
  MonsterVariety: MonsterVarieties
  _: i32
  _: rid
  _: i32
  _: i32
  Icon: string
  House: string
  _: MercenaryClasses
  _: [_]
  MonsterVarietyAllied: MonsterVarieties
}

type MercenaryAttributes {
  Id: string
  Name: string
  Tags: [Tags]
}

type MercenaryBuilds {
  Id: string
  Class: MercenaryClasses
  Skill1: [MercenarySkills]
  _: i32
  Skill2: [MercenarySkills]
  _: i32
  _: [rid]
  _: i32
  Skill3: [MercenarySkills]
  _: [string]
  Tags: [Tags]
  AIFile: string
  HASH16: u16
  BuildName: string
  _: i32
  Infamous: bool
  _: rid
  _: string
  _: [string]
  Achievements: [AchievementItems]
  WieldableTypes: [MercenaryWieldableTypes]
}

type MercenaryBuildVisualOverrides {
  Id: MercenaryBuilds
  SlotId: i32
  MtxGameSpecific: MtxTypeGameSpecific
}

type MercenaryFlavourText {
  Id: string
  Description: string
  HASH16: u16
  Tags: [Tags]
  TagWeight: [i32]
}

type MercenaryInventories {
  Id: MercenaryClasses
  _: i32
  _: i32
  _: i32
  _: i32
}

type MercenaryRenownLevels {
  RenownLevel: i32
  _: i32
  _: i32
}

type MercenarySkillFamilies {
  Id: string
}

type MercenarySkills {
  Id: GrantedEffects
  SupportCount: MercenarySupportCounts
  PossibleSupports: [MercenarySupports]
  SecondaryGrantedEffect: GrantedEffects
  Name: string
  Description: string
  _: i32
  _: i32
  SkillFamily: MercenarySkillFamilies
  HASH16: u16
  HouseIcon: string
}

type MercenarySupportCounts {
  Id: string
}

type MercenarySupportFamilies {
  Id: string
}

type MercenarySupports {
  Id: string
  _: i32
  _: i32
  _: i32
  Stat: [Stats]
  StatValues: [i32]
  Name: string
  SupportFamily: MercenarySupportFamilies
  HASH16: u16
  GemIcon: string
  Variant: i32
}

type MercenaryWieldableTypes {
  ItemClass: ItemClasses
}
