type BreachBossLifeScalingPerLevel {
  MonsterLevel: i32
  LifeMultiplier: i32
}

type BreachElement {
  Element: string
  _: rid
  BaseBreachstone: BaseItemTypes
  BossMapMod: Stats
  DuplicateBoss: Stats
}

type brequelpassivesubtrees {
  Id: string  @unique
  _: ClientStrings
  _: ClientStrings
  _: BaseItemTypes
}

type brequelgrafttypes {
  BaseItemTypesKey: BaseItemTypes
  LeftArm: string
  RightArm: string
  SkillGemsKey: SkillGems
  _: i32
  SkillAnimation: string
  AchievementItemsKey: AchievementItems
}
