type BreachBossLifeScalingPerLevel {
  MonsterLevel: i32
  LifeMultiplier: i32
}

type BreachElement {
  Element: string
  _: rid
  BaseBreachstone: BaseItemTypes
  BossMapMod: Stats
  DuplicateBoss: Stats
}

type BrequelFruitRewardTypes {
  Id: string @unique
  Name: string
  Description: string
  _: string
  _: string
  _: [_]
  _: [_]
  AchievementItem: AchievementItems
  AchievementItemHardmode: AchievementItems
}

type BrequelFruitTypes {
  BaseItemType: BaseItemTypes @unique
  Reward: BrequelFruitRewardTypes
  _: i32
  _: i32
  _: rid
  _: rid
}

type BrequelGrafts {
  Id: string @unique
  Arm: string
  SkillGem: SkillGems
  _: i32
  SkillAnimation: string
}

type BrequelPassiveSubTrees {
  Id: string  @unique
  _: ClientStrings
  _: ClientStrings
  Wombgift: BaseItemTypes
}

type BrequelTreeSlots {
  PassiveSkill: PassiveSkills @unique
  BrequelSubTree: BrequelPassiveSubTrees
}

type BrequelGraftGrantedSkillLevels {
  ItemLevel: i32
  SkillLevel: i32
  RequiredLevel: i32
}
