type BreachBossLifeScalingPerLevel {
  MonsterLevel: i32
  LifeMultiplier: i32
}

type BreachElement {
  Element: string
  _: rid
  BaseBreachstone: BaseItemTypes
  BossMapMod: Stats
  DuplicateBoss: Stats
}

type BrequelPassiveSubTrees {
  Id: string  @unique
  _: ClientStrings
  _: ClientStrings
  _: BaseItemTypes
}

type BrequelGraftTypes {
  BaseItemType: BaseItemTypes @unique
  LeftArm: string
  RightArm: string
  SkillGem: SkillGems
  _: i32
  SkillAnimation: string
  Achievement: AchievementItems
}
