enum AccountQuestFlags @indexing(first: 0) { _ }

type AchievementItemRewards {
  AchievementItemsKey: AchievementItems
  BaseItemTypesKey: BaseItemTypes
  Message: string
  Id: string
}

type AchievementItems {
  Id: string @unique
  _: i32
  _: i32
  Name: string
  CompletionsRequired: i32
  AchievementsKey: Achievements
  _: bool
  _: bool
  _: bool
  _: bool
}

type Achievements {
  Id: string @unique
  Description: string
  SetId: AchievementSetsDisplay @ref(column: "Id")
  Objective: string
  _: i32 @unique
  _: bool
  HideAchievementItems: bool
  _: bool
  MinCompletedItems: i32
  TwoColumnLayout: bool
  ShowItemCompletionsAsOne: bool
  _: string
  SoftcoreOnly: bool
  HardcoreOnly: bool
  _: bool
  _: string
}

type AchievementSetRewards {
  SetId: AchievementSetsDisplay @ref(column: "Id")
  AchievementsRequired: i32
  Rewards: [BaseItemTypes]
  TotemPieceEveryNAchievements: i32
  Message: string
  NotificationIcon: string @file(ext: ".dds")
  HideoutName: string
  Id: string
}

enum AchievementSets @indexing(first: 0) { _ }

type AchievementSetsDisplay {
  Id: i32 @unique
  Title: string
}

type ActiveSkills {
  Id: string @unique
  DisplayedName: string
  Description: string
  _: string
  Icon_DDSFile: string @file(ext: ".dds")
  ActiveSkillTargetTypes: [ActiveSkillTargetTypes]
  ActiveSkillTypes: [ActiveSkillType]
  WeaponRestriction_ItemClassesKeys: [ItemClasses]
  WebsiteDescription: string
  WebsiteImage: string
  _: bool
  _: string
  _: bool
  SkillTotemId: SkillTotems
  IsManuallyCasted: bool
  Input_StatKeys: [Stats]
  Output_StatKeys: [Stats]
  MinionActiveSkillTypes: [ActiveSkillType]
  _: bool
  _: bool
  _: [Stats]
  _: i32
  AlternateSkillTargetingBehavioursKey: AlternateSkillTargetingBehaviours
  _: bool
  AIFile: string @file(ext: ".ai")
  _: [rid]
  _: bool
  _: bool
  _: bool
}

enum ActiveSkillTargetTypes @indexing(first: 1) {
  TARGETABLE_GROUND
  ENEMY
  WALKABLE_GROUND
  ANYWHERE_SELF_TARGET
  ITEM
  CORPSE
  _
  NO_LINE_OF_SIGHT
  BEHIND_MONSTER
  SELF_ORIGIN
  ROTATE_TO_TARGET
}

type ActiveSkillType {
  Id: string @unique
  FlagStat: Stats
}

type Acts {
  Id: string @unique
  Part: i32
  _: string
  ActNumber: i32
  _: i32
  WorldPanelImage: string
  WorldPanelImageEpilogue: string
  _: i32
  IsPostGame: bool
  _: i32
  _: [QuestFlags]
}

type AddBuffToTargetVarieties {
  BuffDefinitions: BuffDefinitions
  _: [i32]
  StatsKeys: [Stats]
  _: i32
  _: [i32]
  _: i32
  _: i32
  _: [i32]
}

type AdditionalLifeScaling {
  IntId: i32
  ID: string
  DatFile: string @file(ext: ".dat")
}

enum AdditionalLifeScalingPerLevel @indexing(first: 0) { _ }

type AdditionalMonsterPacksFromStats {
  StatsKey: Stats
  _: i32
  MonsterPacksKeys: [MonsterPacks]
  AdditionalMonsterPacksStatMode: i32
  PackCountStatsKey: Stats
  StatsKeys: [Stats]
  StatsValues: [i32]
  _: i32
}

enum AdditionalMonsterPacksStatMode @indexing(first: 0) { _ }

type AdvancedSkillsTutorial {
  Id: string @unique
  SkillGemInfoKey1: [SkillGemInfo]
  SkillGemInfoKey2: [SkillGemInfo]
  Description: string
  International_BK2File: string @file(ext: ".bk2")
  SkillGemsKey: SkillGems
  China_BK2File: string @file(ext: ".bk2")
  CharactersKey: [Characters]
}

type AegisVariations {
  Name: string
  DefendsAgainstPhysical: bool
  DefendsAgainstFire: bool
  DefendsAgainstCold: bool
  DefendsAgainstLightning: bool
  DefendsAgainstChaos: bool
  _: rid
  _: rid
  _: rid
  _: rid
}

enum AlternateBehaviourTypes @indexing(first: 0) { _ }

type AlternatePassiveAdditions {
  Id: string @unique
  AlternateTreeVersionsKey: AlternateTreeVersions
  SpawnWeight: i32
  StatsKeys: [Stats]
  Stat1Min: i32
  Stat1Max: i32
  _: i32
  _: i32
  _: i32
  _: i32
  PassiveType: [i32]
  _: i32
}

type AlternatePassiveSkills {
  Id: string @unique
  AlternateTreeVersionsKey: AlternateTreeVersions
  Name: string
  PassiveType: [i32]
  StatsKeys: [Stats]
  Stat1Min: i32
  Stat1Max: i32
  Stat2Min: i32
  Stat2Max: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  SpawnWeight: i32
  _: i32
  RandomMin: i32
  RandomMax: i32
  FlavourText: string
  DDSIcon: string @file(ext: ".dds")
  AchievementItemsKeys: [AchievementItems]
  _: i32
  _: i32
}

type AlternateSkillTargetingBehaviours {
  Id: string @unique
  _: i32
  ClientStrings: ClientStrings
  _: i32
  _: i32
  _: i32
  _: [i32]
}

enum AlternateTreePassiveSizes @indexing(first: 0) { _ }

type AlternateTreeVersions {
  Id: string @unique
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type AnimatedObjectFlags {
  AOFile: string @file(ext: ".ao")
  _: i32
  _: bool
  _: bool
}

type Animation {
  Id: string @unique
  _: bool
  _: bool
  _: bool
  Mainhand_AnimationKey: Animation @ref(column: "Id")
  Offhand_AnimationKey: Animation @ref(column: "Id")
  _: bool
  _: rid
}

type ApplyDamageFunctions {
  Id: string @unique
  StatsKeys: [Stats]
  _: bool
}

type ArchetypeRewards {
  Id: string @unique
  _: rid
  _: [rid]
  _: rid
  BK2File: string @file(ext: ".bk2")
}

type Archetypes {
  Id: string
  CharactersKey: Characters
  PassiveSkillTreeURL: string
  AscendancyClassName: string
  Description: string
  UIImageFile: string
  TutorialVideo_BKFile: string @file(ext: ".bk")
  _: i32
  _: f32
  _: f32
  BackgroundImageFile: string
  IsTemporary: bool
  _: bool
  ArchetypeImage: string
  _: bool
  _: bool
}

type AreaInfluenceDoodads {
  StatsKey: Stats
  StatValue: i32
  _: f32
  AOFiles: [string] @file(ext: ".ao")
  _: i32
  _: bool
  _: string
  _: Stats
}

type AreaTransitionAnimations {
  Id: string @unique
  AnimationId: string
}

type AreaTransitionAnimationTypes {
  Id: string @unique
}

type AreaTransitionInfo {
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: [rid]
  _: i32
  _: [rid]
}

enum AreaType @indexing(first: 0) { _ }

enum ArmourClasses @indexing(first: 0) { _ }

enum ArmourSurfaceTypes @indexing(first: 0) { _ }

type ArmourTypes {
  BaseItemTypesKey: BaseItemTypes
  ArmourMin: i32
  ArmourMax: i32
  EvasionMin: i32
  EvasionMax: i32
  EnergyShieldMin: i32
  EnergyShieldMax: i32
  IncreasedMovementSpeed: i32
  WardMin: i32
  WardMax: i32
  _: i32
  _: i32
}

type Ascendancy {
  Id: string @unique
  ClassNo: i32
  Characters: [Characters]
  "Coordinates in 'x1, y1, x2, y2' format"
  CoordinateRect: string
  RGBFlavourTextColour: string
  Name: string
  FlavourText: string
  OGGFile: string @file(ext: ".ogg")
  PassiveTreeImage: string @file(ext: ".dds")
  _: i32
  _: i32
  BackgroundImage: string
}

type AtlasAwakeningStats {
  AwakeningLevel: i32
  Stats: [Stats]
  Values: [i32]
}

type AtlasBaseTypeDrops {
  Id: string @unique
  AtlasRegionsKey: AtlasRegions
  MinTier: i32
  MaxTier: i32
  SpawnWeight_TagsKeys: [Tags]
  SpawnWeight_Values: [i32]
}

type AtlasFog {
  _: i32
  _: i32
  _: i32
  _: i32
}

type AtlasInfluenceData {
  InfluencePack: AtlasInfluenceOutcomes
  MonsterPacks: [MonsterPacks]
  _: rid
  _: [Stats]
  _: i32
  _: [i32]
  _: [i32]
  _: i32
  _: i32
}

type AtlasInfluenceOutcomes {
  Id: string
  _: i32
  Type: AtlasInfluenceOutcomeTypes
}

enum AtlasInfluenceOutcomeTypes @indexing(first: 0) {
  MONSTER_PACKS
  EMPOWERED_BOSS
  ON_KILL
  INITIAL_PACKS
  AWAKENER
}

type AtlasInfluenceSets {
  Id: string
  InfluencePacks: [AtlasInfluenceOutcomes]
}

type AtlasMods {
  ModsKey: Mods
  AtlasModTiers: i32
}

type AtlasFavouredMapSlots {
  _: i32
  _: i32
  Requirement: string
}

enum AtlasModTiers @indexing(first: 0) { _ }

type AtlasNode {
  WorldAreasKey: WorldAreas
  ItemVisualIdentityKey: ItemVisualIdentity
  _: bool
  MapsKey: Maps
  FlavourTextKey: FlavourText
  AtlasNodeKeys: [AtlasNode]
  Tier0: i32
  Tier1: i32
  Tier2: i32
  Tier3: i32
  Tier4: i32
  _: f32
  _: f32
  _: f32
  _: f32
  _: f32
  DDSFile: string @file(ext: ".dds")
  _: bool
  NotOnAtlas: bool
}

type AtlasNodeDefinition {
  WorldAreasKey: WorldAreas
  ItemVisualIdentityKey: ItemVisualIdentity
  _: bool
  Tier: i32
  _: i32
  _: i32
}

type AtlasPositions {
  _: i32
  _: i32
  X: f32
  Y: f32
}

enum AtlasQuadrant @indexing(first: 0) { _ }

type AtlasRegions {
  Id: string @unique
  Name: string
  _: i32
  _: rid
  _: f32
  _: f32
  _: rid
  CitadelName: string
  _: i32
  BK2File: string @file(ext: ".bk2")
  _: i32
  AdviceAudio: NPCTextAudio
  _: rid
  Quest: Quest
}

type AtlasRegionUpgradesInventoryLayout {
  Id: string @unique
  _: i32
  _: i32
  _: rid
  _: rid
}

type AtlasRegionUpgradeRegions {
  _: rid
  _: rid
}

type AtlasSector {
  Id: string @unique
  SpawnWeight_TagsKeys: [Tags]
  SpawnWeight_Values: [i32]
}

enum Attributes @indexing(first: 1) {
  STRENGTH
  DEXTERITY
  INTELLIGENCE
  NONE
}

type AwardDisplay {
  Id: string @unique
  Text: string
  BackgroundImage: string
  _: i32
  _: f32
  _: f32
  _: string
  _: string
  ForegroundImage: string
  OGGFile: string @file(ext: ".ogg")
  _: rid
  _: i32
}

type BackendErrors {
  Id: string @unique
  Text: string
}

type BaseItemTypes {
  Id: string @unique
  ItemClassesKey: ItemClasses
  Width: i32
  Height: i32
  Name: string @localized
  InheritsFrom: string @files(ext: [".ot", ".otc"])
  DropLevel: i32
  FlavourTextKey: FlavourText
  Implicit_ModsKeys: [Mods]
  SizeOnGround: i32
  SoundEffect: SoundEffects
  TagsKeys: [Tags]
  ModDomain: ModDomains
  SiteVisibility: BaseItemTypeVisibility
  ItemVisualIdentity: ItemVisualIdentity
  HASH32: i32 @unique
  VendorRecipe_AchievementItems: [AchievementItems]
  "the inflection identifier used for i18n in related fields"
  Inflection: string
  Equip_AchievementItemsKey: AchievementItems
  IsCorrupted: bool
  Identify_AchievementItems: [AchievementItems]
  IdentifyMagic_AchievementItems: [AchievementItems]
  "the item which represents this item in the fragment stash tab"
  FragmentBaseItemTypesKey: BaseItemTypes
  _: bool
  _: rid
  _: rid
  _: bool
  TradeMarketCategory: TradeMarketCategory
  _: bool
  Achievement: [AchievementItems]
}

enum BaseItemTypeVisibility @indexing(first: 0) {
  HIDDEN
  VISIBLE
  _
}

type BindableVirtualKeys {
  KeyCode: i32
  Name: string
  Id: string
}

type BlightStashTabLayout {
  Id: string @unique
  BaseItemTypesKey: BaseItemTypes
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: bool
}

type BloodTypes {
  Id: string
  _: rid
  _: rid
  _: [rid]
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
}

enum BuffCategories @indexing(first: 0) { _ }

type BuffDefinitions {
  Id: string @unique
  Description: string
  Invisible: bool
  Removable: bool
  Name: string
  StatsKeys: [Stats]
  _: bool
  _: i32
  _: bool
  Maximum_StatsKey: Stats
  Current_StatsKey: Stats
  _: bool
  _: i32
  BuffVisualsKey: BuffVisuals
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: bool
  _: bool
  BuffLimit: i32
  _: bool
  Id2: string
  IsRecovery: bool
  _: bool
  _: rid
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: [i32]
  _: bool
  _: bool
  _: [rid]
  _: bool
  _: [Stats]
  _: [Stats]
  _: [Stats]
  _: [Stats]
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: Stats
  _: [i32]
  _: string
  _: [Stats]
}

enum BuffGroups @indexing(first: 0) { _ }

enum BuffMergeModes @indexing(first: 0) { _ }

enum BuffStackUIModes @indexing(first: 0) { _ }

type BuffTemplates {
  Id: string @unique
  BuffDefinitionsKey: BuffDefinitions
  _: [i32]
  AuraRadius: i32
  _: [i32]
  _: [i32]
  BuffVisualsKey: BuffVisuals
  _: f32
  _: bool
  StatsKey: [Stats]
  _: i32
  _: i32
  _: bool
  _: Stats
}

type BuffVisualOrbArt {
  Id: string @unique
  MiscAnimated: MiscAnimated
  _: [i32]
  _: [string]
  _: string
  _: string
  _: string
  _: string
}

type BuffVisualOrbs {
  Id: string @unique
  BuffVisualOrbTypesKey: BuffVisualOrbTypes
  BuffVisualOrbArtKeys: [BuffVisualOrbArt]
  Player_BuffVisualOrbArtKeys: [BuffVisualOrbArt]
  BuffVisualOrbArtKeys2: [BuffVisualOrbArt]
}

type BuffVisualOrbTypes {
  Id: string @unique
  _: f32
  _: f32
  _: f32
  _: f32
  _: i32
  _: bool
  _: rid
  _: rid
  _: i32
  _: bool
  _: f32
  _: i32
  _: f32
  _: bool
  _: f32
}

type BuffVisuals {
  Id: string @unique
  BuffDDSFile: string @file(ext: ".dds")
  EPKFiles1: [string] @file(ext: ".epk")
  EPKFiles2: [string] @file(ext: ".epk")
  PreloadGroups: [PreloadGroups]
  _: bool
  BuffName: string
  MiscAnimated1: MiscAnimated
  MiscAnimated2: MiscAnimated
  BuffDescription: string
  EPKFile: string @file(ext: ".epk")
  HasExtraArt: bool
  ExtraArt: string
  _: [i32]
  EPKFiles: [string] @file(ext: ".epk")
  BuffVisualOrbs: [BuffVisualOrbs]
  MiscAnimated3: MiscAnimated
  _: rid
}

type BuffVisualsArtVariations {
  Buff: string
  _: [_]
  _: i32
}

type BuffVisualSetEntries {
  Id: string @unique
  _: i32
  BuffVisual: BuffVisuals
  _: i32
}

enum BuffVisualSets @indexing(first: 0) { _ }

type CharacterAudioEvents {
  Id: string @unique
  Event: QuestFlags
  _: i32
  _: i32
  "For the Goddess Bound/Scorned/Unleashed unique"
  Goddess_CharacterTextAudioKeys: [CharacterTextAudio]
  "For Jack the Axe unique"
  JackTheAxe_CharacterTextAudioKeys: [CharacterTextAudio]
  _: bool
  _: bool
}

type CharacterEventTextAudio {
  Event: CharacterAudioEvents
  Character: Characters
  TextAudio: [CharacterTextAudio]
}

type CharacterPanelDescriptionModes {
  Id: string @unique
  _: string
  FormatString_Positive: string
  FormatString_Negative: string
}

enum CharacterPanelStatContexts @indexing(first: 0) { _ }

type CharacterPanelStats {
  Id: string @unique
  Text: string
  StatsKeys1: [Stats]
  CharacterPanelDescriptionModesKey: CharacterPanelDescriptionModes
  StatsKeys2: [Stats]
  StatsKeys3: [Stats]
  CharacterPanelTabsKey: CharacterPanelTabs
  _: bool
  _: [i32]
  _: i32
}

type CharacterPanelTabs {
  Id: string @unique
  _: i32
  Text: string
  _: i32
}

type Characters {
  Id: string @unique
  Name: string @unique @localized
  AOFile: string @file(ext: ".ao")
  ACTFile: string @file(ext: ".act")
  BaseMaxLife: i32
  BaseMaxMana: i32
  "Attack Speed in milliseconds"
  WeaponSpeed: i32
  MinDamage: i32
  MaxDamage: i32
  MaxAttackDistance: i32
  Icon: string
  IntegerId: i32 @unique
  BaseStrength: i32
  BaseDexterity: i32
  BaseIntelligence: i32
  _: [rid]
  Description: string @localized
  StartSkillGem: SkillGems
  _: rid
  _: i32
  _: i32
  CharacterSize: i32
  IntroSoundFile: string @file(ext: ".ogg")
  StartWeapons: [BaseItemTypes]
  Gender: string
  TraitDescription: string @localized
  _: rid
  _: rid
  _: rid
  _: rid
  _: i32
  _: [rid]
  PassiveTreeImage: string @file(ext: ".dds")
  _: i32
  _: i32
  TencentVideo: string @file(ext: ".bk2")
  AttrsAsId: string
  LoginScreen: string @file(ext: ".ao")
  PlayerCritter: string
  PlayerEffect: string
  AfterImage: string
  Mirage: MonsterVarieties
  CloneImmobile: MonsterVarieties
  ReplicateClone: MonsterVarieties
  LightningClone: MonsterVarieties
  _: f32
  _: f32
  SkillTreeBackground: string
  Clone: MonsterVarieties
  Double: MonsterVarieties
  MirageWarrior: MonsterVarieties
  DoubleTwo: MonsterVarieties
  DarkExile: MonsterVarieties
  Attr: string
  AttrLowercase: string
  Script: string
  _: rid
  _: i32
}

type CharacterStartQuestState {
  Id: string
  QuestKeys: [Quest]
  QuestStates: [i32]
  _: [rid]
  MapPinsKeys: [MapPins]
  _: [i32]
  _: [rid]
}

type CharacterStartStates {
  Id: string @unique
  Description: string
  CharactersKey: Characters
  Level: i32
  PassiveSkillsKeys: [PassiveSkills]
  CharacterStartStateSetKey: CharacterStartStateSet
  _: rid
  CharacterStartQuestStateKeys: [CharacterStartQuestState]
  _: bool
  InfoText: string
  _: rid
}

type CharacterStartStateSet {
  Id: string
}

type CharacterTextAudio {
  Id: string @unique
  Text: string
  SoundFile: string @file(ext: ".ogg")
}

type ChatIcons {
  Icon: string
  Image: string
}

type ChestClusters {
  Id: string @unique
  ChestsKeys: [Chests]
  _: [i32]
  _: i32
  _: i32
  _: i32
}

type ChestEffects {
  Id: string @unique
  Normal_EPKFile: string @file(ext: ".epk")
  Normal_Closed_AOFile: string @file(ext: ".ao")
  Normal_Open_AOFile: string @file(ext: ".ao")
  Magic_EPKFile: string @file(ext: ".epk")
  Unique_EPKFile: string @file(ext: ".epk")
  Rare_EPKFile: string @file(ext: ".epk")
  Magic_Closed_AOFile: string @file(ext: ".ao")
  Unique_Closed_AOFile: string @file(ext: ".ao")
  Rare_Closed_AOFile: string @file(ext: ".ao")
  Magic_Open_AOFile: string @file(ext: ".ao")
  Unique_Open_AOFile: string @file(ext: ".ao")
  Rare_Open_AOFile: string @file(ext: ".ao")
}

type Chests {
  Id: string @unique
  _: bool
  _: i32
  Name: string
  AOFiles: [string] @file(ext: ".ao")
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: [rid]
  BaseItemTypesKey: BaseItemTypes
  _: bool
  ModsKeys: [Mods]
  TagsKeys: [Tags]
  ChestEffectsKey: ChestEffects
  MinLevel: i32
  _: string
  MaxLevel: i32
  Corrupt_AchievementItemsKey: AchievementItems
  CurrencyUse_AchievementItemsKey: AchievementItems
  Encounter_AchievementItemsKeys: [AchievementItems]
  _: rid
  InheritsFrom: string @files(ext: [".ot", ".otc"])
  _: bool
  _: rid
  _: [i32]
  _: string
  _: i32
  _: i32
  _: bool
  _: rid
  _: rid
  _: bool
  _: bool
  _: [rid]
  IsHardmode: bool
  StatsHardmode: [Stats]
}

type ClientStrings {
  Id: string @unique
  Text: string
  XBoxText: string
  XBoxText2: string
  HASH32: i32
  PlaystationText: string
}

type ClientLeagueAction {
  Id: string
  _: rid
  _: i32
  GamepadIcon: string
}

enum ClientUIScreens @indexing(first: 0) { _ }

type CloneShot {
  Id: i32 @unique
  MonsterVarietiesKey: MonsterVarieties
  MiscAnimated1: MiscAnimated
  MiscAnimated2: MiscAnimated
  MiscAnimated3: MiscAnimated
}

type Colours {
  Item: string
  Red: i32
  Green: i32
  Blue: i32
  RgbCode: string
}

type Commands {
  Id: string @unique
  Command: string
  _: bool
  EnglishCommand: string
  Description: string
  _: bool
}

type ComponentAttributeRequirements {
  BaseItemTypesKey: BaseItemTypes @ref(column: "Id") @unique
  ReqStr: i32
  ReqDex: i32
  ReqInt: i32
}

type ComponentCharges {
  BaseItemTypesKey: BaseItemTypes @ref(column: "Id") @unique
  MaxCharges: i32
  PerCharge: i32
  MaxCharges2: i32
  PerCharge2: i32
}

enum CooldownBypassTypes @indexing(first: 1) { _ }

enum CooldownGroups @indexing(first: 0) { _ }

type CoreLeagues {
  Id: string
  _: bool
  _: bool
  _: Stats
  _: [Stats]
  _: Stats
  _: Stats
  _: Stats
  _: [Stats]
  _: Stats
  _: rid
  _: i32
  _: bool
  _: Stats
  _: [Stats]
  _: bool
  _: bool
  _: [Stats]
}

type CostTypes {
  Id: string @unique
  StatsKey: Stats
  FormatText: string
  _: i32
}

enum CraftingBenchCustomActions @indexing(first: 0) {
  REMOVE_CRAFTED_MODS
	REMOVE_ENCHANT_MODS
}

type CraftingBenchOptions {
  HideoutNPCsKey: HideoutNPCs
  Order: i32
  AddMod: Mods
  Cost_BaseItemTypes: [BaseItemTypes]
  Cost_Values: [i32]
  RequiredLevel: i32
  Name: string
  CraftingBenchCustomAction: CraftingBenchCustomActions
  ItemClasses: [ItemClasses]
  Links: i32
  SocketColours: string
  Sockets: i32
  ItemQuantity: i32
  _: [i32]
  Description: string
  IsDisabled: bool
  IsAreaOption: bool
  RecipeIds: [RecipeUnlockDisplay] @ref(column: "RecipeId")
  Tier: i32
  CraftingItemClassCategories: [CraftingItemClassCategories]
  _: i32
  UnlockCategory: CraftingBenchUnlockCategories
  UnveilsRequired: i32
  UnveilsRequired2: i32
  _: [rid]
  _: [rid]
  _: i32
  _: i32
  _: rid
  AddEnchantment: Mods
  SortCategory: CraftingBenchSortCategories
  _: rid
  _: bool
  _: i32
  _: Stats #"stat granted by kirac mod"
  _: Stats #"stat granted by kirac mod"
  _: Stats #"stat granted by kirac mod"
}

type CraftingBenchSortCategories {
  Id: string @unique
  Name: ClientStrings
  IsVisible: bool
}

type CraftingBenchUnlockCategories {
  Id: string @unique
  _: i32
  _: [i32]
  UnlockType: string
  CraftingItemClassCategories: [CraftingItemClassCategories]
  ObtainingDescription: string
}

type CraftingItemClassCategories {
  Id: string @unique
  ItemClasses: [ItemClasses]
  _: string
  Text: string
}

type CurrencyItems {
  BaseItemTypesKey: BaseItemTypes @unique
  Stacks: i32
  CurrencyUseType: i32
  Action: string
  Directions: string
  "Full stack transforms into this item"
  FullStack_BaseItemTypesKey: BaseItemTypes
  Description: string
  Usage_AchievementItemsKeys: [AchievementItems]
  _: bool
  CosmeticTypeName: string
  Possession_AchievementItemsKey: AchievementItems
  _: [rid]
  _: [i32]
  CurrencyTab_StackSize: i32
  XBoxDirections: string
  _: i32
  _: rid
  _: rid
  ModifyMapsAchievements: [AchievementItems]
  ModifyContractsAchievements: [AchievementItems]
  CombineAchievements: [AchievementItems]
  _: i32
  _: [i32]
  ShopTag: ShopTag
  IsHardmode: bool
  DescriptionHardmode: string
  IsGold: bool
}

type CurrencyStashTabLayout {
  Id: string
  BaseItemTypesKey: BaseItemTypes
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
}

enum CurrencyUseTypes @indexing(first: 0) { _ }

type CustomLeagueMods {
  Id: string @unique
  _: [rid]
  _: [i32]
  _: bool
  _: bool
  _: i32
  _: rid
  _: i32
  _: rid
  _: i32
}

type DaemonSpawningData {
  Id: string
  MonsterVarieties: [MonsterVarieties]
  _: i32
  _: bool
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
}

type DamageHitEffects {
  Id: i32
  _: i32
  _: i32
  _: rid
  _: rid
}

type DamageParticleEffects {
  DamageParticleEffectTypes: DamageParticleEffectTypes
  Variation: i32
  PETFile: string @file(ext: ".pet")
  ImpactSoundData1: ImpactSoundData
  ImpactSoundData2: ImpactSoundData
  _: i32
}

enum DamageParticleEffectTypes @indexing(first: 0) { _ }

type Dances {
  BaseItemTypesKey: BaseItemTypes
  CharactersKey: Characters
}

type DaressoPitFights {
  Id: string @unique
  _: rid
  _: i32
  _: [i32]
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
}

enum Default @indexing(first: 0) { _ }

type DefaultMonsterStats {
  DisplayLevel: string
  Damage: f32
  Evasion: i32
  Accuracy: i32
  Life: i32
  Experience: i32
  AllyLife: i32
  _: i32
  Difficulty: i32
  Damage2: f32
  _: i32
  _: f32
  _: f32
  _: i32
  _: i32
  Armour: i32
}

type DeliriumStashTabLayout {
  Id: string @unique
  BaseItemType: BaseItemTypes
  X: i32
  Y: i32
  IntId: i32 @unique
  Width: i32
  Height: i32
  _: i32
  _: bool
}

type DelveStashTabLayout {
  Id: string @unique
  BaseItemTypesKey: BaseItemTypes
  X: i32
  Y: i32
  IntId: i32 @unique
  Width: i32
  Height: i32
  StackSize: i32
  HideIfNoneOwned: bool
  Image: string
}

type DescentExiles {
  Id: string @unique
  WorldAreasKey: WorldAreas
  CharactersKey: Characters
  MonsterVarietiesKey: MonsterVarieties
  _: i32
}

type DescentRewardChests {
  Id: string @unique
  BaseItemTypesKeys1: [BaseItemTypes]
  BaseItemTypesKeys2: [BaseItemTypes]
  BaseItemTypesKeys3: [BaseItemTypes]
  BaseItemTypesKeys4: [BaseItemTypes]
  BaseItemTypesKeys5: [BaseItemTypes]
  BaseItemTypesKeys6: [BaseItemTypes]
  BaseItemTypesKeys7: [BaseItemTypes]
  BaseItemTypesKeys8: [BaseItemTypes]
  BaseItemTypesKeys9: [BaseItemTypes]
  BaseItemTypesKeys10: [BaseItemTypes]
  BaseItemTypesKeys11: [BaseItemTypes]
  BaseItemTypesKeys12: [BaseItemTypes]
  WorldAreasKey: WorldAreas
  BaseItemTypesKeys13: [BaseItemTypes]
  BaseItemTypesKeys14: [BaseItemTypes]
}

type DescentStarterChest {
  Id: string @unique
  CharactersKey: Characters
  BaseItemTypesKey: BaseItemTypes
  SocketColours: string
  WorldAreasKey: WorldAreas
}

type DialogueEvent {
  Id: string @unique
  Timer: i32
}

enum Directions @indexing(first: 0) { _ }

type DisplayMinionMonsterType {
  Id: i32 @unique
  MonsterVarietiesKey: MonsterVarieties
}

type DivinationCardStashTabLayout {
  BaseItemTypesKey: BaseItemTypes @unique
  IsEnabled: bool
  _: bool
}

type Doors {
  Id: string @unique
  _: bool
}

type DropEffects {
  Id: string @unique
  AOFile: string @file(ext: ".ao")
}

type DropPool {
  Group: string @unique
  Weight: i32
  _: [i32]
  WeightHardmode: i32
}

type EclipseMods {
  Key: string @unique
  SpawnWeight_TagsKeys: [Tags]
  SpawnWeight_Values: [i32]
  ModsKey: Mods
  MinLevel: i32
  MaxLevel: i32
  IsPrefix: bool
}

type EffectDrivenSkill {
  _: i32
  _: [rid]
  _: [_]
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: [_]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
}

enum Effectiveness @indexing(first: 0) { _ }

type EffectivenessCostConstants {
  Id: string @unique
  Multiplier: f32
}

type EinharMissions {
  Id: string
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type EinharPackFallback {
  _: rid
  _: [rid]
}

type EndlessLedgeChests {
  Id: string @unique
  WorldAreasKey: WorldAreas
  BaseItemTypesKeys: [BaseItemTypes]
  SocketColour: string
}

type Environments {
  Id: string @unique
  Base_ENVFile: string @file(ext: ".env")
  Corrupted_ENVFile: string @file(ext: ".env")
  _: rid
  _: rid
  _: [_]
  EnvironmentTransitionsKey: EnvironmentTransitions
  PreloadGroup: PreloadGroups
}

type EnvironmentTransitions {
  Id: string
  OTFiles: [string] @file(ext: ".ot")
  _: [string]
}

type EssenceStashTabLayout {
  Id: string @unique
  BaseItemTypesKey: BaseItemTypes
  X: i32
  Y: i32
  IntId: i32 @unique
  SlotWidth: i32
  SlotHeight: i32
  IsUpgradableEssenceSlot: bool
}

type EventSeason {
  Id: string @unique
  _: i32
  RewardCommand: string
}

type EventSeasonRewards {
  EventSeasonKey: EventSeason
  Point: i32
  RewardCommand: string
}

type EvergreenAchievements {
  _: i32
  _: i32
  _: [rid]
}

enum EvergreenAchievementTypes @indexing(first: 0) { _ }

type ExecuteGEAL {
  _: i32
  MiscAnimated: [MiscAnimated]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: bool
  _: [_]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: string
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  MetadataIDs: [string] @files(ext: [".ot", ".otc"])
  ScriptCommand: string
  _: string
  _: string
  _: string
  _: string
  _: i32
  _: bool
  _: bool
  _: [_]
  _: i32
}

type ExpandingPulse {
  IntId: i32 @unique
  StringId: string @unique
  _: [i32]
  _: [f32]
  _: [rid]
  _: i32
  _: i32
  _: bool
}

type ExperienceLevels {
  _: string
  Level: i32
  Experience: i32
}

type ExplodingStormBuffs {
  Id: string @unique
  BuffDefinitionsKey1: BuffDefinitions
  _: rid
  StatValues: [i32]
  _: i32
  _: [i32]
  _: i32
  _: i32
  _: i32
  Friendly_MonsterVarietiesKey: MonsterVarieties
  MiscObjectsKey: MiscObjects
  MiscAnimatedKey: MiscAnimated
  BuffVisualsKey: BuffVisuals
  Enemy_MonsterVarietiesKey: MonsterVarieties
  _: i32
  _: i32
  _: i32
  BuffDefinitionsKey2: BuffDefinitions
  IsOnlySpawningNearPlayer: bool
}

type ExtraTerrainFeatures {
  Id: string @unique
  ArmFiles: [string] @file(ext: ".arm")
  TdtFiles: [string] @file(ext: ".tdt")
  _: bool
  _: [string]
  _: [i32]
  _: ExtraTerrainFeatures
  WorldAreasKey: WorldAreas
  _: bool
  _: i32
}

type FixedHideoutDoodadTypes {
  Id: string
  HideoutDoodadsKeys: [HideoutDoodads]
  BaseTypeHideoutDoodadsKey: HideoutDoodads
}

type FixedMissions {
  _: QuestAchievements
  _: rid
  _: [i32]
  _: rid
  _: rid
  _: i32
  _: i32
  _: i32
}

type Flasks {
  BaseItemTypesKey: BaseItemTypes @unique
  Name: string
  Group: i32
  LifePerUse: i32
  ManaPerUse: i32
  "in 1/10 s"
  RecoveryTime: i32
  BuffDefinitionsKey: BuffDefinitions
  BuffStatValues: [i32]
  RecoveryTime2: i32
  BuffStatValues2: [i32]
}

enum FlaskType @indexing(first: 0) { _ }

type FlavourText {
  Id: string @unique
  _: i32
  Text: string
}

enum FlavourTextImages @indexing(first: 0) { _ }

type Footprints {
  Id: string
  Active_AOFiles: [string] @file(ext: ".ao")
  Idle_AOFiles: [string] @file(ext: ".ao")
  _: [string] @file(ext: ".ao")
  _: [string] @file(ext: ".ao")
  _: i32
}

type FootstepAudio {
  Id: string
  Index: i32
}

type FragmentStashTabLayout {
  Id: string
  PosX: i32
  PosY: i32
  Order: i32
  SizeX: i32
  SizeY: i32
  _: bool
  Tab: i32
  _: i32
  IsDisabled: bool
  Subtab: i32
  FragmentItems: [BaseItemTypes]
}

type GameConstants {
  Id: string @unique
  Value: i32
  _: i32
}

type GameLogos {
  Id: string
  LogoIntl: string
  LogoTW: string
}

type GameObjectTasks {
  Id: string
  HASH16: i32
}

type GamepadButton {
  _: string
  _: string
  _: string
  _: string
}

type GamepadType {
  Id: string
  Console: string
  ImageFile: string
}

type GameStats {
  Id: string @unique
  Id2: string @unique
}

type GemTags {
  Id: string @unique
  Tag: string
  Stat1: Stats
  Stat2: Stats
  Stat3: Stats
  Stat4: Stats
}

enum GemTypes @indexing(first: 0) { _ }

type GenericBuffAuras {
  Id: string @unique
}

type GenericLeagueRewardTypes {
  Id: string
  MinLevel: i32
  MaxLevel: i32
}

type GenericLeagueRewardTypeVisuals {
  Type: GenericLeagueRewardTypes
  _: rid
  _: rid
  _: f32
  Icon: string
  Name: string @localized
}

type GeometryAttack {
  _: i32
  _: [rid]
  _: [rid]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: [_]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: rid
  _: [i32]
  _: i32
  _: bool
  _: bool
  _: rid
  _: bool
  _: [i32]
  _: bool
  _: bool
  _: rid
  _: bool
  _: bool
  _: [_]
  _: bool
  _: bool
  _: bool
  _: bool
}

type GeometryChannel {
  Id: string @unique
  _: rid
  _: rid
  _: rid
  _: string
  _: string
  _: string
  _: bool
  _: bool
  _: rid
  _: rid
  EPKFile: string @file(ext: ".epk")
  _: i32
  _: i32
}

type GeometryProjectiles {
  _: i32
  _: rid
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: rid
  _: bool
  _: rid
  _: i32
}

type GeometryTrigger {
  _: i32
  _: rid
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  _: [rid]
  _: i32
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: rid
  _: bool
  _: bool
  _: bool
  _: i32
  _: i32
  _: [rid]
  _: [i32]
  _: i32
  _: i32
  _: i32
  _: bool
}

type GiftWrapArtVariations {
  _: i32
  _: i32
  _: i32
  _: rid
}

type GlobalAudioConfig {
  Id: string @unique
  Value: i32
  _: bool
}

type Grandmasters {
  Id: string
  GMFile: string @file(ext: ".gm")
  AISFile: string @file(ext: ".ais")
  ModsKeys: [Mods]
  CharacterLevel: i32
  _: bool
}

enum GrantedEffectGroups @indexing(first: 0) { _ }

type GrantedEffectQualityStats {
  GrantedEffectsKey: GrantedEffects
  SetId: i32
  StatsKeys: [Stats]
  StatsValuesPermille: [i32]
  Weight: i32
  _: [i32]
  _: [i32]
}

type GrantedEffectQualityTypes {
  Id: i32 @unique
  Text: string
  ClientStringsKey: ClientStrings
}

type GrantedEffects {
  Id: string @unique
  IsSupport: bool
  "This support gem only supports active skills with at least one of these types"
  AllowedActiveSkillTypes: [ActiveSkillType]
  SupportGemLetter: string
  Attribute: Attributes
  "This support gem adds these types to supported active skills"
  AddedActiveSkillTypes: [ActiveSkillType]
  "This support gem does not support active skills with one of these types"
  ExcludedActiveSkillTypes: [ActiveSkillType]
  "This support gem only supports active skills that come from gem items"
  SupportsGemsOnly: bool
  _: i32
  _: [i32]
  CannotBeSupported: bool
  _: i32
  CastTime: i32
  ActiveSkill: ActiveSkills
  IgnoreMinionTypes: bool
  _: bool
  AddedMinionActiveSkillTypes: [ActiveSkillType]
  Animation: Animation
  MultiPartAchievement: MultiPartAchievements
  _: bool
  SupportWeaponRestrictions: [ItemClasses]
  RegularVariant: GrantedEffects
  _: i32
  _: i32
  _: i32
  _: bool
  StatSet: GrantedEffectStatSets
  _: [rid]
}

type GrantedEffectsPerLevel {
  GrantedEffect: GrantedEffects
  Level: i32
  PlayerLevelReq: f32
  CostMultiplier: i32
  StoredUses: i32
  Cooldown: i32
  CooldownBypassType: CooldownBypassTypes
  VaalSouls: i32
  VaalStoredUses: i32
  CooldownGroup: i32
  _: i32
  SoulGainPreventionDuration: i32
  AttackSpeedMultiplier: i32
  _: i32
  CostAmounts: [i32]
  CostTypes: [CostTypes]
  ManaReservationFlat: i32
  ManaReservationPercent: i32
  LifeReservationFlat: i32
  LifeReservationPercent: i32
  AttackTime: i32
}

type GrantedEffectStatSets {
  Id: string @unique
  ImplicitStats: [Stats]
  ConstantStats: [Stats]
  ConstantStatsValues: [i32]
  BaseEffectiveness: f32
  IncrementalEffectiveness: f32
  _: i32
}

type GrantedEffectStatSetsPerLevel {
  StatSet: GrantedEffectStatSets
  GemLevel: i32
  PlayerLevelReq: f32
  SpellCritChance: i32
  AttackCritChance: i32
  BaseMultiplier: i32
  DamageEffectiveness: i32
  AdditionalFlags: [Stats]
  FloatStats: [Stats]
  InterpolationBases: [Stats]
  AdditionalStats: [Stats]
  StatInterpolations: [StatInterpolationTypes]
  FloatStatsValues: [f32]
  BaseResolvedValues: [i32]
  AdditionalStatsValues: [i32]
  GrantedEffects: [GrantedEffects]
}

enum GroundEffectEffectTypes @indexing(first: 0) { _ }

type GroundEffects {
  GroundEffectTypesKey: GroundEffectTypes
  _: i32
  _: i32
  _: rid
  _: f32
  _: [i32]
  _: bool
  AOFile: [string] @file(ext: ".ao")
  _: [string]
  EndEffect: string
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: bool
  _: bool
  _: bool
  _: rid
  _: rid
  _: bool
  _: bool
}

type GroundEffectTypes {
  Id: string @unique
  _: i32
  _: f32
  _: rid
  _: rid
  _: rid
}

type HarvestStorageLayout {
  Id: string @unique
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  Button: string
  ButtonHighlight: string
  HasButton: bool
}

type HeistStorageLayout {
  Id: string @unique
  BaseItemType: BaseItemTypes
  _: bool
  ButtonFile: string
  _: i32
  HeistJobsKey: HeistJobs
  Columns: i32
  Rows: i32
  _: i32
  _: i32
  _: i32
  _: i32
  ItemClass: ItemClasses
}

type HideoutDoodads {
  BaseItemTypesKey: BaseItemTypes @unique
  Variation_AOFiles: [string] @file(ext: ".ao")
  IsNonMasterDoodad: bool
  InheritsFrom: string @files(ext: [".ot", ".otc"])
  _: bool
  IsCraftingBench: bool
  Tags: [HideoutDoodadTags]
  _: bool
  _: rid
  Category: HideoutDoodadCategory
  _: i32
  _: bool
  _: rid
  _: bool
  _: rid
}

type HideoutDoodadCategory {
  Id: string
  Name: string @localized
}

type HideoutDoodadTags {
  Id: string
  _: [i32]
  _: [i32]
  Name: string @localized
}

type HideoutNPCs {
  Hideout_NPCsKey: NPCs
  Regular_NPCsKeys: [NPCs]
  HideoutDoodadsKey: HideoutDoodads
  NPCMasterKey: i32
  _: rid
  _: rid
  _: i32
  _: rid
  _: i32
  _: bool
  _: rid
}

type HideoutRarity {
  Id: string @unique
  Text: string
}

type Hideouts {
  Id: string @unique
  HideoutArea: WorldAreas
  HASH16: i32
  HideoutFile: string @file(ext: ".hideout")
  SpawnAreas: [WorldAreas]
  ClaimSideArea: WorldAreas
  HideoutImage: string
  IsEnabled: bool
  Weight: i32
  Rarity: HideoutRarity
  NotActsArea: bool
  Name: string
  _: [i32]
  _: bool
  _: bool
  _: bool
  _: bool
}

type ImpactSoundData {
  Id: string @unique
  "Located in Audio/SoundEffects. Format has SG removed and $(#) replaced with the number"
  Sound: string
  _: i32
  _: i32
  _: i32
  _: i32
}

type IndexableSupportGems {
  Index: i32 @unique
  SupportGem: SkillGems
  Name: string
}

type InfluenceExalts {
  Id: i32 @unique
  BaseItemTypesKey: BaseItemTypes
}

type InfluenceTags {
  ItemClass: ItemClasses
  Influence: InfluenceTypes
  Tag: Tags
}

enum InfluenceTypes @indexing(first: 0) {
  SHAPER
  ELDER
  CRUSADER
  EYRIE
  BASILISK
  ADJUDICATOR
  NONE
 }

type Inventories {
  Id: string
  InventoryIdKey: InventoryId
  InventoryTypeKey: InventoryType
  _: i32
  _: bool
  _: bool
  _: bool
}

enum InventoryId @indexing(first: 0) { _ }

enum InventoryType @indexing(first: 0) { _ }

type ItemClassCategories {
  Id: string @unique
  Text: string
  _: rid
}

type ItemClasses {
  Id: string @unique
  Name: string
  TradeMarketCategory: TradeMarketCategory
  ItemClassCategory: ItemClassCategories
  RemovedIfLeavesArea: bool
  _: [_]
  IdentifyAchievements: [AchievementItems]
  AllocateToMapOwner: bool
  AlwaysAllocate: bool
  CanHaveVeiledMods: bool
  PickedUpQuest: QuestFlags
  _: i32
  AlwaysShow: bool
  CanBeCorrupted: bool
  CanHaveIncubators: bool
  CanHaveInfluence: bool
  CanBeDoubleCorrupted: bool
  CanHaveAspects: bool
  CanTransferSkin: bool
  ItemStance: ItemStances
  CanScourge: bool
  CanUpgradeRarity: bool # by using Tainted Mythic Orb
  _: bool # 3.17
  _: bool # 3.18
  MaxInventoryDimensions: [i32]
  Flags: [ItemClassFlags]
  IsUnmodifiable: bool
  CanBeFractured: bool
  EquipAchievements: AchievementItems
  _: bool
}

enum ItemClassFlags @indexing(first: 0) {
  WEAPON
  ONE_HAND
  MELEE
  OFF_HAND
  FLASK
  ARMOUR
  JEWELLERY
  CURRENCY
}

type ItemCostPerLevel {
  Contract_BaseItemTypesKey: BaseItemTypes
  Level: i32
  Cost: ItemCosts
  CostHardmode: ItemCosts
}

type ItemCosts {
  Id: string
  Cost1Currencies: [BaseItemTypes]
  Cost1Values: [i32]
  Cost2Currencies: [BaseItemTypes]
  Cost2Values: [i32]
  Cost3Currencies: [BaseItemTypes]
  Cost3Values: [i32]
  Cost4Currencies: [BaseItemTypes]
  Cost4Values: [i32]
}

enum ItemCreationTemplateCustomAction @indexing(first: 0) { _ }

type ItemFrameType {
  Id: string
  _: bool
  DoubleLine: bool
  HeaderSingle: string
  HeaderDouble: string
  HardmodeHeaderSingle: string
  HardmodeHeaderDouble: string
  Color: [i32]
  Separator: string
  _: bool
  Rarity: Rarity
  DisplayString: ClientStrings
  ColorMarkup: string
}

type ItemExperienceTypes {
  Id: string
}

type ItemExperiencePerLevel {
  ItemExperienceType: ItemExperienceTypes
  ItemCurrentLevel: i32
  Experience: i32
}

type ItemisedVisualEffect {
  BaseItemTypesKey: BaseItemTypes
  ItemVisualEffectKey: ItemVisualEffect
  ItemVisualIdentityKey1: ItemVisualIdentity
  ItemVisualIdentityKey2: ItemVisualIdentity
  Stats: [Stats]
  ItemClasses: [ItemClasses]
  _: [rid]
  _: bool
  _: [i32]
  _: [i32]
  _: bool
  _: [_]
  _: bool
}

type ItemNoteCode {
  BaseItem: BaseItemTypes
  Code: string
  Order1: i32
  Show: bool
  Order2: i32
}

enum ItemSetNames @indexing(first: 0) { _ }

type ItemShopType {
  Id: string @unique
  Name: string
}

type ItemStances {
  Id: string @unique
}

type ItemThemes {
  Id: string @unique
  Name: string
}

type ItemVisualEffect {
  Id: string @unique
  DaggerEPKFile: string @file(ext: ".epk")
  BowEPKFile: string @file(ext: ".epk")
  OneHandedMaceEPKFile: string @file(ext: ".epk")
  OneHandedSwordEPKFile: string @file(ext: ".epk")
  _: string
  TwoHandedSwordEPKFile: string @file(ext: ".epk")
  TwoHandedStaffEPKFile: string @file(ext: ".epk")
  _: i32 @unique
  TwoHandedMaceEPKFile: string @file(ext: ".epk")
  OneHandedAxeEPKFile: string @file(ext: ".epk")
  TwoHandedAxeEPKFile: string @file(ext: ".epk")
  ClawEPKFile: string @file(ext: ".epk")
  PETFile: string @file(ext: ".pet")
  Shield: string @file(ext: ".epk")
}

type ItemVisualHeldBodyModel {
  ItemVisualIdentity: ItemVisualIdentity
  MarauderAnimatedObject: string
  RangerAnimatedObject: string
  WitchAnimatedObject: string
  DuelistAnimatedObject: string
  TemplarAnimatedObject: string
  ShadowAnimatedObject: string
  ScionAnimatedObject: string
  MarauderBone: string
  RangerBone: string
  WitchBone: string
  DuelistBone: string
  TemplarBone: string
  ShadowBone: string
  ScionBone: string
}

type ItemVisualIdentity {
  Id: string @unique
  DDSFile: string @file(ext: ".dds")
  AOFile: string @file(ext: ".ao")
  InventorySoundEffect: SoundEffects
  _: i32 @unique
  AOFile2: string @file(ext: ".ao")
  MarauderSMFiles: [string] @file(ext: ".sm")
  RangerSMFiles: [string] @file(ext: ".sm")
  WitchSMFiles: [string] @file(ext: ".sm")
  DuelistDexSMFiles: [string] @file(ext: ".sm")
  TemplarSMFiles: [string] @file(ext: ".sm")
  ShadowSMFiles: [string] @file(ext: ".sm")
  ScionSMFiles: [string] @file(ext: ".sm")
  MarauderShape: string
  RangerShape: string
  WitchShape: string
  DuelistShape: string
  TemplarShape: string
  ShadowShape: string
  ScionShape: string
  _: i32
  _: i32
  Pickup_AchievementItemsKeys: [AchievementItems]
  SMFiles: [string] @file(ext: ".sm")
  Identify_AchievementItemsKeys: [AchievementItems]
  EPKFile: string @file(ext: ".epk")
  Corrupt_AchievementItemsKeys: [AchievementItems]
  IsAlternateArt: bool
  _: bool
  CreateCorruptedJewelAchievementItemsKey: AchievementItems
  AnimationLocation: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  IsAtlasOfWorldsMapIcon: bool
  IsTier16Icon: bool
  _: [i32]
  _: bool
  _: [rid]
  _: string
  _: i32
  _: rid
  _: rid
  _: rid
  _: rid
}

type JobAssassinationSpawnerGroups {
  _: rid
  _: rid
}

type JobRaidBrackets {
  MinLevel: i32
  _: i32
  WorldArea: WorldAreas
  _: i32
  _: i32
  _: i32
  _: i32
}

type KillstreakThresholds {
  Kills: i32
  "Monster that plays the effect, i.e. the 'nova' etc."
  MonsterVarietiesKey: MonsterVarieties
  AchievementItemsKey: AchievementItems
}

enum LeagueCategory @indexing(first: 0) { _ }

type LeagueFlag {
  Id: string @unique
  Image: string
  IsHC: bool
  IsSSF: bool
  Banner: string
  IsRuthless: bool
}

enum LeagueFlags @indexing(first: 0) { _ }

type LeagueInfo {
  LeagueNumber: rid
  InfoClass: string
  PanelImage: string
  HeaderImage: string
  Screenshots: [string]
  Description: string
  _: bool
  TrailerVideoLink: string
  BackgroundImage: string
  _: bool
  _: bool
  PanelItems: [string]
}

type LeagueProgressQuestFlags {
  QuestFlag: QuestFlags
  CompletionString: ClientStrings
  Boss: string
  _: bool
}

enum LeagueQuestFlags @indexing(first: 0) { _ }

type LeagueStaticRewards {
  _: i32
  _: i32
  _: i32
  _: rid
  _: rid
  _: i32
  _: i32
  _: bool
}

enum LeagueTrophy @indexing(first: 0) { _ }

type LevelRelativePlayerScaling {
  PlayerLevel: i32 @unique
  MonsterLevel: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type MagicMonsterLifeScalingPerLevel {
  Level: i32
  Life: i32
}

type MapCompletionAchievements {
  _: string
  MapStatConditionsKeys: [MapStatConditions]
  StatsKeys: [Stats]
  AchievementItemsKeys: [AchievementItems]
  MapTierAchievementsKeys: [MapTierAchievements]
  _: bool
  WorldAreasKeys: [WorldAreas]
}

type MapConnections {
  MapPinsKey0: MapPins
  MapPinsKey1: MapPins
  _: rid
  RestrictedAreaText: string
  _: rid
  _: rid
  _: rid
  _: [_]
}

type MapCreationInformation {
  MapsKey: Maps
  Tier: i32
}

type MapDeviceRecipes {
  Id: string
  RecipeItems: [BaseItemTypes]
  WorldArea: WorldAreas
  MicrotransactionPortalVariation: MicrotransactionPortalVariations
  AreaLevel: i32
  _: rid
  _: i32
  _: bool
  _: bool
  _: bool
  OpenAchievemnts: [AchievementItems]
}

type MapDevices {
  Id: string
  MiscObject: MiscObjects
  _: i32
  _: string
  _: string
  _: [i32]
  _: bool
  _: i32
  _: bool
}

enum MapFragmentFamilies @indexing(first: 0) { _ }

type MapFragmentMods {
  BaseItemTypesKey: BaseItemTypes @unique
  ModsKeys: [Mods]
  AchievementItemsKey: [AchievementItems]
  MapFragmentFamilies: i32
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
}

type MapInhabitants {
  StatsKey: Stats
  MonsterPacksKeys: [MonsterPacks]
}

type MapPins {
  Id: string @unique
  "X starts at left side of image, can be negative"
  PositionX: i32
  "Y starts at top side of image, can be negative"
  PositionY: i32
  Waypoint_WorldAreasKey: WorldAreas
  WorldAreasKeys: [WorldAreas]
  Name: string
  FlavourText: string
  _: [i32]
  Act: i32
  _: string
  _: [i32]
  _: i32
}

type MapPurchaseCosts {
  Tier: i32 @unique
  Cost: ItemCosts
  _: rid
}

type Maps {
  BaseItemTypesKey: BaseItemTypes @unique
  Regular_WorldAreasKey: WorldAreas
  Unique_WorldAreasKey: WorldAreas
  MapUpgrade_BaseItemTypesKey: BaseItemTypes
  MonsterPacksKeys: [MonsterPacks]
  AchievementItem: AchievementItems
  Regular_GuildCharacter: string
  Unique_GuildCharacter: string
  Tier: i32
  Shaped_Base_MapsKey: Maps
  Shaped_AreaLevel: i32
  UpgradedFrom_MapsKey: Maps
  MapsKey2: Maps
  MapsKey3: Maps
  "References MapSeries as an enum: i32, 1-based indexing"
  MapSeriesKey: i32
  _: bool
  _: bool
  _: bool
}

type MapSeries {
  Id: string @unique
  Name: string
  BaseIcon_DDSFile: string @file(ext: ".dds")
  Infected_DDSFile: string @file(ext: ".dds")
  Shaper_DDSFile: string @file(ext: ".dds")
  Elder_DDSFile: string @file(ext: ".dds")
  Drawn_DDSFile: string @file(ext: ".dds")
  Delirious_DDSFile: string @file(ext: ".dds")
  UberBlight_DDSFile: string @file(ext: ".dds")
}

type MapSeriesTiers {
  MapsKey: Maps
  MapWorldsTier: i32
  BetrayalTier: i32
  SynthesisTier: i32
  LegionTier: i32
  BlightTier: i32
  MetamorphosisTier: i32
  DeliriumTier: i32
  HarvestTier: i32
  HeistTier: i32
  RitualTier: i32
  ExpeditionTier: i32
  ScourgeTier: i32
  ArchnemesisTier: i32
  SentinelTier: i32
  KalandraTier: i32
  SanctumTier: i32
  CrucibleTier: i32
}

enum MapStashTabLayout @indexing(first: 0) { _ }

type MapStashSpecialTypeEntries {
  Id: string
  _: i32
  MapItem: BaseItemTypes
  Name: string @localized
  _: i32
  Icon: string @file(ext: ".dds")
  Icon2: string @file(ext: ".dds")
  IsShaperGuardian: bool
  IsElderGuardian: bool
}

type MapStashUniqueMapInfo {
  UniqueMap: UniqueMaps
  BaseItem: BaseItemTypes
}

type MapStatConditions {
  Id: string @unique
  StatsKey: Stats
  _: bool
  StatMin: i32
  StatMax: i32
  _: bool
}

type MapTierAchievements {
  Id: string @unique
  AchievementItemsKey: [AchievementItems]
  MapTiers: [i32]
}

type MapTiers {
  Tier: i32
  Level: i32
  Level2: i32 # 3.18.1
}

type MasterHideoutLevels {
  NPCMasterKey: NPCMaster
  Level: i32
  MissionsRequired: i32
}

type Melee {
  ActiveSkill: ActiveSkills
  _: i32
  MiscAnimated: MiscAnimated
  MeleeTrailsKey1: MeleeTrails
  MeleeTrailsKey2: MeleeTrails
  MeleeTrailsKey3: MeleeTrails
  MeleeTrailsKey4: MeleeTrails
  MeleeTrailsKey5: MeleeTrails
  MeleeTrailsKey6: MeleeTrails
  MeleeTrailsKey7: MeleeTrails
  _: bool
  SurgeEffect_EPKFile: string @file(ext: ".epk")
  _: string
  _: string
}

type MeleeTrails {
  EPKFile1: string @file(ext: ".epk")
  EPKFile2: string @file(ext: ".epk")
  _: i32
  _: i32
  _: i32
  _: bool
  AOFile: string @file(ext: ".ao")
  _: bool
}

type MetamorphosisStashTabLayout {
  Id: string @unique
  BaseItemTypesKey: BaseItemTypes
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  BackgroundImage: string
  ButtonImage: string
}

type MicroMigrationData {
  BaseItemTypesKey: BaseItemTypes
  _: i32
  _: rid
  _: rid
}

enum MicrotransactionCategoryId @indexing(first: 0) { _ }

type MicrotransactionCategory {
  Id: MicrotransactionCategoryId
  Name: string
}

type MicrotransactionCharacterPortraitVariations {
  BaseItemType: BaseItemTypes
}

type MicrotransactionCombineFormula {
  Id: string
  Result_BaseItemTypesKey: BaseItemTypes
  Ingredients_BaseItemTypesKeys: [BaseItemTypes]
  BK2File: string @file(ext: ".bk2")
  _: [i32]
  _: i32
  _: bool
}

type MicrotransactionCursorVariations {
  _: BaseItemTypes
  _: rid
  _: i32
}

type MicrotransactionFireworksVariations {
  BaseItemTypesKey: BaseItemTypes
  AOFile: string @file(ext: ".ao")
  _: bool
}

type MicrotransactionGemCategory {
  _: BaseItemTypes
  Id: string
}

type MicrotransactionPeriodicCharacterEffectVariations {
  Id: string @unique
  AOFile: string @file(ext: ".ao")
  MiscObject: MiscObjects
}

type MicrotransactionPortalVariations {
  BaseItemTypesKey: BaseItemTypes
  Id: i32 @unique
  AOFile: string @file(ext: ".ao")
  MapAOFile: string @file(ext: ".ao")
  _: f32
  MiscObject: MiscObjects
  PortalEffect: string @file(ext: ".ao")
  _: f32
  _: string
  PortalEffectLarge: string @file(ext: ".ao")
  _: string
  _: string
  _: string
  _: i32
  _: i32
}

type MicrotransactionRarityDisplay {
  Rarity: string @unique
  ImageFile: string
}

enum MicrotransactionRecycleCategories @indexing(first: 0) { _ }

type MicrotransactionRecycleOutcomes {
  _: rid
  _: i32
}

type MicrotransactionRecycleSalvageValues {
  BaseItemType: BaseItemTypes
  _: i32
  _: i32
}

enum MicrotransactionSlotId @indexing(first: 1) { _ }

type MicrotransactionSlot {
  Id: MicrotransactionSlotId
  _: rid
  Name: string @localized
}

type MicrotransactionSocialFrameVariations {
  BaseItemTypesKey: BaseItemTypes
  Id: i32 @unique
  BK2File: string @file(ext: ".bk2")
}

type MinimapIcons {
  Id: string
  MinimapIconRadius: i32
  LargemapIconRadius: i32
  _: bool
  _: bool
  _: bool
  MinimapIconPointerMaxDistance: i32
  _: i32
}

type MiniQuestStates {
  _: i32
  _: [_]
  _: [_]
  _: i32
}

type MiscAnimated {
  Id: string @unique
  AOFile: string @file(ext: ".ao")
  PreloadGroupsKeys: [PreloadGroups]
  _: i32
  _: i32
  HASH32: i32
}

type MiscAnimatedArtVariations {
  Id: string
  _: [_]
  _: i32
  _: i32
  _: rid
}

type MiscBeams {
  Id: string @unique
  MiscAnimated: MiscAnimated
  _: i32
  PreloadGroupsKeys: [PreloadGroups]
  _: i32
}

type MiscBeamsArtVariations {
  Id: string
  _: [_]
  _: i32
  _: i32
  _: rid
}

type MiscEffectPacks {
  Id: string @unique
  EPKFile: string @file(ext: ".epk")
  _: i32
  _: i32
  _: i32
  PreloadGroups: [PreloadGroups]
  _: bool
  PlayerOnly_EPKFile: string @file(ext: ".epk")
  _: bool
}

type MiscEffectPacksArtVariations {
  _: string
  _: [_]
  _: i32
}

type MiscObjects {
  Id: string @unique
  EffectVirtualPath: string @files(ext: [".ot", ".otc"])
  PreloadGroupsKeys: [PreloadGroups]
  _: i32
  _: i32
}

type MiscObjectsArtVariations {
  _: string
  _: [_]
  _: i32
  _: i32
  _: rid
}

type MissionFavourPerLevel {
  Level: i32
  Favour: i32
}

enum MissionTileMap @indexing(first: 0) { _ }

type MissionTimerTypes {
  Id: string
  Image: string
  BackgroundImage: string
  _: [rid]
  _: [f32]
  _: rid
  _: rid
}

type MissionTransitionTiles {
  Id: string @unique
  TDTFile: string @file(ext: ".tdt")
  _: i32
  _: i32
  _: i32
}

enum ModAuraFlags @indexing(first: 0) { _ }

enum ModDomains @indexing(first: 1) {
  ITEM
  FLASK
  MONSTER
  CHEST
  AREA
  _
  SANCTUM_RELIC
  _
  CRAFTED
  MISC
  ATLAS
  LEAGUESTONE
  ABYSS_JEWEL
  MAP_DEVICE
  DUMMY
  DELVE
  DELVE_AREA
  SYNTHESIS_A
  SYNTHESIS_GLOBALS
  SYNTHESIS_BONUS
  AFFLICTION_JEWEL
  HEIST_AREA
  HEIST_NPC
  HEIST_TRINKET
  WATCHSTONE
  VEILED
  EXPEDITION_RELIC
  UNVEILED
  ELDRITCH_ALTAR
  SENTINEL
  MEMORY_LINE
  SANCTUM_SPECIAL
  CRUCIBLE_MAP
}

type ModEffectStats {
  StatsKey: Stats
  TagsKeys: [Tags]
  _: bool
  _: i32
  _: bool
}

type ModEquivalencies {
  Id: string @unique
  ModsKey0: Mods
  ModsKey1: Mods
  ModsKey2: Mods
  _: bool
}

type ModFamily {
  Id: string @unique
}

enum ModGenerationType @indexing(first: 1) {
  PREFIX
  SUFFIX
  UNIQUE
  NEMESIS
  CORRUPTED
  BLOODLINES
  TORMENT
  TEMPEST
  TALISMAN
  ENCHANTMENT
  ESSENCE
  _
  BESTIARY
  DELVE_AREA
  SYNTHESIS_A
  SYNTHESIS_GLOBALS
  SYNTHESIS_BONUS
  BLIGHT
  BLIGHT_TOWER
  MONSTER_AFFLICTION
  FLASK_ENCHANTMENT_ENKINDLING
  FLASK_ENCHANTMENT_INSTILLING
  EXPEDITION_LOGBOOK
  SCOURGE_UPSIDE
  SCOURGE_DOWNSIDE
  SCOURGE_MAP
  _
  EXARCH_IMPLICIT
  EATER_IMPLICIT
  _
  WEAPON_TREE
  WEAPON_TREE_RECOMBINED
}

type Mods {
  Id: string @unique
  HASH16: i32
  ModTypeKey: ModType
  Level: i32
  StatsKey1: Stats
  StatsKey2: Stats
  StatsKey3: Stats
  StatsKey4: Stats
  Domain: ModDomains
  Name: string
  GenerationType: ModGenerationType
  Families: [ModFamily]
  Stat1Min: i32
  Stat1Max: i32
  Stat2Min: i32
  Stat2Max: i32
  Stat3Min: i32
  Stat3Max: i32
  Stat4Min: i32
  Stat4Max: i32
  SpawnWeight_TagsKeys: [Tags]
  SpawnWeight_Values: [i32]
  TagsKeys: [Tags]
  GrantedEffectsPerLevelKeys: [GrantedEffectsPerLevel]
  _: [i32]
  MonsterMetadata: string
  MonsterKillAchievements: [AchievementItems]
  ChestModType: [ModType]
  Stat5Min: i32
  Stat5Max: i32
  StatsKey5: Stats
  FullAreaClear_AchievementItemsKey: [AchievementItems]
  AchievementItemsKey: [AchievementItems]
  GenerationWeight_TagsKeys: [Tags]
  GenerationWeight_Values: [i32]
  ModifyMapsAchievements: [AchievementItems]
  IsEssenceOnlyModifier: bool
  Stat6Min: i32
  Stat6Max: i32
  StatsKey6: Stats
  MaxLevel: i32
  _: bool
  CraftingItemClassRestrictions: [ItemClasses]
  MonsterOnDeath: string
  _: i32
  _: [GrantedEffectsPerLevel]
  Heist_SubStatValue1: i32
  Heist_SubStatValue2: i32
  Heist_StatsKey0: Stats
  Heist_StatsKey1: Stats
  Heist_AddStatValue1: i32
  Heist_AddStatValue2: i32
  InfluenceTypes: InfluenceTypes
  ImplicitTagsKeys: [Tags]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  BuffTemplate: BuffTemplates
  ArchnemesisMinionMod: Mods
  HASH32: i32
  _: [rid]
  _: i32
  _: [GrantedEffectsPerLevel]
}

type ModSellPriceTypes {
  Id: string @unique
}

enum ModSetNames @indexing(first: 0) { _ }

type ModType {
  Name: string @unique
  ModSellPriceTypesKeys: [ModSellPriceTypes]
  _: bool
}

type MonsterArmours {
  Id: string
  ArtString_SMFile: string @file(ext: ".sm")
}

enum MonsterBehavior @indexing(first: 0) { _ }

type MonsterBonuses {
  Id: string @unique
  _: [rid]
  _: rid
  _: [i32]
  StatsKeys: [Stats]
  StatValues: [i32]
}

type MonsterConditionalEffectPacks {
  Id: string @unique
  MiscEffectPack1: [MiscEffectPacks]
  MiscEffectPack2: [MiscEffectPacks]
  MiscEffectPack3: [MiscEffectPacks]
  MiscEffectPack4: [MiscEffectPacks]
  _: i32
}

type MonsterConditions {
  Id: string
  _: rid
  _: rid
  _: rid
  _: [rid]
  _: bool
  _: bool
  _: [rid]
  _: [_]
  _: i32
  _: i32
  _: i32
  _: i32
}

type MonsterDeathAchievements {
  Id: string @unique
  MonsterVarietiesKeys: [MonsterVarieties]
  AchievementItemsKeys: [AchievementItems]
  _: bool
  PlayerConditionsKeys: [PlayerConditions]
  MonsterDeathConditionsKeys: [MonsterDeathConditions]
  _: [rid]
  _: i32
  _: i32
  _: bool
  _: bool
  _: rid
  _: [rid]
  _: [rid]
  _: [rid]
  _: rid
  _: i32
  NearbyMonsterConditionsKeys: [NearbyMonsterConditions]
  _: bool
  MultiPartAchievementConditionsKeys: [MultiPartAchievementConditions]
  _: i32
  _: bool
}

type MonsterDeathConditions {
  _: string
  _: [rid]
  _: bool
  _: i32
  _: [rid]
  _: bool
  _: i32
  _: rid
  _: bool
  _: [rid]
  _: i32
  _: bool
  _: [rid]
  _: i32
  _: rid
  _: rid
  _: i32
  _: i32
}

enum MonsterFleeConditions @indexing(first: 0) { _ }

type MonsterGroupEntries {
  Id: string @unique
  MonsterVarietiesKey: MonsterVarieties
  MonsterGroupNamesId: i32
}

enum MonsterGroupNames @indexing(first: 0) { _ }

type MonsterHeightBrackets {
  Id: string
  _: i32
  BuffVisuals1: BuffVisuals
  BuffVisuals2: BuffVisuals
  _: i32
  _: f32
  _: f32
  Tag: Tags
  _: i32
  _: f32
}

type MonsterHeights {
  MonsterVariety: MonsterVarieties
  _: f32
  MonsterHeightBracket: MonsterHeightBrackets
  _: i32
  _: i32
}

type MonsterMapBossDifficulty {
  MapLevel: i32
  Stat1Value: i32
  Stat2Value: i32
  StatsKey1: Stats
  StatsKey2: Stats
  StatsKey3: Stats
  Stat3Value: i32
  StatsKey4: Stats
  Stat4Value: i32
  StatsKey5: Stats
  Stat5Value: i32
}

type MonsterMapDifficulty {
  MapLevel: i32
  Stat1Value: i32
  Stat2Value: i32
  StatsKey1: Stats
  StatsKey2: Stats
  StatsKey3: Stats
  Stat3Value: i32
  StatsKey4: Stats
  Stat4Value: i32
}

type MonsterMortar {
  Id: i32
  _: rid
  _: rid
  _: rid
  _: i32
  _: bool
  _: bool
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: bool
  _: rid
  _: i32
  _: f32
  _: f32
  _: f32
  _: bool
  _: rid
  _: string
}

type MonsterPackCounts {
  _: rid
  _: i32
  _: [rid]
  _: bool
  _: [i32]
}

type MonsterPackEntries {
  Id: string @unique
  MonsterPacksKey: MonsterPacks
  _: bool
  _: i32
  MonsterVarietiesKey: MonsterVarieties
}

type MonsterPacks {
  Id: string @unique
  WorldAreasKeys: [WorldAreas]
  _: i32
  _: i32
  BossMonsterSpawnChance: i32
  BossMonsterCount: i32
  BossMonster_MonsterVarietiesKeys: [MonsterVarieties]
  _: bool
  _: i32
  _: [string]
  TagsKeys: [Tags]
  MinLevel: i32
  MaxLevel: i32
  WorldAreas2: [Tags]
  _: i32
  PackFormation: PackFormation
  _: i32
  _: bool
}

type MonsterProjectileAttack {
  Id: i32 @unique
  Projectile: Projectiles
  _: bool
  _: bool
  _: bool
  _: i32
}

type MonsterProjectileSpell {
  Id: i32 @unique
  Projectile: Projectiles
  Animation: Animation
  _: bool
  _: bool
  _: i32
  _: bool
}

type MonsterResistances {
  Id: string @unique
  FireNormal: i32
  ColdNormal: i32
  LightningNormal: i32
  ChaosNormal: i32
  FireCruel: i32
  ColdCruel: i32
  LightningCruel: i32
  ChaosCruel: i32
  FireMerciless: i32
  ColdMerciless: i32
  LightningMerciless: i32
  ChaosMerciless: i32
}

enum MonsterScalingByLevel @indexing(first: 0) { _ }

type MonsterSegments {
  Id: string
  Shapes: string
}

enum MonsterSize @indexing(first: 0) { _ }

enum MonsterSkillsAliveDead @indexing(first: 0) { _ }

enum MonsterSkillsAttackSpell @indexing(first: 0) { _ }

enum MonsterSkillsClientInstance @indexing(first: 0) { _ }

enum MonsterSkillsHull @indexing(first: 0) { _ }

enum MonsterSkillsOrientation @indexing(first: 0) { _ }

enum MonsterSkillsPlacement @indexing(first: 0) { _ }

enum MonsterSkillsReference @indexing(first: 0) { _ }

enum MonsterSkillsSequenceMode @indexing(first: 0) { _ }

enum MonsterSkillsShape @indexing(first: 0) { _ }

enum MonsterSkillsTargets @indexing(first: 0) { _ }

enum MonsterSkillsWaveDirection @indexing(first: 0) { _ }

type MonsterSpawnerGroups {
  Id: string @files(ext: [".ot", ".otc"])
}

type MonsterSpawnerGroupsPerLevel {
  MonsterSpawnerGroupsKey: MonsterSpawnerGroups
  MinLevel: i32
  _: i32
  _: i32
  _: i32
}

type MonsterSpawnerOverrides {
  _: rid
  Base_MonsterVarietiesKey: MonsterVarieties
  Override_MonsterVarietiesKey: MonsterVarieties
}

type MonsterTypes {
  Id: string @unique
  _: i32
  IsSummoned: bool
  Armour: i32
  Evasion: i32
  EnergyShieldFromLife: i32
  DamageSpread: i32
  MonsterResistancesKey: MonsterResistances
  IsLargeAbyssMonster: bool
  IsSmallAbyssMonster: bool
  _: bool
}

type MonsterVarieties {
  Id: string @unique
  MonsterTypesKey: MonsterTypes
  _: i32
  ObjectSize: i32
  MinimumAttackDistance: i32
  MaximumAttackDistance: i32
  ACTFiles: [string] @file(ext: ".act")
  AOFiles: [string] @file(ext: ".ao")
  BaseMonsterTypeIndex: string @files(ext: [".ot", ".otc"])
  ModsKeys: [Mods]
  _: i32
  _: string
  _: string
  "in percent"
  ModelSizeMultiplier: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  TagsKeys: [Tags]
  "in percent"
  ExperienceMultiplier: i32
  _: [i32]
  _: i32
  _: i32
  _: i32
  CriticalStrikeChance: i32
  _: i32
  GrantedEffectsKeys: [GrantedEffects]
  AISFile: string @file(ext: ".ais")
  ModsKeys2: [Mods]
  Stance: string
  _: rid
  Name: string
  "in percent"
  DamageMultiplier: i32
  "in percent"
  LifeMultiplier: i32
  "in ms"
  AttackSpeed: i32
  Weapon1_ItemVisualIdentityKeys: [ItemVisualIdentity]
  Weapon2_ItemVisualIdentityKeys: [ItemVisualIdentity]
  Back_ItemVisualIdentityKey: ItemVisualIdentity
  MainHand_ItemClassesKey: ItemClasses
  OffHand_ItemClassesKey: ItemClasses
  Helmet_ItemVisualIdentityKey: ItemVisualIdentity
  _: i32
  KillSpecificMonsterCount_AchievementItemsKeys: [AchievementItems]
  Special_ModsKeys: [Mods]
  KillRare_AchievementItemsKeys: [AchievementItems]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: string
  KillWhileOnslaughtIsActive_AchievementItemsKey: AchievementItems
  MonsterSegmentsKey: MonsterSegments
  MonsterArmoursKey: MonsterArmours
  KillWhileTalismanIsActive_AchievementItemsKey: AchievementItems
  Part1_ModsKeys: [Mods]
  Part2_ModsKeys: [Mods]
  Endgame_ModsKeys: [Mods]
  _: rid
  _: i32
  _: i32
  _: [rid]
  _: [rid]
  _: i32
  SinkAnimation_AOFile: string @file(ext: ".ao")
  _: bool
  _: [rid]
  _: bool
  _: bool
  _: bool
  _: i32
  _: i32
  _: f32
  _: i32
  EPKFile: string
  _: i32
  MonsterConditionalEffectPacksKey: MonsterConditionalEffectPacks
  _: bool
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: [_]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
}

type MonsterVarietiesArtVariations {
  Id: string
  _: i32
  _: [_]
}

type MouseCursorSizeSettings {
  Size: string
  Description: string
  Ratio: f32
}

type MoveDaemon {
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: string
  _: i32
  _: bool
  _: bool
  _: i32
}

type MTXSetBonus {
  Id: string @unique
  _: rid
  _: [rid]
  _: [rid]
  _: [rid]
  _: [rid]
}

type MultiPartAchievementAreas {
  _: rid
  _: [rid]
  _: i32
}

type MultiPartAchievementConditions {
  Id: string @unique
  MultiPartAchievementsKey1: MultiPartAchievements
  MultiPartAchievementsKey2: MultiPartAchievements
  _: i32
  _: i32
}

type MultiPartAchievements {
  Id: string @unique
  _: i32
  AchievementItemsKey: AchievementItems
  _: i32
  _: bool
  _: bool
  _: i32
}

type Music {
  Id: string @unique
  SoundFile: string @file(ext: ".ogg")
  BankFile: string @file(ext: ".bank")
  HASH16: i32
  IsAvailableInHideout: bool
  Name: string
  _: string
  MusicCategories: [MusicCategories]
  _: bool
  _: i32
}

type MusicCategories {
  Id: string @unique
  Name: string
  Order: i32
  _: bool
}

type MysteryBoxes {
  BaseItemTypesKey: BaseItemTypes
  BK2File: string @file(ext: ".bk2")
  BoxId: string
  BundleId: string
}

type NearbyMonsterConditions {
  Id: string @unique
  MonsterVarietiesKeys: [MonsterVarieties]
  MonsterAmount: i32
  _: i32
  IsNegated: bool
  _: i32
  _: [i32]
  IsLessThen: bool
  MinimumHealthPercentage: i32
}

type NetTiers {
  BaseItemTypesKey: BaseItemTypes
  Tier: i32
}

type Notifications {
  Id: string @unique
  _: bool
  _: bool
  Message: string
  _: string
  _: i32
  _: bool
  _: bool
  _: i32
}

type NPCAudio {
  Id: string @unique
  _: [i32]
  _: [i32]
  VolumePercentage: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: i32
  _: i32
}

type NPCConversations {
  Id: string
  DialogueEvent: DialogueEvent
  NPCTextAudioKeys: [NPCTextAudio]
  _: [i32]
  _: i32
}

type NPCDialogueStyles {
  Id: string @unique
  HeaderBaseFile: string
  ButtomFile: string
  BannerFiles: [string]
  HeaderFiles: [string]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: [i32]
  _: NPCDialogueStyles
  _: string
  _: [i32]
  _: [i32]
  _: i32
  _: i32
  _: f32
  _: string
  _: string
  _: i32
  _: i32
}

type NPCFollowerVariations {
  MonsterVarietiesKey: MonsterVarieties
  MiscAnimatedKey0: MiscAnimated
  MiscAnimatedKey1: MiscAnimated
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: [_]
  _: [_]
  _: i32
  _: bool
  _: bool
  _: i32
}

type NPCMaster {
  Id: string
  _: bool
  _: bool
  Signature_ModsKey: Mods
  _: bool
  SpawnWeight_TagsKeys: [Tags]
  SpawnWeight_Values: [i32]
  _: [i32]
  _: [i32]
  _: rid
  _: i32
  AreaDescription: string
  _: rid
  _: i32
  _: Stats
  HasAreaMissions: bool
  _: [rid]
  _: [rid]
  _: rid
}

type NPCPortraits {
  Name: string @unique
  PortraitFile: string
  _: i32
  _: i32
}

type NPCs {
  Id: string @unique
  Name: string
  Metadata: string @files(ext: [".ot", ".otc"])
  _: rid
  NPCMasterKey: NPCMaster
  ShortName: string
  _: i32
  NPCAudios1: [NPCAudio]
  NPCAudios2: [NPCAudio]
  _: i32
  _: NPCs
  Portrait: NPCPortraits
  DialogueStyle: NPCDialogueStyles
  _: bool
  _: rid
  Gender: string
}

type NPCShop {
  Id: string @unique
  _: i32
  SoldItem_TagsKeys: [Tags]
  SoldItem_Weights: [i32]
  _: [rid]
  _: [i32]
  _: [rid]
  _: [i32]
  _: i32
  _: i32
  _: i32
  _: [_]
  _: i32
  _: i32
}

type NPCShops {
  Id: string
  _: i32
  Shop: NPCShop
  ShopHardmode: NPCShop
}

type NPCTalk {
  NPCKey: NPCs
  _: i32
  DialogueOption: string
  _: [i32]
  _: [i32]
  _: [i32]
  Script: string
  TextAudio: NPCTextAudio
  Category: NPCTalkCategory
  QuestRewardOffersKey: QuestRewardOffers
  QuestFlag: QuestFlags
  NPCTextAudioKeys: [NPCTextAudio]
  Script2: string
  _: bool
  _: bool
  _: [i32]
  _: [i32]
  _: i32
  _: [i32]
  _: i32
  _: bool
  _: rid
  _: bool
  _: bool
  DialogueOption2: string
  _: rid
  _: rid
  _: i32
  _: [i32]
  _: i32
}

type NPCTalkCategory {
  Id: string
  _: bool
}

type NPCTalkConsoleQuickActions {
  Id: string
  Controller: string
  _: string
}

type NPCTextAudio {
  Id: string @unique
  CharactersKey: Characters
  Text: string
  Mono_AudioFile: string @file(ext: ".ogg")
  Stereo_AudioFile: string @file(ext: ".ogg")
  HasStereo: bool
  _: bool
  Video: string
  _: i32
  _: i32
  _: i32
  _: [rid]
  _: rid
}

enum NPCTextAudioInterruptRules @indexing(first: 0) { _ }

enum OldMapStashTabLayout @indexing(first: 0) { _ }

type OnKillAchievements {
  MonsterVarietiesKey: MonsterVarieties
  GameStat: GameStats
}

enum Orientations @indexing(first: 0) { _ }

type PackFormation {
  Id: string
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type PassiveJewelRadii {
  ID: string
  RingOuterRadius: i32
  RingInnerRadius: i32
  Radius: i32
}

type PassiveJewelSlots {
  Slot: PassiveSkills
  ClusterJewelSize: PassiveTreeExpansionJewelSizes
  _: i32
  ReplacesSlot: PassiveJewelSlots
  ProxySlot: PassiveSkills
  StartIndices: [i32]
}

type PassiveSkillFilterCatagories {
  Id: string @unique
  Name: string
}

type PassiveSkillFilterOptions {
  Id: string @unique
  _: rid
  Name: string
  _: string
}

type PassiveSkillMasteryGroups {
  Id: string
  MasteryEffects: [PassiveSkillMasteryEffects]
  InactiveIcon: string @file(ext: ".dds")
  ActiveIcon: string @file(ext: ".dds")
  ActiveEffectImage: string
  _: bool
  SoundEffect: SoundEffects
  MasteryCountStat: Stats
}

type PassiveSkillMasteryEffects {
  Id: string
  HASH16: i32
  Stats: [Stats]
  Stat1Value: i32
  Stat2Value: i32
  Stat3Value: i32
  AchievementItem: AchievementItems
}

type PassiveSkills {
  Id: string @unique
  Icon_DDSFile: string @file(ext: ".dds")
  Stats: [Stats]
  Stat1Value: i32
  Stat2Value: i32
  Stat3Value: i32
  Stat4Value: i32
  "Id used by PassiveSkillGraph.psg"
  PassiveSkillGraphId: i32 @unique
  Name: string
  Characters: [Characters]
  IsKeystone: bool
  IsNotable: bool
  FlavourText: string
  IsJustIcon: bool
  AchievementItem: AchievementItems
  IsJewelSocket: bool
  AscendancyKey: Ascendancy
  IsAscendancyStartingNode: bool
  ReminderStrings: [ClientStrings]
  SkillPointsGranted: i32
  IsMultipleChoice: bool
  IsMultipleChoiceOption: bool
  Stat5Value: i32
  PassiveSkillBuffs: [BuffTemplates]
  GrantedEffectsPerLevel: GrantedEffectsPerLevel
  IsAnointmentOnly: bool
  _: i32
  IsExpansion: bool
  IsProxyPassive: bool
  SkillType: PassiveSkillTypes
  MasteryGroup: PassiveSkillMasteryGroups
  _: rid
  SoundEffect: SoundEffects
  _: string
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: [rid]
  _: i32
  _: [rid]
  _: bool
}

enum PassiveSkillTypes @indexing(first: 0) {
  PASSIVE_TREE
  ATLAS_TREE
}

type PassiveSkillStatCategories {
  Id: string @unique
  Name: string
}

type PassiveSkillTrees {
  Id: string
  PassiveSkillGraph: string
  _: i32
  _: f32
  _: f32
  _: f32
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: ClientStrings
  UIArt: PassiveSkillTreeUIArt
}

type PassiveSkillTreeTutorial {
  Id: string
  CharactersKey: Characters
  _: rid
  ChoiceA_Description: string
  ChoiceB_Description: string
  _: rid
  ChoiceA_PassiveTreeURL: string
  ChoiceB_PassiveTreeURL: string
  _: rid
  _: rid
}

type PassiveSkillTreeUIArt {
  Id: string
  GroupBackgroundSmall: string
  GroupBackgroundMedium: string
  GroupBackgroundLarge: string
  _: bool
  PassiveFrameNormal: string
  NotableFrameNormal: string
  KeystoneFrameNormal: string
  PassiveFrameActive: string
  NotableFrameActive: string
  KeystoneFrameActive: string
  PassiveFrameCanAllocate: string
  NotableFrameCanAllocate: string
  KeystoneCanAllocate: string
  Ornament: string
  GroupBackgroundSmallBlank: string
  GroupBackgroundMediumBlank: string
  GroupBackgroundLargeBlank: string
}

type PassiveTreeExpansionJewels {
  BaseItemTypesKey: BaseItemTypes
  PassiveTreeExpansionJewelSizesKey: PassiveTreeExpansionJewelSizes
  MinNodes: i32
  MaxNodes: i32
  SmallIndices: [i32]
  NotableIndices: [i32]
  SocketIndices: [i32]
  TotalIndices: i32
}

type PassiveTreeExpansionJewelSizes {
  Name: string @unique
}

type PassiveTreeExpansionSkills {
  PassiveSkillsKey: PassiveSkills
  Mastery_PassiveSkillsKey: PassiveSkills
  TagsKey: Tags
  PassiveTreeExpansionJewelSizesKey: PassiveTreeExpansionJewelSizes
}

type PassiveTreeExpansionSpecialSkills {
  PassiveSkillsKey: PassiveSkills
  StatsKey: Stats
}

type PCBangRewardMicros {
  _: rid
  _: i32
}

enum PerLevelValues @indexing(first: 0) { _ }

type Pet {
  Id: string @unique @files(ext: [".ot", ".otc"])
  BaseItemTypesKey: BaseItemTypes
  HASH16: i32
  HASH32: i32
  _: i32
  _: bool
  _: bool
  _: [_]
  _: rid
}

type PlayerConditions {
  Id: string @unique
  BuffDefinitionsKeys: [BuffDefinitions]
  _: bool
  BuffStacks: i32
  CharactersKey: Characters
  StatsKeys: [Stats]
  _: bool
  StatValue: i32
  _: [rid]
  _: bool
}

type PlayerTradeWhisperFormats {
  Id: string
  Whisper: string
  InStash: bool
  IsPriced: bool
}

type PreloadGroups {
  Id: string @unique
}

enum PreloadPriorities @indexing(first: 0) { _ }

type Projectiles {
  Id: string @unique @files(ext: [".ot", ".otc"])
  AOFiles: [string] @file(ext: ".ao")
  LoopAnimationIds: [string]
  ImpactAnimationIds: [string]
  ProjectileSpeed: i32
  _: bool
  _: i32
  _: bool
  _: bool
  InheritsFrom: string @files(ext: [".ot", ".otc"])
  _: i32
  _: rid
  _: i32
  _: bool
  _: bool
  Stuck_AOFile: [string] @file(ext: ".ao")
  Bounce_AOFile: string @file(ext: ".ao")
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: [string]
  _: bool
  _: [i32]
}

type ProjectilesArtVariations {
  Projectile: string
  Variant: i32
  _: [_]
  _: i32
  _: rid
}

type ProjectileVariations {
  Id: string @unique
  ProjectileKey: Projectiles
}

type PVPTypes {
  Id: string
  _: rid
}

type Quest {
  Id: string @unique
  Act: i32
  Name: string @localized
  Icon_DDSFile: string @file(ext: ".dds")
  QuestId: i32
  _: bool
  Type: QuestType
  _: [i32]
  _: i32
  TrackerGroup: QuestTrackerGroup
}

type QuestAchievements {
  Id: string @unique
  QuestStates: [i32]
  _: [i32]
  AchievementItems: [AchievementItems]
  NPCs: [NPCs]
  _: bool
}

type QuestFlags {
  Id: string
  HASH32: i32
}

type QuestItems {
  Item: BaseItemTypes
  _: rid
  _: rid
  _: i32
  _: rid
  _: [_]
  _: bool
  _: bool
  _: rid
  _: i32
  _: rid
  Script: string
  _: rid
}

type QuestRewardOffers {
  Id: string
  QuestKey: Quest
  _: rid
  _: i32
  RewardWindowTake: ClientStrings
  _: bool
  _: bool
  RewardWindowTitle: ClientStrings
}

type QuestRewards {
  RewardOffer: QuestRewardOffers
  _: i32
  Characters: [Characters]
  Reward: BaseItemTypes
  RewardLevel: i32
  _: rid
  _: i32
  _: string
  _: [_]
  RewardStack: i32
  _: bool
  _: bool
  _: [_]
  _: i32
  _: i32
  _: [_]
  _: i32
  _: rid
  _: i32
}

enum QuestRewardType @indexing(first: 0) { _ }

enum QuestStateCalculation @indexing(first: 0) { _ }

type QuestStates {
  QuestKey: Quest
  _: i32
  QuestStates: [i32]
  _: [i32]
  Text: string
  _: bool
  Message: string
  MapPinsKeys1: [MapPins]
  _: i32
  MapPinsTexts: [string]
  MapPinsKeys2: [MapPins]
  _: [rid]
  _: bool
  _: [i32]
  _: [i32]
  _: i32
  SoundEffect: SoundEffects
}

type QuestStaticRewards {
  QuestFlag: QuestFlags
  _: i32
  StatsKeys: [Stats]
  StatValues: [i32]
  QuestKey: Quest
  _: i32
  ClientStringsKey: ClientStrings
  _: i32
  StatValuesHardmode: [i32]
  ClientStringHardmode: ClientStrings
  _: i32
}

type QuestTrackerGroup {
  Id: string @unique
  Name: string @localized
  QuestType: QuestType
}

type QuestType {
  Id: string @unique
  _: [i32]
}

type Races {
  Id: string
  Mods: [Mods]
  _: string
  _: string
  _: i32
  _: i32
  _: [rid]
  _: bool
  _: i32
}

type RaceTimes {
  RacesKey: Races
  Index: i32
  StartUNIXTime: i32
  EndUNIXTime: i32
}

type RareMonsterLifeScalingPerLevel {
  Level: i32
  Life: i32
}

type Rarity {
  Id: string
  MinMods: i32
  MaxMods: i32
  _: i32
  MaxPrefix: i32
  _: i32
  MaxSuffix: i32
  Color: string
}

type Realms {
  Id: string @unique
  Name: string
  Server: [string]
  IsEnabled: bool
  Server2: [string]
  ShortName: string
  _: [Realms]
  _: Realms
  _: i32
  IsGammaRealm: bool
  SpeedtestUrl: [string]
}

type RecipeUnlockDisplay {
  RecipeId: i32 @unique
  Description: string
  CraftingItemClassCategoriesKeys: [CraftingItemClassCategories]
  UnlockDescription: string
  Rank: i32
  UnlockArea: WorldAreas
}

type RecipeUnlockObjects {
  WorldAreasKey: WorldAreas
  InheritsFrom: string @files(ext: [".ot", ".otc"])
  RecipeId: i32
}

type ReminderText {
  Id: string
  Text: string @localized
  TextHardmode: string @localized
}

enum RelativeImportanceConstants @indexing(first: 0) { _ }

type Rulesets {
  Id: string @unique
  _: [_]
}

type RunicCircles {
  _: string
  _: i32
  _: [i32]
  _: i32
}

type SalvageBoxes {
  BaseItemType: BaseItemTypes
  Id: string @unique
  _: string
}

type SessionQuestFlags {
  QuestFlag: QuestFlags
}

type ShieldTypes {
  BaseItemTypesKey: BaseItemTypes @unique
  Block: i32
}

type ShopCategory {
  Id: string @unique
  ClientText: string
  ClientJPGFile: string @file(ext: ".jpg")
  WebsiteText: string
  WebsiteJPGFile: string
  _: i32
  AppliedTo_BaseItemTypesKey: BaseItemTypes
}

type ShopCountry {
  CountryTwoLetterCode: string
  Country: string
  ShopCurrencyKey: ShopCurrency
}

type ShopCurrency {
  CurrencyCode: string
  CurrencySign: string
}

enum ShopForumBadge @indexing(first: 0) { _ }

enum ShopPackagePlatform @indexing(first: 1) {
  PC
  XBOX
  SONY
}

type ShopPaymentPackage {
  Id: string @unique
  Text: string
  Coins: i32
  AvailableFlag: bool
  _: i32
  _: i32
  _: bool
  ContainsBetaKey: bool
  _: [i32]
  _: rid
  BackgroundImage: string
  _: string
  _: bool
  Upgrade_ShopPaymentPackageKey: ShopPaymentPackage
  "Number of points the user gets back if they opt-out of physical items"
  PhysicalItemPoints: i32
  _: i32
  ShopPackagePlatform: [ShopPackagePlatform]
  _: string
}

type ShopPaymentPackagePrice {
  ShopPaymentPackageKey: ShopPaymentPackage
  ShopCountryKey: ShopCountry
  Price: i32
}

enum ShopPaymentPackageProxy @indexing(first: 0) { _ }

type ShopRegion {
  Id: string @unique
}

type ShopTag {
  Id: string
  Name: string @localized
  IsCategory: bool
  Category: ShopTag
  SkillGem: [BaseItemTypes]
}

type ShopToken {
  Id: string
  TypeId: string
  Description: string
}

type SigilDisplay {
  Id: string @unique
  Active_StatsKey: Stats
  Inactive_StatsKey: Stats
  DDSFile: string @file(ext: ".dds")
  Inactive_ArtFile: string
  Active_ArtFile: string
  Frame_ArtFile: string
}

type SingleGroundLaser {
  Id: i32
  _: rid
  _: rid
  _: i32
  _: string
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: rid
  _: rid
  _: i32
  _: bool
}

type SkillArtVariations {
  Id: string
  _: [rid]
  _: [i32]
  _: [i32]
  _: [i32]
  Variants: [string]
  _: [rid]
  _: [i32]
  _: [rid]
  _: rid
  _: [i32]
  _: [rid]
  _: [i32]
}

type SkillGemInfo {
  Id: string @unique
  Description: string
  VideoURL1: string
  SkillGemsKey: SkillGems
  VideoURL2: string
  CharactersKeys: [Characters]
}

type SkillGems {
  BaseItemTypesKey: BaseItemTypes @unique
  GrantedEffectsKey: GrantedEffects
  Str: i32
  Dex: i32
  Int: i32
  GemTagsKeys: [GemTags]
  VaalVariant_BaseItemTypesKey: BaseItemTypes
  IsVaalVariant: bool
  Description: string
  Consumed_ModsKey: Mods
  GrantedEffectsKey2: GrantedEffects
  MinionGlobalSkillLevelStat: Stats
  SupportSkillName: string
  IsSupport: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  AwakenedVariant: SkillGems
  RegularVariant: SkillGems
  GrantedEffectHardMode: GrantedEffects
  _: rid
  _: i32
  ItemExperienceType: ItemExperienceTypes
}

enum SkillMines @indexing(first: 0) { _ }

type SkillMineVariations {
  SkillMinesKey: i32
  _: i32
  MiscObject: MiscObjects
}

type SkillMorphDisplay {
  _: rid
  _: [rid]
  DDSFiles: [string] @file(ext: ".dds")
  _: i32
  _: [i32]
  _: i32
  _: [f32]
  _: bool
  _: bool
}

enum SkillMorphDisplayOverlayCondition @indexing(first: 0) { _ }

enum SkillMorphDisplayOverlayStyle @indexing(first: 0) { _ }

type SkillSurgeEffects {
  GrantedEffectsKey: GrantedEffects
  _: string
  _: bool
  _: bool
  _: bool
  MiscAnimated: MiscAnimated
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: bool
  _: bool
}

enum SkillTotems @indexing(first: 0) { _ }

type SkillTotemVariations {
  SkillTotemsKey: SkillTotems
  TotemSkinId: i32
  MonsterVarietiesKey: MonsterVarieties
}

type SkillTrapVariations {
  Id: i32
  Metadata: string
  MiscAnimated: MiscAnimated
}

type SocketNotches {
  Id: string
  Description: string
  RedSocketImage: string
  BlueSocketImage: string
  GreenSocketImage: string
}

type SoundEffects {
  Id: string @unique
  SoundFile: string @file(ext: ".ogg")
  SoundFile_2D: string @file(ext: ".ogg")
  _: bool
  _: string
}

type SpawnAdditionalChestsOrClusters {
  StatsKey: Stats
  ChestsKey: Chests
  ChestClustersKey: ChestClusters
}

type SpawnObject {
  _: i32
  _: [rid]
  _: [_]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: string
  _: i32
  _: bool
  _: i32
  _: i32
}

type SpecialRooms {
  Id: string @unique
  ARMFile: string @file(ext: ".arm")
}

type SpecialTiles {
  Id: string @unique
  TDTFile: string @file(ext: ".tdt")
}

type SpectreOverrides {
  Monster: MonsterVarieties
  Spectre: MonsterVarieties
  _: [rid]
}

type StartingPassiveSkills {
  Id: string @unique
  PassiveSkills: [PassiveSkills]
}

enum StashId @indexing(first: 0) { _ }

type StashTabAffinities {
  SpecializedStash: StashId
  Name: string @localized
  ShowInStashes: [StashId]
}

type StashType {
  Id: string @unique
  IntId: i32 @unique
  Id2: string
  Width: i32
  Height: i32
  _: i32
}

type StatDescriptionFunctions {
  Id: string @unique
  TranslationId: string @unique
}

enum StatInterpolationTypes @indexing(first: 1) {
  CONSTANT
  LINEAR
  EXPONENTIAL
}

type StatsAffectingGeneration {
  Stat: Stats
  StatValue: i32
}

type Stats {
  Id: string @unique
  _: bool
  IsLocal: bool
  IsWeaponLocal: bool
  Semantics: StatSemantics
  Text: string
  _: bool
  IsVirtual: bool
  MainHandAlias_StatsKey: Stats
  OffHandAlias_StatsKey: Stats
  _: bool
  HASH32: i32
  BelongsActiveSkillsKey: [ActiveSkills] @ref(column: "Id")
  Category: PassiveSkillStatCategories
  _: bool
  _: bool

  """
  If not, displayed in advanced mod description as " — Unscalable Value"
  """
  IsScalable: bool
  ContextFlags: [VirtualStatContextFlags]
  _: [rid]
}

enum StatSemantics @indexing(first: 1) {
  PERCENT
  OVERRIDE_VALUE
  VALUE
  FLAG
  OVERRIDE_PERCENT
  PERMYRIAD
  OVERRIDE_PERMYRIAD
}

type StrDexIntMissionExtraRequirement {
  Id: string @unique
  SpawnWeight: i32
  MinLevel: i32
  MaxLevel: i32
  "in milliseconds"
  TimeLimit: i32
  HasTimeBonusPerKill: bool
  HasTimeBonusPerObjectTagged: bool
  HasLimitedPortals: bool
  NPCTalkKey: NPCTalk
  "in milliseconds"
  TimeLimitBonusFromObjective: i32
  ObjectCount: i32
  _: [i32]
  _: bool
  _: [rid]
}

type StrDexIntMissions {
  Id: string @unique
  _: i32
  _: i32
  SpawnWeight: i32
  _: rid
  _: rid
  Extra_ModsKeys: [Mods]
  _: bool
  _: bool
  _: bool
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: rid
  _: rid
  _: bool
  _: rid
  _: bool
  _: rid
}

type SuicideExplosion {
  Id: i32
  _: rid
  _: rid
  _: bool
  _: bool
  _: bool
  _: bool
  _: i32
  _: bool
}

type SummonedSpecificBarrels {
  Id: string
  Chest: Chests
  _: rid
  _: rid
  _: rid
  _: string
}

type SummonedSpecificMonsters {
  Id: i32 @unique
  MonsterVarietiesKey: MonsterVarieties
  _: i32
  _: rid
  _: bool
  _: bool
  _: i32
  _: i32
  _: bool
  _: rid
  _: rid
  _: i32
  _: bool
  _: i32
  _: string
  _: bool
  _: bool
  _: i32
}

type SummonedSpecificMonstersOnDeath {
  Id: string @unique
  MonsterVarietiesKey: MonsterVarieties
  _: i32
  _: rid
  _: i32
  _: bool
}

type SupporterPackSets {
  Id: string @unique
  FormatTitle: string
  Background: string
  Time0: string
  Time1: string
  ShopPackagePlatform: [ShopPackagePlatform]
  _: string
}

enum SurgeCategory @indexing(first: 0) { _ }

type SurgeEffects {
  Id: string
  _: MiscAnimated
  _: [f32]
  _: [MiscAnimated]
  _: [string]
}

type SurgeTypes {
  Id: string @unique
  SurgeEffects: [SurgeEffects]
  IntId: i32
}

type TableCharge {
  _: i32
  _: f32
  _: f32
  _: bool
  _: rid
  _: bool
  _: [rid]
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: rid
  _: rid
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: i32
}

type TableMonsterSpawners {
  Metadata: string
  AreaLevel: i32
  SpawnsMonsters: [MonsterVarieties]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: bool
  _: bool
  Script1: string
  _: bool
  _: bool
  Script2: string
  _: [i32]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type Tags {
  Id: string @unique
  _: i32
  DisplayString: string
  Name: string
}

type TalkingPetAudioEvents {
  Event: string
  _: i32
  _: i32
  _: i32
  _: [i32]
  _: [i32]
  _: i32
}

type TalkingPetNPCAudio {
  _: TalkingPetAudioEvents
  _: TalkingPets
  _: [i32]
}

type TalkingPets {
  _: rid
  _: [rid]
}

type TencentAutoLootPetCurrencies {
  BaseItemTypesKey: BaseItemTypes
  _: bool
}

type TencentAutoLootPetCurrenciesExcludable {
  BaseItemTypesKey: BaseItemTypes
}

type TerrainPlugins {
  Id: string @unique
  _: i32 @unique
  _: bool
  _: bool
}

type Tips {
  Id: string @unique
  Text: string
  TextXBox: string
}

type Topologies {
  Id: string @unique
  DGRFile: string @file(ext: ".dgr")
  _: i32
  _: i32
  _: i32
}

type TradeMarketCategory {
  Id: string
  Name: string @localized
  StyleFlag: TradeMarketCategoryStyleFlag
  Group: TradeMarketCategoryGroups
  _: [i32]
  _: bool
  IsDisabled: bool
}

type TradeMarketCategoryGroups {
  Id: string
  Name: string @localized
}

type TradeMarketCategoryListAllClass {
  TradeCategory: TradeMarketCategory
  ItemClass: ItemClasses
}

type TradeMarketIndexItemAs {
  Item: rid
  IndexAs: rid
}

enum TradeMarketCategoryStyleFlag @indexing(first: 0) { _ }

type TreasureHunterMissions {
  Id: string @unique
  _: rid
  _: rid
  _: [rid]
  _: [rid]
  _: [rid]
  _: i32
  _: i32
  _: i32
  _: string
  _: string
  OTFile: string @file(ext: ".ot")
  _: bool
  _: i32
  _: i32
}

type TriggerBeam {
  _: i32
  _: [MiscBeams]
  _: [MiscBeams]
  _: [i32]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: [i32]
  _: bool
  _: i32
}

type TriggerSpawners {
  Id: string @unique
  _: [i32]
  _: i32
  _: [i32]
  _: bool
}

type Tutorial {
  Id: string @unique
  UIFile: string @file(ext: ".ui")
  ClientString: ClientStrings
  IsEnabled: bool
  _: i32
  _: [i32]
  _: rid
  _: i32
  _: [i32]
  _: bool
  _: bool
  _: i32
}

enum UITalkCategories @indexing(first: 0) { _ }

type UITalkText {
  Id: string @unique
  UITalkCategoriesKey: UITalkCategories
  OGGFile: string @file(ext: ".ogg")
  Text: string
  _: bool
  NPCTextAudio: NPCTextAudio
}

type UniqueChests {
  Id: string @unique
  WordsKey: Words
  FlavourTextKey: FlavourText
  MinLevel: i32
  ModsKeys: [Mods]
  SpawnWeight: i32
  _: [i32]
  AOFile: string @file(ext: ".ao")
  _: bool
  _: [i32]
  AppearanceChestsKey: Chests
  ChestsKey: Chests
  _: [rid]
}

type UniqueJewelLimits {
  JewelName: Words
  Limit: i32
}

type UniqueMapInfo {
  BaseItemTypesKey: BaseItemTypes
  Word: Words
  FlavourTextKey: FlavourText
  ItemVisualIdentityKey: ItemVisualIdentity
  _: bool
}

type UniqueMaps {
  ItemVisualIdentityKey: ItemVisualIdentity @unique
  WorldAreasKey: WorldAreas
  WordsKey: Words
  FlavourTextKey: FlavourText
  HasGuildCharacter: bool
  GuildCharacter: string
  Name: string
  IsDropDisabled: bool
}

enum UniqueSetNames @indexing(first: 0) { _ }

type UniqueStashLayout {
  WordsKey: Words
  ItemVisualIdentityKey: ItemVisualIdentity
  UniqueStashTypesKey: UniqueStashTypes
  _: i32
  _: i32
  OverrideWidth: i32
  OverrideHeight: i32
  ShowIfEmptyChallengeLeague: bool
  ShowIfEmptyStandard: bool
  RenamedVersion: UniqueStashLayout
  BaseVersion: UniqueStashLayout
  IsAlternateArt: bool
}

type UniqueStashTypes {
  Id: string
  Order: i32
  Width: i32
  Height: i32
  _: i32
  _: i32
  Name: string @localized
  StandardCount: i32
  Image: string
  ChallengeLeagueCount: i32
  IsDisabled: bool
}

type VirtualStatContextFlags {
  Id: string @unique
  _: i32
}

type VoteState {
  Id: string @unique
  Text: string
}

type VoteType {
  Id: string @unique
  Text: string
  AcceptText: string
  RejectText: string
  _: i32
}

enum WeaponArmourCommon @indexing(first: 0) { _ }

type WeaponClasses {
  ItemClass: ItemClasses
  _: i32
}

enum WeaponDamageScaling @indexing(first: 0) { _ }

type WeaponImpactSoundData {
  Id: string @unique
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

enum WeaponSoundTypes @indexing(first: 0) { _ }

type WeaponTypes {
  BaseItemTypesKey: BaseItemTypes @unique
  Critical: i32
  "1000 / speed -> attacks per second"
  Speed: i32
  DamageMin: i32
  DamageMax: i32
  RangeMax: i32
  _: i32
}

type WindowCursors {
  Id: string
  CursorDefault: string @file(ext: ".bmp")
  CursorClick: string @file(ext: ".bmp")
  _: i32
  _: i32
  CursorHover: string @file(ext: ".bmp")
  Description: string
  IsEnabled: bool
  _: i32
}

enum Wordlists @indexing(first: 1) {
  ITEM_PREFIX
  ITEM_SUFFIX
  MONSTER_PREFIX
  MONSTER_SUFFIX
  MONSTER_TITLE
  UNIQUE_ITEM
  STRONGBOX_PREFIX
  STRONGBOX_SUFFIX
  ESSENCE
}

type Words {
  Wordlist: Wordlists
  Text: string
  SpawnWeight_Tags: [Tags]
  SpawnWeight_Values: [i32]
  _: i32
  Text2: string
  "the inflection identifier used for i18n in related fields"
  Inflection: string
}

type WorldAreas {
  Id: string @unique
  Name: string
  Act: i32
  IsTown: bool
  HasWaypoint: bool
  Connections_WorldAreasKeys: [WorldAreas]
  AreaLevel: i32
  HASH16: i32
  _: i32
  _: i32
  LoadingScreen_DDSFile: string @file(ext: ".dds")
  _: rid
  _: [rid]
  _: i32
  TopologiesKeys: [Topologies]
  ParentTown_WorldAreasKey: WorldAreas
  _: i32
  _: rid
  _: rid
  Bosses_MonsterVarietiesKeys: [MonsterVarieties]
  Monsters_MonsterVarietiesKeys: [MonsterVarieties]
  SpawnWeight_TagsKeys: [Tags]
  SpawnWeight_Values: [i32]
  IsMapArea: bool
  FullClear_AchievementItemsKeys: [AchievementItems]
  _: rid
  AchievementItemsKey: AchievementItems
  ModsKeys: [Mods]
  _: i32
  VaalArea: [WorldAreas]
  _: bool
  MaxLevel: i32
  AreaTypeTags: [Tags]
  _: i32
  IsHideout: bool
  Inflection: string
  _: i32
  _: i32
  Tags: [Tags]
  IsVaalArea: bool
  IsLabyrinthAirlock: bool
  IsLabyrinthArea: bool
  TwinnedFullClear_AchievementItemsKey: AchievementItems
  Enter_AchievementItemsKey: AchievementItems
  TSIFile: string @file(ext: ".tsi")
  _: rid
  WaypointActivation_AchievementItemsKeys: [AchievementItems]
  IsUniqueMapArea: bool
  IsLabyrinthBossArea: bool
  FirstEntry_NPCTextAudioKey: NPCTextAudio
  FirstEntry_SoundEffectsKey: SoundEffects
  FirstEntry_NPCsKey: NPCs @ref(column: "Id")
  _: i32
  EnvironmentsKey: Environments
  _: i32
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: [_]
  _: rid
  _: i32
  _: rid
  _: rid
  _: Rulesets
}

type WorldAreaLeagueChances {
  Id: string
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: [i32]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}

type WorldPopupIconTypes {
  Id: string @unique
  _: string
  _: i32
  _: i32
  _: bool
  _: f32
  _: f32
  _: f32
  _: string
}

type ZanaLevels {
  _: i32
  _: i32
}
