# Added 3.17
type BattlePassRewards {
  BattlePass: BattlePasses
  RewardTier: i32
  _: i32
  _: i32
  _: bool
  Id: string
  RewardedMTX: [BaseItemTypes]
  _: i32
  RewardDescription: string
  _: string
  _: i32
  _: i32
  _: bool
  RewardTitle: string
  _: rid
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
}
