# Added 3.08
type BlightCraftingRecipes @tags(list: ["crafting"]) {
  Id: string @unique
  BlightCraftingItemsKeys: [BlightCraftingItems]
  BlightCraftingResultsKey: BlightCraftingResults
  BlightCraftingTypesKey: BlightCraftingTypes
}
