type BuffDefinitions {
  Id: string @unique
  Description: string
  Invisible: bool
  Removable: bool
  Name: string
  StatsKeys: [Stats]
  _: bool
  _: i32
  _: bool
  Maximum_StatsKey: Stats
  Current_StatsKey: Stats
  _: bool
  _: i32
  BuffVisualsKey: BuffVisuals
  _: bool
  _: bool
  BuffCategory: i32
  _: bool
  _: bool
  _: bool
  _: bool
  BuffLimit: i32
  _: bool
  Id2: string
  IsRecovery: bool
  _: bool
  _: rid
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: [i32]
  _: bool
  _: bool
  _: [rid]
  _: bool
  _: [Stats]
  BinaryStats: [Stats]
  _: [Stats]
  _: [Stats]
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: Stats
  _: [i32]
  _: string
  _: [Stats]
  _: bool
}
