type DamageParticleEffects {
  DamageParticleEffectTypes: DamageParticleEffectTypes
  Variation: i32
  PETFile: string @file(ext: ".pet")
  ImpactSoundData1: ImpactSoundData
  ImpactSoundData2: ImpactSoundData
  _: i32
}
