# Added 3.17
type DamageEffectVariations {
  Id: string @unique
  _: [_]
  _: [string]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: rid
}
