# Added 3.04
type DelveLevelScaling {
  Depth: i32
  MonsterLevel: i32
  _: i32
  SulphiteCost: i32
  MonsterLevel2: i32
  MoreMonsterDamage: i32
  MoreMonsterLife: i32
  DarknessResistance: i32
  LightRadius: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}
