# Added 3.04
type DelveCraftingModifiers @tags(list: ["crafting"]) {
  BaseItemTypesKey: BaseItemTypes
  AddedModsKeys: [Mods]
  NegativeWeight_TagsKeys: [Tags]
  NegativeWeight_Values: [i32]
  ForcedAddModsKeys: [Mods]
  ForbiddenDelveCraftingTagsKeys: [DelveCraftingTags]
  AllowedDelveCraftingTagsKeys: [DelveCraftingTags]
  CanMirrorItem: bool
  CorruptedEssenceChance: i32
  CanImproveQuality: bool
  HasLuckyRolls: bool
  SellPrice_ModsKeys: [Mods]
  CanRollWhiteSockets: bool
  Weight_TagsKeys: [Tags]
  Weight_Values: [i32]
  DelveCraftingModifierDescriptionsKeys: [DelveCraftingModifierDescriptions]
  BlockedDelveCraftingModifierDescriptionsKeys: [DelveCraftingModifierDescriptions]
  _: bool
  _: bool
  _: [i32]
  _: [i32]
  _: bool
}
