# Added 3.18
type DroneBaseTypes {
  BaseType: BaseItemTypes @unique
  Type: DroneTypes
  Charges: i32
  Duration: i32
  EnemyLimit: i32
  Visual: BuffVisuals
  Empowerment: i32
  UseAchievement: AchievementItems
  CreatedViaPowerCore: bool
}
