type GrantedEffectQualityStats @tags(list: ["item:droptable"]) {
  GrantedEffectsKey: GrantedEffects
  StatsKeys: [Stats]
  StatsValuesPermille: [i32]
  _: [_] # All rows empty
  _: [_] # All rows empty
}
