type HideoutDoodads {
  MtxTypeGameSpecific: MtxTypeGameSpecific @unique
  Variation_AOFiles: [string] @file(ext: ".ao")
  IsNonMasterDoodad: bool
  InheritsFrom: string @files(ext: [".ot", ".otc"])
  _: bool
  IsCraftingBench: bool
  Tags: [HideoutDoodadTags]
  _: bool
  _: rid
  Category: HideoutDoodadCategory
  _: i32
  _: bool
  _: rid
  _: bool
  _: rid
  _: [string]
  _: i32
  _: i32
  _: bool
  _: bool
}
