# Added 3.21
type HudLifeVisuals {
  Id: string @unique
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: i32
  _: string
}
