# Added 2.02
type LabyrinthSecretEffects {
  Id: string
  MonsterVarietiesKey: MonsterVarieties
  Buff_BuffDefinitionsKey: BuffDefinitions
  Buff_StatValues: [i32]
  OTFile: string @file(ext: ".ot")
  _: [_]
}
