type Mods @tags(list: ["crafting"]) {
  Id: string @unique
  HASH16: i16
  ModTypeKey: ModType
  Level: i32
  StatsKey1: Stats
  StatsKey2: Stats
  StatsKey3: Stats
  StatsKey4: Stats
  Domain: ModDomains
  Name: string
  GenerationType: ModGenerationType
  Families: [ModFamily]
  Stat1Min: i32
  Stat1Max: i32
  Stat2Min: i32
  Stat2Max: i32
  Stat3Min: i32
  Stat3Max: i32
  Stat4Min: i32
  Stat4Max: i32
  SpawnWeight_TagsKeys: [Tags]
  SpawnWeight_Values: [i32]
  TagsKeys: [Tags]
  GrantedEffectsPerLevelKeys: [GrantedEffectsPerLevel]
  _: [i32]
  MonsterMetadata: string
  MonsterKillAchievements: [AchievementItems]
  ChestModType: [ModType]
  Stat5Min: i32
  Stat5Max: i32
  StatsKey5: Stats
  FullAreaClear_AchievementItemsKey: [AchievementItems]
  AchievementItemsKey: [AchievementItems]
  GenerationWeight_TagsKeys: [Tags]
  GenerationWeight_Values: [i32]
  ModifyMapsAchievements: [AchievementItems]
  IsEssenceOnlyModifier: bool
  Stat6Min: i32
  Stat6Max: i32
  StatsKey6: Stats
  MaxLevel: i32
  _: bool
  CraftingItemClassRestrictions: [ItemClasses]
  MonsterOnDeath: string
  _: i32
  _: [GrantedEffectsPerLevel]
  Heist_SubStatValue1: i32
  Heist_SubStatValue2: i32
  Heist_StatsKey0: Stats
  Heist_StatsKey1: Stats
  Heist_AddStatValue1: i32
  Heist_AddStatValue2: i32
  InfluenceTypes: InfluenceTypes
  ImplicitTagsKeys: [Tags]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  BuffTemplate: BuffTemplates
  ArchnemesisMinionMod: Mods
  HASH32: i32
  _: [rid]
  "0: All, 1: Normal, 2: Ruthless"
  GameMode: i32
  _: [GrantedEffectsPerLevel]
}
