type MonsterTypes {
  Id: string @unique
  _: i32
  _: i32
  IsSummoned: bool
  Armour: i32
  Evasion: i32
  DamageSpread: i32
  MonsterResistancesKey: MonsterResistances
  IsLargeAbyssMonster: bool
  IsSmallAbyssMonster: bool
  _: bool
}
