type NPCTalk {
  NPCKey: NPCs
  _: i32
  DialogueOption: string
  _: [i32]
  _: [i32]
  _: [i32]
  Script: string
  TextAudio: NPCTextAudio
  Category: NPCTalkCategory
  QuestRewardOffersKey: QuestRewardOffers
  QuestFlag: QuestFlags
  NPCTextAudioKeys: [NPCTextAudio]
  Script2: string
  _: bool
  _: bool
  _: [i32]
  _: [i32]
  _: i32
  _: [i32]
  _: i32
  _: bool
  _: rid
  _: i32
  _: bool
  DialogueOption2: string
  _: rid
  _: rid
  _: string
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: i32
  _: rid
  _: bool
  _: i32
  _: NPCTalk
}
