type PassiveSkillTrees {
  Id: string
  _: i32
  _: f32
  _: f32
  _: f32
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  Name: ClientStrings
  UIArt: PassiveSkillTreeUIArt
  PassiveSkillGraph: string
}
