type PassiveSkillMasteryGroups {
  Id: string @unique
  MasteryEffects: [PassiveSkillMasteryEffects]
  InactiveIcon: string @file(ext: ".dds")
  ActiveIcon: string @file(ext: ".dds")
  ActiveEffectImage: string
  _: bool
  SoundEffect: SoundEffects
  MasteryCountStat: Stats
}
