type SummonedSpecificMonsters {
  Id: i32 @unique
  MonsterVarietiesKey: MonsterVarieties
  _: i32
  _: rid
  _: bool
  _: bool
  _: i32
  _: i32
  _: bool
  _: rid
  _: rid
  _: i32
  _: bool
  _: i32
  _: string
  _: bool
  _: bool
  _: i32
}
