type BlightCraftingItems @tags(list: ["item:def"]) {
  Oil: BaseItemTypes @unique
  Tier: i32
  Achievements: [AchievementItems]
  UseType: i32
  NameShort: string
  _ : rid
}


type ExpeditionCurrency {
  BaseItemType: BaseItemTypes
}

type Essences {
  BaseItemType: BaseItemTypes
  HASH32: i32
  _: i32
  _: i32
  _: [i32]
  _: i32
  MonsterMod: Mods
  _: bool
  CraftTag: Tags
}

type PantheonPanelLayout {
  Id: string @unique
  X: i32
  Y: i32
  IsMajorGod: bool
  CoverImage: string
  GodName2: string
  SelectionImage: string
  Effect1_StatsKeys: [Stats]
  Effect1_Values: [i32]
  Effect2_StatsKeys: [Stats]
  GodName3: string
  Effect3_Values: [i32]
  Effect3_StatsKeys: [Stats]
  GodName4: string
  Effect4_StatsKeys: [Stats]
  Effect4_Values: [i32]
  GodName1: string
  Effect2_Values: [i32]
  QuestFlag: QuestFlags
  AchievementItems: [AchievementItems]
  LeagueQuestFlag1: i32
  LeagueQuestFlag2: i32
  LeagueQuestFlag3: i32
  LeagueQuestFlag4: i32
  _: rid
  _: bool
  DowngradeFlags: [QuestFlags]
}

type DelveCraftingModifiers @tags(list: ["crafting"]) {
  BaseItemTypesKey: BaseItemTypes
  AddedModsKeys: [Mods]
  NegativeWeight_TagsKeys: [Tags]
  NegativeWeight_Values: [i32]
  ForcedAddModsKeys: [Mods]
  ForbiddenDelveCraftingTagsKeys: [DelveCraftingTags]
  AllowedDelveCraftingTagsKeys: [DelveCraftingTags]
  CanMirrorItem: bool
  CorruptedEssenceChance: i32
  CanImproveQuality: bool
  HasLuckyRolls: bool
  _: bool
  SellPrice_ModsKeys: [Mods]
  CanRollWhiteSockets: bool
  Weight_TagsKeys: [Tags]
  Weight_Values: [i32]
  DelveCraftingModifierDescriptionsKeys: [DelveCraftingModifierDescriptions]
  BlockedDelveCraftingModifierDescriptionsKeys: [DelveCraftingModifierDescriptions]
  _: bool
  _: bool
  _: [i32]
  _: [i32]
}

type AlternateQualityTypes @tags(list: ["item:def"]) {
  Id: string
  Description: string
  Item: BaseItemTypes
  _: rid
  HASH16: i16
}
