type ActiveSkills {
  Id: string @unique
  DisplayedName: string
  Description: string
  ActionType: ActionTypes
  Icon_DDSFile: string @file(ext: ".dds")
  ActiveSkillTargetTypes: [ActiveSkillTargetTypes]
  ActiveSkillTypes: [ActiveSkillType]
  WeaponRestriction_ItemClassesKeys: [ItemClasses]
  WebsiteDescription: string
  WebsiteImage: string
  _: bool
  _: string
  _: bool
  SkillTotemId: SkillTotems
  IsManuallyCasted: bool
  Input_StatKeys: [Stats]
  Output_StatKeys: [Stats]
  MinionActiveSkillTypes: [ActiveSkillType]
  _: bool
  _: bool
  _: [Stats]
  _: i32
  AlternateSkillTargetingBehavioursKey: AlternateSkillTargetingBehaviours
  _: bool
  AIFile: string @file(ext: ".ai")
  _: [rid]
  _: bool
  _: bool
  _: bool
  TransfigureBase: ActiveSkills
  VideoClip: string @file(ext: ".bk2")
  _: rid
  AiScript: string @file(ext: ".ais")
  _: rid
  _: rid
  _: bool
  _: string
  _: i32
  StatDescription: string
}

type Acts {
  Id: string @unique
  UI_Title: string
  ActNumber: i32
  _: string
  _: string
  _: i32
  IsEndGame: bool
  _: i32
  _: [rid]
  _: [rid]
  _: [rid]
  _: rid
  _: [rid]
  Description: string
}

type AegisVariations {
  Id: string @unique
  DefendsAgainstPhysical: bool
  DefendsAgainstFire: bool
  DefendsAgainstCold: bool
  DefendsAgainstLightning: bool
  DefendsAgainstChaos: bool
  _: rid
  _: rid
  _: rid
  _: bool
  _: [string]
}

type ArmourTypes @tags(list: ["item:def"]) {
  BaseItemTypesKey: BaseItemTypes @unique
  Armour: i32
  Evasion: i32
  EnergyShield: i32
  IncreasedMovementSpeed: i32
  Ward: i32
  _: i32
}

type AtlasPassiveSkillSubTrees {
  Id: string @unique
  UI_Image: string
  UI_Background: string
  IllustrationX: i32
  IllustrationY: i32
  CounterX: i32
  CounterY: i32
  _: rid
  _: rid
}

type BaseItemTypes @tags(list: ["item:def", "item:droptable"]) {
  Id: string @unique
  ItemClassesKey: ItemClasses
  Width: i32
  Height: i32
  Name: string @localized
  InheritsFrom: string @files(ext: [".ot", ".otc"])
  DropLevel: i32
  FlavourTextKey: FlavourText
  Implicit_ModsKeys: [Mods]
  SizeOnGround: i32
  SoundEffect: SoundEffects
  TagsKeys: [Tags]
  ModDomain: ModDomains
  SiteVisibility: i32
  ItemVisualIdentity: ItemVisualIdentity
  HASH32: i32 @unique
  VendorRecipe_AchievementItems: [AchievementItems]
  "the inflection identifier used for i18n in related fields"
  Inflection: string
  Equip_AchievementItemsKey: AchievementItems
  IsCorrupted: bool
  Identify_AchievementItems: [AchievementItems]
  IdentifyMagic_AchievementItems: [AchievementItems]
  "the item which represents this item in the fragment stash tab"
  FragmentBaseItemTypesKey: BaseItemTypes
  _: bool
  _: rid
  _: rid
  _: bool
  TradeMarketCategory: TradeMarketCategory
  Unmodifiable: bool
  Achievement: [AchievementItems]
  _: rid # spells have some values
  _: rid # all nulls
}

type Chanceableitemclasses {
  ItemClass: ItemClasses
  _: i32
}

type CharacterCreationButton {
  _: rid
  _: string
  _: string
  _: string
  _: string
}

type CharacterCreationDialogue {
  _: rid
  _: rid
  _: rid
  _: rid
}

type CurrencyItems @tags(list: ["item:def", "item:recipe"]) {
  BaseItemTypesKey: BaseItemTypes @unique
  StackSize: i32
  CurrencyUseType: i32
  Action: string
  Directions: string
  "Full stack transforms into this item"
  FullStack_BaseItemTypesKey: BaseItemTypes
  Description: string
  Usage_AchievementItemsKeys: [AchievementItems]
  Scroll: bool
  Possession_AchievementItemsKey: AchievementItems
  _: [rid]
  _: [i32]
  CurrencyTab_StackSize: i32
  XBoxDirections: string
  _: i32
  ModifyMapsAchievements: [AchievementItems]
  ModifyContractsAchievements: [AchievementItems]
  CombineAchievements: [AchievementItems]
  ChangedForHardmode: bool
  DescriptionHardmode: string
  IsGold: bool
  UsageHint: string
  _: bool
}

type EndgameCorruptionMods {
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
}

type GemEffects {
  Id: string @unique
  Name: string
  GrantedEffect: GrantedEffects
  SupportText: string
  SupportName: string
  GemTags: [GemTags]
  Consumed_ModsKey: Mods
  "Used by gem icon shader https://gist.github.com/zao/08878df57aba605e5fa1e6373f2dce02"
  ItemColor: i32
  _: [rid]
  AdditionalGrantedEffects: [GrantedEffects]
  _: bool
  _: bool
  _: [i32]
  _: i32
}

type GoldModPrices {
  Mod: Mods
  Value: i32
  _: i32
  _: i32
  _: i32
  Tags: [Tags]
  SpawnWeight: [i32]
  CraftableType: CraftableModTypes
  _: [rid]
}

type CraftableModTypes {
  ModType: ModType
  HASH16: u16
}

type GrantedEffectsPerLevel {
  GrantedEffect: GrantedEffects
  Level: i32
  CostMultiplier: i32
  StoredUses: i32
  Cooldown: i32
  CooldownBypassType: CooldownBypassTypes
  VaalSouls: i32
  VaalStoredUses: i32
  CooldownGroup: i32
  _: i32
  SoulGainPreventionDuration: i32
  AttackSpeedMultiplier: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  Reservation: i32
  _: i32
  CostAmounts: [i32]
  _: f32
  _: i32
}

type GrantedEffectStatSets {
  Id: string @unique
  Label: GrantedEffectLabels
  ImplicitStats: [Stats]
  ConstantStats: [Stats]
  ConstantStatsValues: [i32]
  BaseEffectiveness: f32
  IncrementalEffectiveness: f32
  _: f32
  _: [rid]
  _: bool
}

type GrantedEffectStatSetsPerLevel {
  StatSet: GrantedEffectStatSets
  GemLevel: i32
  SpellCritChance: i32
  AttackCritChance: i32
  BaseResolvedValues: [i32]
  AdditionalStatsValues: [i32]
  GrantedEffects: [GrantedEffects]
  _: bool
  _: i32
  AdditionalFlags: [Stats]
  FloatStats: [Stats]
  InterpolationBases: [Stats]
  AdditionalStats: [Stats]
  StatInterpolations: [StatInterpolationTypes]
  FloatStatsValues: [f32]
  _: f32
  BaseMultiplier: i32
}

type ItemClasses @tags(list: ["crafting"]) {
  Id: string @unique
  Name: string
  TradeMarketCategory: TradeMarketCategory
  ItemClassCategory: ItemClassCategories
  RemovedIfLeavesArea: bool
  _: [_] # All rows empty
  IdentifyAchievements: [AchievementItems]
  AllocateToMapOwner: bool
  AlwaysAllocate: bool
  CanHaveVeiledMods: bool
  PickedUpQuest: QuestFlags
  _: i32
  AlwaysShow: bool
  CanBeCorrupted: bool
  CanHaveIncubators: bool
  CanHaveInfluence: bool
  CanBeDoubleCorrupted: bool
  CanHaveAspects: bool
  CanTransferSkin: bool
  ItemStance: ItemStances
  CanScourge: bool
  CanUpgradeRarity: bool
  _: bool
  InventoryDimensions: [i32]
  ItemClassFlags: [i32]
  Unmodfiable: bool
  CanBeFractured: bool
  _: rid # Only charms have a value
  UsableInMapDevice: bool
}

type ItemInherentSkills {
  BaseItemTypes: BaseItemTypes
  SkillsGranted: [SkillGems]
  IsWeapon: bool
}

type ItemSpirit {
  BaseItemTypes: BaseItemTypes
  SpiritGranted: i32
}

type KeywordPopups {
  Id: string @unique
  Term: string
  Definition: string
  _: string
}

type Mods @tags(list: ["crafting"]) {
  Id: string @unique
  HASH16: u16
  ModTypeKey: ModType
  Level: i32
  StatsKey1: Stats
  StatsKey2: Stats
  StatsKey3: Stats
  StatsKey4: Stats
  Domain: ModDomains
  Name: string
  GenerationType: ModGenerationType
  Families: [ModFamily]
  Stat1Min: i32
  Stat1Max: i32
  Stat2Min: i32
  Stat2Max: i32
  Stat3Min: i32
  Stat3Max: i32
  Stat4Min: i32
  Stat4Max: i32
  SpawnWeight_TagsKeys: [Tags]
  SpawnWeight_Values: [i32]
  TagsKeys: [Tags]
  GrantedEffectsPerLevelKeys: [GrantedEffectsPerLevel]
  _: [i32]
  MonsterMetadata: string
  MonsterKillAchievements: [AchievementItems]
  ChestModType: [ModType]
  Stat5Min: i32
  Stat5Max: i32
  StatsKey5: Stats
  FullAreaClear_AchievementItemsKey: [AchievementItems]
  AchievementItemsKey: [AchievementItems]
  GenerationWeight_TagsKeys: [Tags]
  GenerationWeight_Values: [i32]
  ModifyMapsAchievements: [AchievementItems]
  IsEssenceOnlyModifier: bool
  Stat6Min: i32
  Stat6Max: i32
  StatsKey6: Stats
  MaxLevel: i32
  _: bool
  CraftingItemClassRestrictions: [ItemClasses]
  MonsterOnDeath: string
  _: i32
  _: [GrantedEffectsPerLevel]
  Heist_SubStatValue1: i32
  Heist_SubStatValue2: i32
  Heist_StatsKey0: Stats
  Heist_StatsKey1: Stats
  Heist_AddStatValue1: i32
  Heist_AddStatValue2: i32
  InfluenceTypes: InfluenceTypes
  ImplicitTagsKeys: [Tags]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  BuffTemplate: BuffTemplates
  ArchnemesisMinionMod: Mods
  HASH32: i32
  _: [rid]
  _: i32
  _: [GrantedEffectsPerLevel]
  RadiusJewelType: i32
}

type Passiveskills {
  Id: string @unique
  Icon_DDSFile: string @file(ext: ".dds")
  Stats: [Stats]
  Stat1Value: i32
  Stat2Value: i32
  Stat3Value: i32
  Stat4Value: i32
  "Id used by PassiveSkillGraph.psg"
  PassiveSkillGraphId: u16 @unique
  Name: string
  Characters: [Characters]
  IsKeystone: bool
  IsNotable: bool
  FlavourText: string
  IsJustIcon: bool
  AchievementItem: AchievementItems
  IsJewelSocket: bool
  AscendancyKey: Ascendancy
  IsAscendancyStartingNode: bool
  ReminderStrings: [ReminderText]
  SkillPointsGranted: i32
  IsMultipleChoice: bool
  IsMultipleChoiceOption: bool
  Stat5Value: i32
  PassiveSkillBuffs: [BuffTemplates]
  IsAnointmentOnly: bool
  _: i32
  IsExpansion: bool
  IsProxyPassive: bool
  SkillType: PassiveSkillTypes
  MasteryGroup: PassiveSkillMasteryGroups
  Group: AtlasPassiveSkillTreeGroupType
  SoundEffect: SoundEffects
  _: string
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: [rid]
  _: i32
  _: [rid]
  _: bool
  KeystoneId: rid
  _: bool
  IsAttribute: bool
  AtlasSubTree: AtlasPassiveSkillSubTrees
  IsRootOfAtlasTree: bool
  GrantedSkill: SkillGems
  WeaponPointsGranted: i32
}

type SkillGems @tags(list: ["item:def"]) {
  BaseItemTypesKey: BaseItemTypes @unique
  StrengthRequirementPercent: i32
  DexterityRequirementPercent: i32
  IntelligenceRequirementPercent: i32
  VaalVariant_BaseItemTypesKey: BaseItemTypes
  IsVaalVariant: bool
  MinionGlobalSkillLevelStat: Stats
  GemType: GemTypes
  _: bool
  _: bool
  _: rid
  _: i32
  _: i32
  ItemExperienceType: ItemExperienceTypes
  CraftingTypes: [SkillCraftingData]
  _: [rid]
  _: bool
  GemEffects: [GemEffects]
  _: bool
  TutorialVideo: string @file(ext: ".bk2")
  UI_Image: string @file(ext: ".dds")
  _: i32
  CraftingLevel: i32
  _: bool
  _: i32
  _: bool
  _: string
}

type SkillGemSupports {
  SkillGemsKey: SkillGems
  Supports: [SkillGems]
}

type SupportGems {
  SkillGemsKey: SkillGems
  _: i32
  Icon: string @file(ext: ".dds")
}

type Tags {
  Id: string @unique
  HASH32: i32
  DisplayString: string
  _: [rid]
  UiHints: string
}

type UncutGemAdditionalTiers {
  BaseItemType: BaseItemTypes
  AreaLevel: i32
  Tier: i32
  Odds: i32
}

type UncutGemTiers {
  BaseItemType: BaseItemTypes
  Tier: i32
  AreaLevel: i32
}

type ClassPassiveSkillOverrides {
  CharacterToOverrideFor: Characters
  SkillToOverride: PassiveSkills
  Override: PassiveSkills
}

type Characters {
  Id: string @unique
  Name: string @unique @localized
  AOFile: string @file(ext: ".ao")
  ACTFile: string @file(ext: ".act")
  BaseMaxLife: i32
  BaseMaxMana: i32
  "Attack Speed in milliseconds"
  WeaponSpeed: i32
  MinDamage: i32
  MaxDamage: i32
  MaxAttackDistance: i32
  Icon: string
  IntegerId: i32 @unique
  BaseStrength: i32
  BaseDexterity: i32
  BaseIntelligence: i32
  _: [rid]
  Description: string @localized
  StartSkillGem: SkillGems
  _: rid
  _: i32
  _: i32
  CharacterSize: i32
  _: i32
  _: i32
  _: i32
  IntroSoundFile: string @file(ext: ".ogg")
  StartWeapons: [BaseItemTypes]
  Gender: string
  TraitDescription: string @localized
  _: rid
  _: rid
  _: [rid]
  _: rid
  _: rid
  _: i32
  PassiveTreeImage: string @file(ext: ".dds")
  _: i32
  _: i32
  AttrsAsId: string
  LoginScreen: string @file(ext: ".ao")
  PlayerCritter: string
  PlayerEffect: string
  AfterImage: string
  Mirage: MonsterVarieties
  CloneImmobile: MonsterVarieties
  ReplicateClone: MonsterVarieties
  LightningClone: MonsterVarieties
  _: f32
  _: f32
  SkillTreeBackground: string
  Clone: MonsterVarieties
  _: [_]
  MirageWarrior: MonsterVarieties
  DoubleTwo: MonsterVarieties
  DarkExile: MonsterVarieties
  Attr: string
  AttrLowercase: string
  Script: string
  _: rid
  _: i32
  _: f32
  _: f32
  _: f32
  _: string
  _: i32
  _: rid
  _: [rid]
  _: f32
  GemCuttingIcon: string
}

type Ascendancy {
  Id: string @unique
  ClassNo: i32
  Characters: [Characters]
  "Coordinates in 'x1, y1, x2, y2' format"
  CoordinateRect: string
  RGBFlavourTextColour: string
  Name: string @localized
  FlavourText: string @localized
  OGGFile: string @file(ext: ".ogg")
  PassiveTreeImage: string @file(ext: ".dds")
  _: i32
  _: i32
  _: i32
  _: i32
  Disabled: bool
}

type AttributeRequirements {
  BaseItemTypesKey: BaseItemTypes
  ReqStr: i32
  ReqInt: i32
  ReqDex: i32
}

type BeltTypes {
  BaseItem: BaseItemTypes
  CharmSlots: i32
}

type BuffDefinitions {
  Id: string @unique
  Description: string
  Invisible: bool
  Removable: bool
  Name: string
  StatsKeys: [Stats]
  _: bool
  _: i32
  _: bool
  Maximum_StatsKey: Stats
  Current_StatsKey: Stats
  _: bool
  _: i32
  BuffVisualsKey: BuffVisuals
  _: bool
  _: bool
  BuffCategory: i32
  _: bool
  _: bool
  _: bool
  _: bool
  BuffLimit: i32
  _: bool
  Id2: string
  IsRecovery: bool
  _: bool
  _: rid
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: [i32]
  _: bool
  _: bool
  _: [rid]
  _: bool
  _: [Stats]
  BinaryStats: [Stats]
  _: [Stats]
  _: [Stats]
  _: bool
  _: bool
  _: bool
  _: bool
  _: Stats
  _: [i32]
  _: string
  _: [Stats]
  _: [i32]
  _: i32
  _: [rid]
}

type BuffTemplates {
  Id: string @unique
  BuffDefinitionsKey: BuffDefinitions
  Buff_StatValues: [i32]
  AuraRadius: i32
  _: [i32]
  _: [i32]
  BuffVisualsKey: BuffVisuals
  _: f32
  _: bool
  StatsKey: [Stats]
  _: i32
  _: i32
  _: bool
  _: Stats
  _: bool
}

type CharacterMeleeSkills {
  _: rid
  _: rid
  SkillGemsKey: SkillGems
}

type ClientStrings {
  Id: string @unique
  Text: string
  XBoxText: string
  XBoxText2: string
  HASH32: i32
  PlaystationText: string
  _: string
}

type CostTypes {
  Id: string @unique
  StatsKey: Stats
  FormatText: string
  _: i32
  _: bool
}

type CraftingBenchOptions @tags(list: ["crafting"]) {
  _: rid
  Order: i32
  AddMod: Mods
  Cost_BaseItemTypes: [BaseItemTypes]
  Cost_Values: [i32]
  RequiredLevel: i32
  Name: string
  CraftingBenchCustomAction: CraftingBenchCustomActions
  ItemClasses: [ItemClasses]
  Links: i32
  SocketColours: string
  Sockets: i32
  ItemQuantity: i32
  _: [i32]
  Description: string
  IsDisabled: bool
  IsAreaOption: bool
  RecipeIds: [RecipeUnlockDisplay] @ref(column: "RecipeId")
  Tier: i32
  CraftingItemClassCategories: [CraftingItemClassCategories]
  _: i32
  UnlockCategory: CraftingBenchUnlockCategories
  UnveilsRequired: i32
  UnveilsRequired2: i32
  _: [rid]
  _: [rid]
  _: i32
  _: i32
  _: rid
  AddEnchantment: Mods
  SortCategory: CraftingBenchSortCategories
  _: rid
  _: bool
  _: i32
  _: Stats
  _: Stats
  _: Stats
}

type CraftingItemClassCategories {
  Id: string @unique
  ItemClasses: [ItemClasses]
  _: string
  Text: string
}

type DefaultMonsterStats {
  DisplayLevel: string
  Damage: f32
  Evasion: i32
  Accuracy: i32
  Life: i32
  Experience: i32
  AllyLife: i32
  _: i32
  Difficulty: i32
  Damage2: f32
  _: i32
  _: f32
  _: f32
  _: i32
  _: i32
  Armour: i32
  _: i32
  _: i32
}

type Flasks @tags(list: ["item:def"]) {
  BaseItemTypesKey: BaseItemTypes @unique
  Name: string
  Type: FlaskType
  LifePerUse: i32
  ManaPerUse: i32
  "in 1/10 s"
  RecoveryTime: i32
  RecoveryTime2: i32
  BuffDefinitionsKey: BuffDefinitions
  _: i32
  UtilityBuff: [UtilityFlaskBuffs]
}

type FlavourText {
  Id: string @unique
  HASH16: i16
  Text: string
}

type GemTags {
  Id: string @unique
  Tag: string
  Stat1: Stats
  Stat2: Stats
  Stat3: Stats
}

type GrantedEffectLabels {
  Id: string
  Text: string
  _: bool
  _: bool
  _: bool
}

type GrantedEffectQualityStats @tags(list: ["item:droptable"]) {
  GrantedEffectsKey: GrantedEffects
  StatsKeys: [Stats]
  StatsValuesPermille: [i32]
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: [i32]
}

type GrantedEffects {
  Id: string @unique
  IsSupport: bool
  "This support gem only supports active skills with at least one of these types"
  AllowedActiveSkillTypes: [ActiveSkillType]
  SupportGemLetter: string
  "This support gem adds these types to supported active skills"
  AddedActiveSkillTypes: [ActiveSkillType]
  "This support gem does not support active skills with one of these types"
  ExcludedActiveSkillTypes: [ActiveSkillType]
  "This support gem only supports active skills that come from gem items"
  SupportsGemsOnly: bool
  HASH32: i32
  CannotBeSupported: bool
  _: i32
  CastTime: i32
  ActiveSkill: ActiveSkills
  IgnoreMinionTypes: bool
  _: bool
  AddedMinionActiveSkillTypes: [ActiveSkillType]
  Animation: Animation
  MultiPartAchievement: MultiPartAchievements
  _: bool
  SupportWeaponRestrictions: [ItemClasses]
  RegularVariant: GrantedEffects
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  StatSet: GrantedEffectStatSets
  AdditionalStatSets: [GrantedEffectStatSets]
  _: string
  CostTypes: [CostTypes]
  _: bool
  _: [i32]
  _: i32
}

type HideoutNPCs {
  Hideout_NPCsKey: NPCs
  Regular_NPCsKeys: [NPCs]
  HideoutDoodadsKey: HideoutDoodads
  NPCMasterKey: i32
  _: rid
  _: rid
  _: i32
  _: rid
}

type ItemExperiencePerLevel {
  ItemExperienceType: ItemExperienceTypes
  ItemCurrentLevel: i32
  Experience: i32
  Level: i32
}

type ItemStances {
  Id: string @unique
  _: bool
  _: ItemStances
}

type ItemVisualIdentity {
  Id: string @unique
  DDSFile: string @file(ext: ".dds")
  AOFile: string @file(ext: ".ao")
  InventorySoundEffect: SoundEffects
  HASH16: i16 @unique
  AOFile2: string @file(ext: ".ao")
  MarauderSMFiles: [string] @file(ext: ".sm")
  RangerSMFiles: [string] @file(ext: ".sm")
  WitchSMFiles: [string] @file(ext: ".sm")
  DuelistDexSMFiles: [string] @file(ext: ".sm")
  TemplarSMFiles: [string] @file(ext: ".sm")
  ShadowSMFiles: [string] @file(ext: ".sm")
  ScionSMFiles: [string] @file(ext: ".sm")
  MarauderShape: string
  RangerShape: string
  WitchShape: string
  DuelistShape: string
  TemplarShape: string
  ShadowShape: string
  ScionShape: string
  _: rid
  _: i32
  Pickup_AchievementItemsKeys: [AchievementItems]
  SMFiles: [string] @file(ext: ".sm")
  Identify_AchievementItemsKeys: [AchievementItems]
  EPKFile: string @file(ext: ".epk")
  Corrupt_AchievementItemsKeys: [AchievementItems]
  IsAlternateArt: bool
  _: bool
  CreateCorruptedJewelAchievementItemsKey: AchievementItems
  AnimationLocation: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  IsAtlasOfWorldsMapIcon: bool
  IsTier16Icon: bool
  _: [i32]
  _: bool
  _: [rid]
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  "0: Standard, 1: Flask, 2: Divination Card, 3: Gem"
  Composition: i32
  _: rid
  _: rid
  _: rid
  _: rid
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: rid
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
}

type Maps @tags(list: ["item:def", "item:recipe"]) {
  BaseItemTypesKey: BaseItemTypes @unique
  Regular_WorldAreasKey: WorldAreas
  MonsterPacksKeys: [MonsterPacks]
  AchievementItem: AchievementItems
  _: string
  Tier: i32
  MapSeriesKey: i32
  _: bool
  _: bool
  _: bool
}

type MapSeries {
  Id: string @unique
  Name: string
  BaseIcon_DDSFile: string @file(ext: ".dds")
  Infected_DDSFile: string @file(ext: ".dds")
  Shaper_DDSFile: string @file(ext: ".dds")
  Elder_DDSFile: string @file(ext: ".dds")
  Drawn_DDSFile: string @file(ext: ".dds")
  Delirious_DDSFile: string @file(ext: ".dds")
  UberBlight_DDSFile: string @file(ext: ".dds")
}

type PassiveJewelSlots {
  Slot: PassiveSkills
  ClusterJewelSize: PassiveTreeExpansionJewelSizes
  _: i32
  ReplacesSlot: PassiveJewelSlots
  ProxySlot: PassiveSkills
  StartIndices: [i32]
}

type PassiveSkillMasteryEffects {
  Id: string
  HASH16: i16
  Stats: [Stats]
  Stat1Value: i32
  Stat2Value: i32
  Stat3Value: i32
  AchievementItem: AchievementItems
}

type ShieldTypes @tags(list: ["item:def"]) {
  BaseItemTypesKey: BaseItemTypes @unique
  Block: i32
  _: i32
}

type SkillCraftingData {
  Id: string
  CharactersKey: Characters
  ListBackground: string
  Icon: string
  ConsoleIcon: string
  Name: string
}

type SoulCores {
  BaseItemTypesKey: BaseItemTypes
  StatsKeysWeapon: [Stats]
  StatsValuesWeapon: [i32]
  StatsKeysArmour: [Stats]
  StatsValuesArmour: [i32]
}

type Stats @tags(list: ["crafting"]) {
  Id: string @unique
  _: bool
  IsLocal: bool
  IsWeaponLocal: bool
  Semantics: StatSemantics
  Text: string
  _: bool
  IsVirtual: bool
  MainHandAlias_StatsKey: Stats
  OffHandAlias_StatsKey: Stats
  _: bool
  HASH32: i32
  BelongsActiveSkillsKey: [ActiveSkills] @ref(column: "Id")
  Category: PassiveSkillStatCategories
  _: bool
  _: bool
  """
  If not, displayed in advanced mod description as " — Unscalable Value"
  """
  IsScalable: bool
  ContextFlags: [VirtualStatContextFlags]
  _: [rid]
  _: bool
}

type UtilityFlaskBuffs {
  BuffDefinitionsKey: BuffDefinitions
  StatValues: [i32]
  StatValues2: [i32]
  _: rid
}

type WeaponClasses {
  ItemClass: ItemClasses
  RangeMax: i32
  _: rid
}

type WeaponTypes @tags(list: ["item:def"]) {
  BaseItemTypesKey: BaseItemTypes @unique
  Critical: i32
  _: rid
  "1000 / speed -> attacks per second"
  Speed: i32
  DamageMin: i32
  DamageMax: i32
  RangeMax: i32
  _: i32
}
