# noinspection GraphQLMemberRedefinition,GraphQLTypeRedefinition
type ActiveSkills {
  Id: string @unique
  DisplayedName: string
  Description: string
  ActionType: ActionTypes
  Icon_DDSFile: string @file(ext: ".dds")
  ActiveSkillTargetTypes: [ActiveSkillTargetTypes]
  ActiveSkillTypes: [ActiveSkillType]
  WeaponRestriction_ItemClasses: [ItemClasses]
  WebsiteDescription: string
  WebsiteImage: string
  HideOnWebsite: bool
  GrantedEffect: string
  _: bool
  SkillTotemId: SkillTotems
  IsManuallyCasted: bool
  Input_Stats: [Stats]
  Output_Stats: [Stats]
  MinionActiveSkillTypes: [ActiveSkillType]
  _: bool
  isGem: bool
  SecondarySkillSpecificStats: [Stats]
  SkillMine: i32
  AlternateSkillTargetingBehaviour: AlternateSkillTargetingBehaviours
  _: bool
  AIFile: string @file(ext: ".ai")
  StatContextFlags: [VirtualStatContextFlags]
  _: bool
  _: bool
  _: bool
  TransfigureBase: ActiveSkills
  VideoClip: string @file(ext: ".bk2")
  _: rid
  AiScript: string @file(ext: ".ais")
  _: rid
  _: rid
  _: bool
  _: string
  StatDescriptionType: i32
  StatDescription: string
}

type ActionTypes {
  Id: string @unique
  _: u16
  _: bool
  _: bool
  _: bool
  _: bool
}

type Acts {
  Id: string @unique
  UI_Title: string
  ActNumber: i32
  _: string
  _: string
  _: i32
  IsEndGame: bool
  _: i32
  _: [rid]
  _: [rid]
  _: [rid]
  _: rid
  _: [rid]
  Description: string
}

type AegisVariations {
  Id: string @unique
  DefendsAgainstPhysical: bool
  DefendsAgainstFire: bool
  DefendsAgainstCold: bool
  DefendsAgainstLightning: bool
  DefendsAgainstChaos: bool
  _: rid
  _: rid
  _: rid
  _: bool
  _: [string]
}

type ArmourTypes @tags(list: ["item:def"]) {
  BaseItemTypes: BaseItemTypes @unique
  Armour: i32
  Evasion: i32
  EnergyShield: i32
  IncreasedMovementSpeed: i32
  Ward: i32
  _: i32
}

type AtlasPassiveSkillSubTrees {
  Id: string @unique
  UI_Image: string
  UI_Background: string
  IllustrationX: i32
  IllustrationY: i32
  CounterX: i32
  CounterY: i32
  _: rid
  _: rid
}

type BaseItemTypes @tags(list: ["item:def", "item:droptable"]) {
  Id: string @unique
  ItemClasses: ItemClasses
  Width: i32
  Height: i32
  Name: string @localized
  InheritsFrom: string @files(ext: [".ot", ".otc"])
  DropLevel: i32
  FlavourText: FlavourText
  Implicit_Mods: [Mods]
  SizeOnGround: i32
  SoundEffect: SoundEffects
  Tags: [Tags]
  ModDomain: ModDomains
  SiteVisibility: i32
  ItemVisualIdentity: ItemVisualIdentity
  HASH32: i32 @unique
  VendorRecipe_AchievementItems: [AchievementItems]
  "the inflection identifier used for i18n in related fields"
  Inflection: string
  Equip_AchievementItems: AchievementItems
  IsCorrupted: bool
  Identify_AchievementItems: [AchievementItems]
  IdentifyMagic_AchievementItems: [AchievementItems]
  "the item which represents this item in the fragment stash tab"
  FragmentBaseItemTypes: BaseItemTypes
  _: bool
  _: rid
  _: rid
  _: bool
  TradeMarketCategory: TradeMarketCategory
  Unmodifiable: bool
  Achievement: [AchievementItems]
  _: rid # spells have some values
  _: rid # all nulls
}


type Chanceableitemclasses {
  ItemClass: ItemClasses
  _: i32
}

type CharacterCreationButton {
  _: rid
  _: string
  _: string
  _: string
  _: string
}

type CharacterCreationDialogue {
  _: rid
  _: rid
  _: rid
  _: rid
}

type CurrencyItems @tags(list: ["item:def", "item:recipe"]) {
  BaseItemTypes: BaseItemTypes @unique
  StackSize: i32
  CurrencyUseType: i32
  Action: string
  Directions: string
  "Full stack transforms into this item"
  FullStack_BaseItemTypes: BaseItemTypes
  Description: string
  Usage_AchievementItems: [AchievementItems]
  Scroll: bool
  Possession_AchievementItems: AchievementItems
  _: [rid]
  _: [i32]
  CurrencyTab_StackSize: i32
  XBoxDirections: string
  _: i32
  ModifyMapsAchievements: [AchievementItems]
  ModifyContractsAchievements: [AchievementItems]
  CombineAchievements: [AchievementItems]
  ChangedForHardmode: bool
  DescriptionHardmode: string
  IsGold: bool
  UsageHint: string
  _: bool
}


type EndgameCorruptionMods {
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
}

type GemEffects {
  Id: string @unique
  Name: string
  GrantedEffect: GrantedEffects
  SupportText: string
  SupportName: string
  GemTags: [GemTags]
  Consumed_Mods: Mods
  "Used by gem icon shader https://gist.github.com/zao/08878df57aba605e5fa1e6373f2dce02"
  ItemColor: i32
  _: [rid]
  AdditionalGrantedEffects: [GrantedEffects]
  _: bool
  _: bool
  _: [i32]
  _: i32
}

type GoldModPrices {
  Mod: Mods
  Value: i32
  _: i32
  _: i32
  _: i32
  Tags: [Tags]
  SpawnWeight: [i32]
  CraftableType: CraftableModTypes
  _: [rid]
}

type CraftableModTypes {
  ModType: ModType
  HASH16: u16
}

type GrantedEffectsPerLevel {
  GrantedEffect: GrantedEffects
  Level: i32
  CostMultiplier: i32
  StoredUses: i32
  Cooldown: i32
  CooldownBypassType: CooldownBypassTypes
  VaalSouls: i32
  VaalStoredUses: i32
  CooldownGroup: i32
  PvPDamageMultiplier: i32
  SoulGainPreventionDuration: i32
  AttackSpeedMultiplier: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  AttackTime: i32
  Reservation: i32
  _: i32
  CostAmounts: [i32]
  _: f32
  EffectOnPlayer: i32
}

type GrantedEffectStatSets {
  Id: string @unique
  Label: GrantedEffectLabels
  ImplicitStats: [Stats]
  ConstantStats: [Stats]
  ConstantStatsValues: [i32]
  BaseEffectiveness: f32
  IncrementalEffectiveness: f32
  DamageIncrementalEffectiveness: f32
  _: [rid]
  _: bool
}

type GrantedEffectStatSetsPerLevel {
  StatSet: GrantedEffectStatSets
  GemLevel: i32
  SpellCritChance: i32
  AttackCritChance: i32
  BaseResolvedValues: [i32]
  AdditionalStatsValues: [i32]
  GrantedEffects: [GrantedEffects]
  _: bool
  _: i32
  AdditionalFlags: [Stats]
  FloatStats: [Stats]
  InterpolationBases: [Stats]
  AdditionalStats: [Stats]
  StatInterpolations: [StatInterpolationTypes]
  FloatStatsValues: [f32]
  ActorLevel: f32
  BaseMultiplier: i32
}

type ItemClasses @tags(list: ["crafting"]) {
  Id: string @unique
  Name: string
  TradeMarketCategory: TradeMarketCategory
  ItemClassCategory: ItemClassCategories
  RemovedIfLeavesArea: bool
  _: [_] # All rows empty
  IdentifyAchievements: [AchievementItems]
  AllocateToMapOwner: bool
  AlwaysAllocate: bool
  CanHaveVeiledMods: bool
  PickedUpQuest: QuestFlags
  _: i32
  AlwaysShow: bool
  CanBeCorrupted: bool
  CanHaveIncubators: bool
  CanHaveInfluence: bool
  CanBeDoubleCorrupted: bool
  CanHaveAspects: bool
  CanTransferSkin: bool
  ItemStance: ItemStances
  CanScourge: bool
  CanUpgradeRarity: bool
  _: bool
  InventoryDimensions: [i32]
  ItemClassFlags: [i32]
  Unmodfiable: bool
  CanBeFractured: bool
  EquipAchievements: AchievementItems
  UsableInMapDevice: bool
}

type ItemInherentSkills {
  BaseItemTypes: BaseItemTypes
  SkillsGranted: [SkillGems]
  IsWeapon: bool
}

type ItemSpirit {
  BaseItemTypes: BaseItemTypes
  SpiritGranted: i32
}

type KeywordPopups {
  Id: string @unique
  Term: string
  Definition: string
  _: string
}

type Mods @tags(list: ["crafting"]) {
  Id: string @unique
  HASH16: u16
  ModType: ModType
  Level: i32
  Stat1: Stats
  Stat2: Stats
  Stat3: Stats
  Stat4: Stats
  Domain: ModDomains
  Name: string
  GenerationType: ModGenerationType
  Families: [ModFamily]
  Stat1Value: i32 @interval
  Stat2Value: i32 @interval
  Stat3Value: i32 @interval
  Stat4Value: i32 @interval
  SpawnWeight_Tags: [Tags]
  SpawnWeight_Values: [i32]
  Tags: [Tags]
  GrantedEffectsPerLevel: [GrantedEffectsPerLevel]
  _: [i32]
  MonsterMetadata: string
  MonsterKillAchievements: [AchievementItems]
  ChestModType: [ModType]
  Stat5Value: i32 @interval
  Stat5: Stats
  FullAreaClear_AchievementItems: [AchievementItems]
  AchievementItems: [AchievementItems]
  GenerationWeight_Tags: [Tags]
  GenerationWeight_Values: [i32]
  ModifyMapsAchievements: [AchievementItems]
  IsEssenceOnlyModifier: bool
  Stat6Value: i32 @interval
  Stat6: Stats
  MaxLevel: i32
  _: bool
  CraftingItemClassRestrictions: [ItemClasses]
  MonsterOnDeath: string
  _: i32
  _: [GrantedEffectsPerLevel]
  Heist_SubStatValue1: i32
  Heist_SubStatValue2: i32
  Heist_StatsKey0: Stats
  Heist_StatsKey1: Stats
  Heist_AddStatValue1: i32
  Heist_AddStatValue2: i32
  InfluenceTypes: InfluenceTypes
  ImplicitTags: [Tags]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  BuffTemplate: BuffTemplates
  ArchnemesisMinionMod: Mods
  HASH32: i32
  _: [rid]
  _: i32
  _: [GrantedEffectsPerLevel]
  RadiusJewelType: i32
}

type PassiveSkills {
  Id: string @unique
  Icon_DDSFile: string @file(ext: ".dds")
  Stats: [Stats]
  Stat1Value: i32
  Stat2Value: i32
  Stat3Value: i32
  Stat4Value: i32
  "Id used by PassiveSkillGraph.psg"
  PassiveSkillGraphId: u16 @unique
  Name: string
  Characters: [Characters]
  IsKeystone: bool
  IsNotable: bool
  FlavourText: string
  IsJustIcon: bool
  AchievementItem: AchievementItems
  IsJewelSocket: bool
  Ascendancy: Ascendancy
  IsAscendancyStartingNode: bool
  ReminderStrings: [ReminderText]
  SkillPointsGranted: i32
  IsMultipleChoice: bool
  IsMultipleChoiceOption: bool
  Stat5Value: i32
  PassiveSkillBuffs: [BuffTemplates]
  IsAnointmentOnly: bool
  _: i32
  IsExpansion: bool
  IsProxyPassive: bool
  SkillType: PassiveSkillTypes
  MasteryGroup: PassiveSkillMasteryGroups
  Group: AtlasPassiveSkillTreeGroupType
  SoundEffect: SoundEffects
  AtlasnodeGroup: string
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: [rid]
  _: i32
  _: [rid]
  _: bool
  KeystoneId: rid
  _: bool
  IsAttribute: bool
  AtlasSubTree: AtlasPassiveSkillSubTrees
  IsRootOfAtlasTree: bool
  GrantedSkill: SkillGems
  WeaponPointsGranted: i32
}

type SkillGems @tags(list: ["item:def"]) {
  BaseItemTypes: BaseItemTypes @unique
  StrengthRequirementPercent: i32
  DexterityRequirementPercent: i32
  IntelligenceRequirementPercent: i32
  VaalVariant_BaseItemTypes: BaseItemTypes
  IsVaalVariant: bool
  MinionGlobalSkillLevelStat: Stats
  GemType: i32
  _: bool
  _: bool
  _: rid
  _: i32
  _: i32
  ItemExperienceType: ItemExperienceTypes
  CraftingTypes: [SkillCraftingData]
  _: [rid]
  _: bool
  GemEffects: [GemEffects]
  _: bool
  TutorialVideo: string @file(ext: ".bk2")
  UI_Image: string @file(ext: ".dds")
  _: i32
  CraftingLevel: i32
  _: bool
  _: i32
  _: bool
  _: string
}

type SkillGemSupports {
  SkillGems: SkillGems
  Supports: [SkillGems]
}

type SupportGems {
  SkillGems: SkillGems
  _: i32
  Icon: string  @file(ext: ".dds")
}


type Tags {
  Id: string @unique
  HASH32: i32
  DisplayString: string
  _: [rid]
  UiHints: string
}

type UncutGemAdditionalTiers {
  BaseItemType: BaseItemTypes
  AreaLevel: i32
  Tier: i32
  Odds: i32
}


type UncutGemTiers {
  BaseItemType: BaseItemTypes
  Tier: i32
  AreaLevel: i32
}

type ClassPassiveSkillOverrides {
  CharacterToOverrideFor: Characters
  SkillToOverride: PassiveSkills
  Override: PassiveSkills
}

type Characters {
  Id: string @unique
  Name: string @unique @localized
  AOFile: string @file(ext: ".ao")
  ACTFile: string @file(ext: ".act")
  BaseMaxLife: i32
  BaseMaxMana: i32
  "Attack Speed in milliseconds"
  WeaponSpeed: i32
  MinDamage: i32
  MaxDamage: i32
  MaxAttackDistance: i32
  Icon: string
  IntegerId: i32 @unique
  BaseStrength: i32
  BaseDexterity: i32
  BaseIntelligence: i32
  _: [rid]
  Description: string @localized
  StartSkillGem: SkillGems
  _: rid
  _: i32
  _: i32
  CharacterSize: i32
  _: i32
  _: i32
  _: i32
  IntroSoundFile: string @file(ext: ".ogg")
  StartWeapons: [BaseItemTypes]
  Gender: string
  TraitDescription: string @localized
  _: rid
  _: rid
  _: [rid]
  _: rid
  _: rid
  _: i32
  PassiveTreeImage: string @file(ext: ".dds")
  _: i32
  _: i32
  AttrsAsId: string
  LoginScreen: string @file(ext: ".ao")
  PlayerCritter: string
  PlayerEffect: string
  AfterImage: string
  Mirage: MonsterVarieties
  CloneImmobile: MonsterVarieties
  ReplicateClone: MonsterVarieties
  LightningClone: MonsterVarieties
  _: f32
  _: f32
  SkillTreeBackground: string
  Clone: MonsterVarieties
  _: [_]
  MirageWarrior: MonsterVarieties
  DoubleTwo: MonsterVarieties
  DarkExile: MonsterVarieties
  Attr: string
  AttrLowercase: string
  Script: string
  _: rid
  _: i32
  _: f32
  _: f32
  _: f32
  BaseClass: string
  _: i32
  _: rid
  _: [rid]
  _: f32
  GemCuttingIcon: string
}

type Ascendancy {
  Id: string @unique
  ClassNo: i32
  Characters: [Characters]
  "Coordinates in 'x1, y1, x2, y2' format"
  CoordinateRect: string
  RGBFlavourTextColour: string
  Name: string @localized
  FlavourText: string @localized
  OGGFile: string @file(ext: ".ogg")
  PassiveTreeImage: string @file(ext: ".dds")
  _: i32
  _: i32
  _: i32
  _: i32
  Disabled: bool
}

type AttributeRequirements {
  BaseItemTypes: BaseItemTypes
  ReqStr: i32
  ReqInt: i32
  ReqDex: i32
}

type BeltTypes {
  BaseItem: BaseItemTypes
  CharmSlots: i32
}

type BuffDefinitions {
  Id: string @unique
  Description: string
  Invisible: bool
  Removable: bool
  Name: string
  Stats: [Stats]
  CancelOnDeath: bool
  MergeMode: BuffMergeModes
  ShowCount: bool
  Maximum_Stat: Stats
  Current_Stat: Stats
  _: bool
  _: i32
  BuffVisual: BuffVisuals
  _: bool
  _: bool
  BuffCategory: i32
  _: bool
  _: bool
  _: bool
  _: bool
  BuffLimit: i32
  _: bool
  Implementation: string
  IsRecovery: bool
  _: bool
  MinStat: Stats
  _: bool
  UIStackMode: i32
  _: bool
  IsSkillBuff: bool
  _: i32
  _: [i32]
  _: bool
  _: bool
  _: [rid]
  _: bool
  Stats2: [Stats]
  GrantedFlags: [Stats]
  GrantedStats: [Stats]
  ConditionStats: [Stats]
  _: bool
  _: bool
  _: bool
  _: bool
  _: Stats
  _: [i32]
  _: string
  _: [Stats]
  _: [i32]
  _: i32
  _: [rid]
}

type BuffTemplates {
  Id: string @unique
  BuffDefinitions: BuffDefinitions
  Buff_StatValues: [i32]
  AuraRadius: i32
  _: [i32]
  _: [i32]
  BuffVisuals: BuffVisuals
  _: f32
  _: bool
  Stats: [Stats]
  _: i32
  _: i32
  _: bool
  _: Stats
  _: bool
}

type CharacterMeleeSkills {
  _: rid
  _: rid
  SkillGems: SkillGems
}

type ClientStrings {
  Id: string @unique
  Text: string
  XBoxText: string
  XBoxText2: string
  HASH32: i32
  PlaystationText: string
  _: string
}

type CostTypes {
  Id: string @unique
  Stats: Stats
  FormatText: string
  Divisor: i32
  PerMinute: bool
}

type CraftingBenchOptions @tags(list: ["crafting"]) {
  HideoutNPC: HideoutNPCs
  Order: i32
  AddMod: Mods
  Cost_BaseItemTypes: [BaseItemTypes]
  Cost_Values: [i32]
  RequiredLevel: i32
  Name: string
  CraftingBenchCustomAction: CraftingBenchCustomActions
  ItemClasses: [ItemClasses]
  Links: i32
  SocketColours: string
  Sockets: i32
  ItemQuantity: i32
  _: [i32]
  Description: string
  IsDisabled: bool
  IsAreaOption: bool
  RecipeIds: [RecipeUnlockDisplay] @ref(column: "RecipeId")
  Tier: i32
  CraftingItemClassCategories: [CraftingItemClassCategories]
  _: i32
  UnlockCategory: CraftingBenchUnlockCategories
  UnveilsRequired: i32
  UnveilsRequired2: i32
  _: [rid]
  KalandraAchievement: [AchievementItems]
  _: i32
  _: i32
  VeiledMods: Mods
  AddEnchantment: Mods
  SortCategory: CraftingBenchSortCategories
  ModType: ModType
  _: bool
  _: i32
  Stat1: Stats
  Stat2: Stats
  Stat3: Stats
}

type CraftingItemClassCategories {
  Id: string @unique
  ItemClasses: [ItemClasses]
  _: string
  Text: string
}

type DefaultMonsterStats {
  DisplayLevel: string
  Damage: f32
  Evasion: i32
  Accuracy: i32
  Life: i32
  Experience: i32
  AllyLife: i32
  Armour: i32
  Difficulty: i32
  MinionDamage: f32
  AltLife1: i32
  AltDamage1: f32
  AltDamage2: f32
  AltLife2: i32
  EvasiveEvasion: i32
  AilmentThreshold: i32
  StunThreshold: i32
  _: i32
}

type Flasks @tags(list: ["item:def"]) {
  BaseItemTypes: BaseItemTypes @unique
  Name: string
  Type: FlaskType
  LifePerUse: i32
  ManaPerUse: i32
  "in 1/10 s"
  RecoveryTime: i32
  RecoveryTime2: i32
  BuffDefinitions: BuffDefinitions
  _: i32
  UtilityBuff: [UtilityFlaskBuffs]
}

type FlavourText {
  Id: string @unique
  HASH16: i16
  Text: string
}

type GemTags {
  Id: string @unique
  Name: string
  LocalLevelStat: Stats
  LocalQualityStat: Stats
  GlobalSpellLevelStat: Stats
}

type GrantedEffectLabels {
  Id: string
  Text: string
  _: bool
  _: bool
  _: bool
}

type GrantedEffectQualityStats @tags(list: ["item:droptable"]) {
  GrantedEffects: GrantedEffects
  Stats: [Stats]
  StatsValuesPermille: [i32]
  AddTypes: [ActiveSkillType]
  AddMinionTypes: [ActiveSkillType]
  _: [i32]
}

type GrantedEffects {
  Id: string @unique
  IsSupport: bool
  "This support gem only supports active skills with at least one of these types"
  AllowedActiveSkillTypes: [ActiveSkillType]
  SupportGemLetter: string
  "This support gem adds these types to supported active skills"
  AddedActiveSkillTypes: [ActiveSkillType]
  "This support gem does not support active skills with one of these types"
  ExcludedActiveSkillTypes: [ActiveSkillType]
  "This support gem only supports active skills that come from gem items"
  SupportsGemsOnly: bool
  HASH32: u32
  CannotBeSupported: bool
  LifeLeech: i32
  CastTime: i32
  ActiveSkill: ActiveSkills
  IgnoreMinionTypes: bool
  CooldownNotRecoverDuringActive: bool
  AddedMinionActiveSkillTypes: [ActiveSkillType]
  Animation: Animation
  MultiPartAchievement: MultiPartAchievements
  _: bool
  SupportWeaponRestrictions: [ItemClasses]
  RegularVariant: GrantedEffects
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  StatSet: GrantedEffectStatSets
  AdditionalStatSets: [GrantedEffectStatSets]
  Audio: string
  CostTypes: [CostTypes]
  _: bool
  _: [i32]
  _: i32
}

type HideoutNPCs {
  Hideout_NPCs: NPCs
  Regular_NPCs: [NPCs]
  HideoutDoodads: HideoutDoodads
  NPCMaster: i32
  _: rid
  _: rid
  _: i32
  _: rid
}

type ItemExperiencePerLevel {
  ItemExperienceType: ItemExperienceTypes
  ItemCurrentLevel: i32
  Experience: i32
  Level: i32
}

type ItemStances {
  Id: string @unique
  _: bool
  _: ItemStances
}

type ItemVisualIdentity {
  Id: string @unique
  DDSFile: string @file(ext: ".dds")
  AOFile: string @file(ext: ".ao")
  InventorySoundEffect: SoundEffects
  HASH16: i16 @unique
  AOFile2: string @file(ext: ".ao")
  MarauderSMFiles: [string] @file(ext: ".sm")
  RangerSMFiles: [string] @file(ext: ".sm")
  WitchSMFiles: [string] @file(ext: ".sm")
  DuelistDexSMFiles: [string] @file(ext: ".sm")
  TemplarSMFiles: [string] @file(ext: ".sm")
  ShadowSMFiles: [string] @file(ext: ".sm")
  ScionSMFiles: [string] @file(ext: ".sm")
  MarauderShape: string
  RangerShape: string
  WitchShape: string
  DuelistShape: string
  TemplarShape: string
  ShadowShape: string
  ScionShape: string
  _: rid
  _: i32
  Pickup_AchievementItems: [AchievementItems]
  SMFiles: [string] @file(ext: ".sm")
  Identify_AchievementItems: [AchievementItems]
  EPKFile: string @file(ext: ".epk")
  Corrupt_AchievementItems: [AchievementItems]
  IsAlternateArt: bool
  _: bool
  CreateCorruptedJewelAchievementItems: AchievementItems
  AnimationLocation: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  IsAtlasOfWorldsMapIcon: bool
  IsTier16Icon: bool
  _: [i32]
  _: bool
  _: [rid]
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  "0: Standard, 1: Flask, 2: Divination Card, 3: Gem"
  Composition: i32
  _: rid
  _: rid
  _: rid
  _: rid
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  _: rid
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
}

type Maps @tags(list: ["item:def", "item:recipe"]) {
  BaseItemTypes: BaseItemTypes @unique
  Regular_WorldAreas: WorldAreas
  MonsterPacks: [MonsterPacks]
  AchievementItem: AchievementItems
  _: string
  Tier: i32
  MapSeries: i32
  _: bool
  _: bool
  _: bool
}

type MapSeries {
  Id: string @unique
  Name: string
  BaseIcon_DDSFile: string @file(ext: ".dds")
  Infected_DDSFile: string @file(ext: ".dds")
  Shaper_DDSFile: string @file(ext: ".dds")
  Elder_DDSFile: string @file(ext: ".dds")
  Drawn_DDSFile: string @file(ext: ".dds")
  Delirious_DDSFile: string @file(ext: ".dds")
  UberBlight_DDSFile: string @file(ext: ".dds")
}

type PassiveJewelSlots {
  Slot: PassiveSkills
  ClusterJewelSize: PassiveTreeExpansionJewelSizes
  ClusterIndex: i32
  ReplacesSlot: PassiveJewelSlots
  ProxySlot: PassiveSkills
  StartIndices: [i32]
}

type PassiveSkillMasteryEffects {
  Id: string
  HASH16: i16
  Stats: [Stats]
  Stat1Value: i32
  Stat2Value: i32
  Stat3Value: i32
  AchievementItem: AchievementItems
}

type ShieldTypes @tags(list: ["item:def"]) {
  BaseItemTypes: BaseItemTypes @unique
  Block: i32
  _: i32
}

type SkillCraftingData {
  Id: string
  Characters: Characters
  ListBackground: string
  Icon: string
  ConsoleIcon: string
  Name: string
}

type SoulCores {
  BaseItemTypes: BaseItemTypes
  StatsKeysWeapon: [Stats]
  StatsValuesWeapon: [i32]
  StatsKeysArmour: [Stats]
  StatsValuesArmour: [i32]
}

type Stats @tags(list: ["crafting"]) {
  Id: string @unique
  _: bool
  IsLocal: bool
  IsWeaponLocal: bool
  Semantics: StatSemantics
  Text: string
  _: bool
  IsVirtual: bool
  MainHandAlias_Stats: Stats
  OffHandAlias_Stats: Stats
  _: bool
  HASH32: i32
  BelongsActiveSkills: [ActiveSkills] @ref(column: "Id")
  Category: PassiveSkillStatCategories
  _: bool
  _: bool
  """
  If not, displayed in advanced mod description as " — Unscalable Value"
  """
  IsScalable: bool
  ContextFlags: [VirtualStatContextFlags]
  DotFlag: [VirtualStatContextFlags]
  WeaponHandCheck: bool
}

type UtilityFlaskBuffs {
  BuffDefinitions: BuffDefinitions
  StatValues: [i32]
  StatValues2: [i32]
  _: rid  
}

type WeaponClasses {
  ItemClass: ItemClasses
  RangeMax: i32
  _: rid
}

type WeaponTypes @tags(list: ["item:def"]) {
  BaseItemTypes: BaseItemTypes @unique
  Critical: i32
  _: rid
  "1000 / speed -> attacks per second"
  Speed: i32
  DamageMin: i32
  DamageMax: i32
  RangeMax: i32
  _: i32
}

type AlternatePassiveAdditions {
  Id: string @unique
  AlternateTreeVersion: AlternateTreeVersions
  SpawnWeight: i32
  Stats: [Stats]
  Stat1: i32 @interval
  Stat2: i32 @interval
  Stat3: i32 @interval
  PassiveType: [i32]
  _: i32
}

type AlternatePassiveSkills {
  Id: string @unique
  AlternateTreeVersion: AlternateTreeVersions
  Name: string
  PassiveType: [i32]
  Stats: [Stats]
  Stat1: i32 @interval
  Stat2: i32 @interval
  Stat3: i32 @interval
  Stat4: i32 @interval
  Stat5: i32 @interval
  Stat6: i32 @interval
  SpawnWeight: i32
  ConquerorIndex: i32
  Random: i32 @interval
  FlavourText: string
  DDSIcon: string @file(ext: ".dds")
  AchievementItems: [AchievementItems]
  ConquerorVersion: i32
  ConquerorSpawnWeight: i32
}

type AlternateTreeVersions {
  ConquerorType: string @unique
  SmallAttributeReplaced: bool
  SmallNormalPassiveReplaced: bool
  SmallAttributePassiveSkillAdditions: i32 @interval
  NotableAdditions: i32 @interval
  SmallNormalPassiveSkillAdditions: i32 @interval
  NotableReplacementSpawnWeight: i32
}

type AnimateWeaponUniques {
  Id: string @unique
  ItemVisualIdentity: ItemVisualIdentity
  ItemClass: ItemClasses
  _: i32
}

type BuffVisualOrbTypes {
  Id: string @unique
  _: f32
  _: f32
  _: f32
  _: f32
  _: i32
  _: bool
  RadiusStat: Stats
  HeightStat: Stats
  _: i32
  _: bool
  _: f32
  _: i32
  _: f32
  _: bool
  _: f32
}

type BuffVisualsArtVariations {
  Buff: string
  Visuals: [BuffVisuals]
  _: i32
}

type MonsterVarieties {
  Id: string @unique
  MonsterTypesKey: MonsterTypes
  MovementSpeed: i32
  ObjectSize: i32
  MinimumAttackDistance: i32
  MaximumAttackDistance: i32
  ACTFiles: [string] @file(ext: ".act")
  AOFiles: [string] @file(ext: ".ao")
  BaseMonsterTypeIndex: string @files(ext: [".ot", ".otc"])
  Mods: [Mods]
  _: i32
  _: string
  _: string
  "in percent"
  ModelSizeMultiplier: i32
  _: i32
  _: i32
  _: rid
  _: i32
  _: i32
  Tags: [Tags]
  "in percent"
  ExperienceMultiplier: i32
  _: [i32]
  MinAgroRange: i32
  MaxAgroRange: i32
  SpotlightColour1: i32
  SpotlightColour2: i32
  SpotlightColour3: i32
  GrantedEffects: [GrantedEffects]
  AISFile: string @file(ext: ".ais")
  ModsKeys2: [Mods]
  Stance: string
  _: rid
  Name: string
  "in percent"
  DamageMultiplier: i32
  "in percent"
  LifeMultiplier: i32
  "in ms"
  AttackSpeed: i32
  Weapon1_ItemVisualIdentity: [ItemVisualIdentity]
  Weapon2_ItemVisualIdentity: [ItemVisualIdentity]
  Back_ItemVisualIdentity: ItemVisualIdentity
  MainHand_ItemClasses: ItemClasses
  OffHand_ItemClasses: ItemClasses
  Helmet_ItemVisualIdentity: ItemVisualIdentity
  _: i32
  KillSpecificMonsterCount_AchievementItems: [AchievementItems]
  Special_Mods: [Mods]
  KillRare_AchievementItems: [AchievementItems]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  HASH16: u16
  _: bool
  _: string
  KillWhileOnslaughtIsActive_AchievementItem: AchievementItems
  MonsterSegment: MonsterSegments
  MonsterArmour: MonsterArmours
  KillWhileTalismanIsActive_AchievementItem: AchievementItems
  Part1_Mods: [Mods]
  Part2_Mods: [Mods]
  Endgame_Mods: [Mods]
  _: rid
  _: i32
  _: i32
  _: [rid]
  MultiPartAchievements: [MultiPartAchievements]
  _: i32
  SinkAnimation_AOFile: string @file(ext: ".ao")
  _: bool
  _: [rid]
  _: bool
  _: bool
  _: bool
  _: i32
  _: i32
  _: f32
  AilmentThreshold: i32
  SinkEffect: i32
  _: i32
  MonsterConditionalEffectPack: MonsterConditionalEffectPacks
  _: bool
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  BossHealthBar: bool
  _: rid
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: rid
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: string
  _: rid
  _: i32
  _: i32
}

type StatsFromSkillStats {
  SkillCondition: Stats
  GrantedFlag: Stats
  FlagValue: bool
}