# Added 4.2
type AchievementItemRewards @tags(list: ["mtx:reward"]) {
  AchievementItemsKey: AchievementItems
  BaseItemTypesKey: BaseItemTypes
  Message: string @localized
  Id: string @unique
  _: string @localized
}