enum ActiveSkillTargetTypes @indexing(first: 1) {
  TARGETABLE_GROUND
  ENEMY
  WALKABLE_GROUND
  ANYWHERE_SELF_TARGET
  ITEM
  CORPSE
  _
  NO_LINE_OF_SIGHT
  BEHIND_MONSTER
  SELF_ORIGIN
  ROTATE_TO_TARGET
}
