type AegisVariations {
  Id: string @unique
  DefendsAgainstPhysical: bool
  DefendsAgainstFire: bool
  DefendsAgainstCold: bool
  DefendsAgainstLightning: bool
  DefendsAgainstChaos: bool
  DefinitionBuff: BuffDefinitions
  DefinitionDepleted: BuffDefinitions
  DefinitionValue: BuffDefinitions
  _: bool
  _: rid
  _: [string]
}
