type Ascendancy {
  Id: string @unique
  ClassNo: i32
  Character: Characters
  "Coordinates in 'x1, y1, x2, y2' format"
  CoordinateRect: string
  RGBFlavourTextColour: string
  Name: string @localized
  FlavourText: string @localized
  OGGFile: string @file(ext: ".ogg")
  PassiveTreeImage: string @file(ext: ".dds")
  TreeRegionVector: i32
  TreeRegionAngle: i32
  _: bool
  BackgroundImage: i32
  _: i32
  _: i32
  _: rid
  _: i32
  _: rid
  _: rid
  _: rid
}
