type AwardDisplay {
  Id: string @unique
  Text: string
  BackgroundImage: string
  _: i32
  _: f32
  _: f32
  _: string
  _: string
  ForegroundImage: string
  OGGFile: string @file(ext: ".ogg")
  _: rid
  _: i32
  _: string
  _: bool
}
