# Added 3.17
type BattlePasses {
  Id: string @unique
  LeagueCategory: LeagueCategory
  International_BK2File: string
  China_BK2File: string
  MapCompletionCount: i32
  _: bool
  Id2: string @unique
}
