type BlightCraftingItems @tags(list: ["item:def"]) {
  BaseItemType: BaseItemTypes @unique
  Tier: i32
  Achievements: [AchievementItems]
  UseType: i32
  NameShort: string @unique
  EnchantedMod: Mods
}
