type BuffVisualOrbs {
  Id: string @unique
  BuffVisualOrbTypesKey: BuffVisualOrbTypes
  BuffVisualOrbArtKeys: [BuffVisualOrbArt]
  Player_BuffVisualOrbArtKeys: [BuffVisualOrbArt]
  BuffVisualOrbArtKeys2: [BuffVisualOrbArt]
}
