# Added 4.1
type BuffVisuals {
  Id: string @unique
  BuffDDSFile: string @file(ext: ".dds")
  EPKFiles1: [string] @file(ext: ".epk")
  EPKFiles2: [string] @file(ext: ".epk")
  PreloadGroups: [PreloadGroups]
  _: bool
  BuffName: string @localized
  MiscAnimated1: MiscAnimated
  MiscAnimated2: MiscAnimated
  BuffDescription: string @localized
  EPKFile: string @file(ext: ".epk")
  HasExtraArt: bool
  ExtraArt: string
  _: [i32]
  EPKFiles: [string] @file(ext: ".epk")
  BuffVisualOrbs: [BuffVisualOrbs]
  MiscAnimated3: MiscAnimated
  _: rid
  _: BuffVisuals
  _: rid
  _: f32
  _: f32
  _: bool
  _: bool
  _: [_]
  _: bool
  _: bool
  _: bool
  _: [i32]
}
