# Added 4.1
type DamageCalculationTypes {
  Id: string @unique
  PhysicalDamageStats: [Stats]
  FireDamageStats: [Stats]
  ColdDamageStats: [Stats]
  LightningDamageStats: [Stats]
  ChaosDamageStats: [Stats]
  CritChanceStat: Stats
  CritBonusStat: Stats
  AlwaysCritStat: Stats
  CannotCritStat: Stats
  StunThresholdStat: Stats
  StunDurationStat: Stats
  _: bool
  CannotBlockStat: Stats
  KnockbackStat: Stats
  KnockbackOnCritStat: Stats
  KnockbackChanceStat: Stats
  Text: string
  _: rid
  Type: i32
  IsAttack: bool
  _: Stats
  _: DamageCalculationTypes
  _: bool
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: bool
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
  _: Stats
}