type DeliriumStashTabLayout {
  Id: string @unique
  StoredItem: BaseItemTypes
  XOffset: i32
  YOffset: i32
  FirstSlotIndex: i32 @unique
  Width: i32
  Height: i32
  SlotSize: i32
  _: i32
  SlotIcon: DynamicStashSlots
  ShowIfEmpty: bool
}
