# Added 3.04
enum DelveUpgradeType @indexing(first: 0) {
  SULPHITE_CAPACITY
  FLARE_CAPACITY
  DYNAMITE_CAPACITY
  CART_LIGHT_RADIUS
  FLARE_LIGHT_RADIUS
  DYNAMITE_RADIUS
  _
  DYNAMITE_DAMAGE
  DARKNESS_RESISTANCE
  FLARE_DURATION
}
