type EffectDrivenSkill {
  _: i32
  _: [rid]
  _: [_] # All rows empty
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: [_] # All rows empty
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
}
