type EndgameMaps {
  _: i32
  WorldArea: WorldAreas @unique
  _: [i32]
  _: [rid]
  FlavourText: string @localized
  _: i32
  _: [i32]
  _: rid
  _: rid
  _: rid
  _: rid
  _: i32
  _: i32
  _: rid
  _: rid
  MapLocations: [EndgameMapLocation]
  SpecialMapText: string @localized
  SpecialMapFlavourText: string @localized
  SpecialMapHelpText: string @localized
}