# Added 4.1
type EndgameMapContent {
  Id: string @unique
  SpawnChance: [i32]
  _: i32
  _: i32
  _: i32
  _: i32
  InherentStat: [Stats]
  InherentStatValues: [i32]
  Icon: string @file(ext: ".dds")
  Description: string @localized
  Name: string @localized
  _: rid
  _: [i32]
  Stats: [Stats]
  _: i32
  _: rid
}