type EssenceStashTabLayout {
  Id: string @unique
  StoredItem: BaseItemTypes
  XOffset: i32
  YOffset: i32
  FirstSlotIndex: i32 @unique
  Width: i32
  Height: i32
  ShowIfEmpty: bool
  _: i32
  FrameType: i32
}