# Added 4.3
type EssenceMods {
  Essence: Essences
  TargetItemCategory: EssenceTargetItemCategories
  Mod: Mods
  DisplayMod: Mods
  Text: string @localized
  OutcomeMods: [Mods]
  OutcomeModWeights: [i32]
}
