# Added 4.1
type ExecuteGEAL {
  _: i32
  _: i32
  MiscAnimated: [MiscAnimated]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: [_]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  Script: string
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: string
  _: string
  _: string
  _: string
  _: string
  _: i32
  _: bool
  _: bool
  _: [_]
  _: i32
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
}
