type GemEffects {
  Id: string @unique
  Name: string
  GrantedEffect: GrantedEffects
  SupportText: string
  SupportName: string
  GemTags: [GemTags]
  Consumed_Mod: Mods
  "Used by gem icon shader https://gist.github.com/zao/08878df57aba605e5fa1e6373f2dce02"
  ItemColor: i32
  _: [rid]
  AdditionalGrantedEffects: [GrantedEffects]
  _: bool
  _: bool
  _: [i32]
  _: i32
  _: i32
}
