# Added 4.1
type GeometryAttack {
  _: i32
  _: [rid]
  _: [rid]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: [_]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: rid
  _: [i32]
  _: i32
  _: bool
  _: bool
  _: rid
  _: bool
  _: [i32]
  _: bool
  _: bool
  _: rid
  _: bool
  _: bool
  _: [_]
  _: bool
  _: bool
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: rid
}