# Added 4.1
type GeometryTrigger {
  _: i32
  _: rid
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  _: [rid]
  _: i32
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: rid
  _: bool
  _: bool
  _: i32
  _: i32
  _: [rid]
  _: [i32]
  _: i32
  _: f32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
}
