type GrantedEffects {
  Id: string @unique
  IsSupport: bool
  "This support gem only supports active skills with at least one of these types"
  AllowedActiveSkillTypes: [ActiveSkillType]
  SupportGemLetter: string
  "This support gem adds these types to supported active skills"
  AddedActiveSkillTypes: [ActiveSkillType]
  "This support gem does not support active skills with one of these types"
  ExcludedActiveSkillTypes: [ActiveSkillType]
  "This support gem only supports active skills that come from gem items"
  SupportsGemsOnly: bool
  HASH32: u32
  CannotBeSupported: bool
  LifeLeech: i32
  CastTime: i32
  ActiveSkill: ActiveSkills
  IgnoreMinionTypes: bool
  CooldownNotRecoverDuringActive: bool
  AddedMinionActiveSkillTypes: [ActiveSkillType]
  Animation: Animation
  MultiPartAchievement: MultiPartAchievements
  _: bool
  RegularVariant: GrantedEffects
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  StatSet: GrantedEffectStatSets
  AdditionalStatSets: [GrantedEffectStatSets]
  Audio: string
  CostTypes: [CostTypes]
  _: bool
  _: [i32]
  _: i32
  SupportWeaponRestrictions: [ItemClasses]
  _: string
  MinionType: MinionType
  _: f32
  _: f32
  _: i32
}