# Added 4.4
type Incursion2Medallions {
  Id: string @unique
  Name: string @localized
  FlavourText: string @localized
  Icon_DDSFile: string @file(ext: ".dds")
  _: bool
  MiscObject: MiscObjects
  Description: string @localized
  SoundEffect: SoundEffects
  _: i32
}
