# Added 4.4
type Incursion2Rooms {
  Id: string @unique
  IsPathway: bool
  UpgradedBy: [Incursion2Rooms]
  ConvertedBy: [Incursion2Rooms]
  ConvertedTo: [Incursion2Rooms]
  UpgradedByPower: i32
  IsPastExclusive: bool
  IsBossReward: bool
  Name: string @localized
  Icon_DDSFile: string @file(ext: ".dds")
}