# Added 2.02
type LabyrinthSecrets {
  Id: string
  Id2: string
  _: [i32]
  _: i32
  _: i32
  LabyrinthSecretEffectsKeys0: [LabyrinthSecretEffects]
  LabyrinthSecretEffectsKeys1: [LabyrinthSecretEffects]
  LabyrinthSecretEffectsKeys2: [LabyrinthSecretEffects]
  _: i32
  LabyrinthSecretEffectsKeys3: [LabyrinthSecretEffects]
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: bool
  Name: string
  AchievementItemsKey: AchievementItems
  LabyrinthTierMinimum: i32
  LabyrinthTierMaximum: i32
  _: bool
}
