type MapFragmentMods {
  BaseItemType: BaseItemTypes @unique
  Mods: [Mods]
  AchievementItems: [AchievementItems]
  MapFragmentFamilies: i32
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
}