type MapPins {
  Id: string @unique
  WorldArea: WorldAreas
  WorldAreasKeys: [WorldAreas]
  Name: string @localized
  FlavourText: string @localized
  QuestFlags1: [QuestFlags]
  Act: i32
  QuestFlags2: [QuestFlags]
  QuestFlags3: [QuestFlags]
  QuestFlag1: QuestFlags
  _: string
  ParentMapPin: MapPins
  MetadataId: string
  _: rid
  QuestFlag2: QuestFlags
  _: string @localized
  _: bool
  _: i32
  _: i32
  _: bool
}