enum ModDomains @indexing(first: 1) {
  ITEM
  FLASK
  MONSTER
  CHEST
  AREA
  _
  SANCTUM_RELIC
  _
  CRAFTED
  BASE_JEWEL
  ATLAS
  LEAGUESTONE
  ABYSS_JEWEL
  MAP_DEVICE
  DUMMY # The name indicates this is meant for the unique Piece item class
  DELVE
  DELVE_AREA
  SYNTHESIS_A
  SYNTHESIS_GLOBALS
  SYNTHESIS_BONUS
  AFFLICTION_JEWEL
  HEIST_AREA
  HEIST_NPC
  HEIST_TRINKET
  WATCHSTONE
  VEILED
  EXPEDITION_RELIC
  UNVEILED
  ELDRITCH_ALTAR
  SENTINEL
  MEMORY_LINE
  SANCTUM_SPECIAL
  CRUCIBLE_MAP
  TINCTURE
  ANIMAL_CHARM
  NECROPOLIS_MONSTER
  UBER_MAP
  IDOL
}
