enum ModGenerationType @indexing(first: 1) {
  PREFIX
  SUFFIX
  UNIQUE
  NEMESIS
  CORRUPTED
  BLOODLINES
  TORMENT
  TEMPEST
  TALISMAN
  ENCHANTMENT
  ESSENCE
  _
  BESTIARY
  DELVE_AREA
  SYNTHESIS_A
  SYNTHESIS_GLOBALS
  SYNTHESIS_BONUS
  BLIGHT
  BLIGHT_TOWER
  MONSTER_AFFLICTION
  FLASK_ENCHANTMENT_ENKINDLING
  FLASK_ENCHANTMENT_INSTILLING
  EXPEDITION_LOGBOOK
  SCOURGE_UPSIDE
  SCOURGE_DOWNSIDE
  SCOURGE_MAP
  _
  EXARCH_IMPLICIT
  EATER_IMPLICIT
  _
  WEAPON_TREE
  WEAPON_TREE_RECOMBINED
  _
  NECROPOLIS_HAUNTED
  NECROPOLIS_DEVOTED
}
