type MonsterVarieties {
  Id: string @unique
  MonsterType: MonsterTypes
  MovementSpeed: i32
  ObjectSize: i32
  MinimumAttackDistance: i32
  MaximumAttackDistance: i32
  ACTFiles: [string] @file(ext: ".act")
  AOFiles: [string] @file(ext: ".ao")
  BaseMonsterTypeIndex: string @files(ext: [".ot", ".otc"])
  Mods: [Mods]
  _: i32
  _: string
  _: string
  "in percent"
  ModelSizeMultiplier: i32
  _: i32
  _: i32
  _: rid
  _: i32
  _: i32
  Tags: [Tags]
  "in percent"
  ExperienceMultiplier: i32
  _: [i32]
  MinAgroRange: i32
  MaxAgroRange: i32
  SpotlightColour1: i32
  SpotlightColour2: i32
  SpotlightColour3: i32
  GrantedEffects: [GrantedEffects]
  AISFile: string @file(ext: ".ais")
  Mods2: [Mods]
  Stance: string
  _: rid
  Name: string
  "in percent"
  DamageMultiplier: i32
  "in percent"
  LifeMultiplier: i32
  "in ms"
  AttackSpeed: i32
  Weapon1_ItemVisualIdentity: [ItemVisualIdentity]
  Weapon2_ItemVisualIdentity: [ItemVisualIdentity]
  Back_ItemVisualIdentity: ItemVisualIdentity
  MainHand_ItemClass: ItemClasses
  OffHand_ItemClass: ItemClasses
  Helmet_ItemVisualIdentity: ItemVisualIdentity
  _: i32
  KillSpecificMonsterCount_AchievementItems: [AchievementItems]
  Special_Mods: [Mods]
  KillRare_AchievementItems: [AchievementItems]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  HASH16: u16
  _: bool
  _: string
  KillWhileOnslaughtIsActive_AchievementItem: AchievementItems
  MonsterSegment: MonsterSegments
  MonsterArmour: MonsterArmours
  KillWhileTalismanIsActive_AchievementItem: AchievementItems
  Part1_Mods: [Mods]
  Part2_Mods: [Mods]
  Endgame_Mods: [Mods]
  _: rid
  _: i32
  _: i32
  _: [rid]
  MultiPartAchievements: [MultiPartAchievements]
  _: i32
  SinkAnimation_AOFile: string @file(ext: ".ao")
  _: bool
  _: [rid]
  _: bool
  _: bool
  _: bool
  _: i32
  _: i32
  _: f32
  AilmentThreshold: i32
  SinkEffect: i32
  _: i32
  MonsterConditionalEffectPack: MonsterConditionalEffectPacks
  _: bool
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  BossHealthBar: bool
  _: rid
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: rid
  _: f32
  _: f32
  _: bool
  _: [_]
  _: rid
  _: i32
  _: i32
  _: f32
  _: rid
  _: bool
  _: i32
  _: bool
  _: i32
}
