# Added 4.1
type MonsterDeathAchievements {
  Id: string @unique
  MonsterVarietiesKeys: [MonsterVarieties]
  AchievementItemsKeys: [AchievementItems]
  _: bool
  PlayerConditionsKeys: [PlayerConditions]
  MonsterDeathConditionsKeys: [MonsterDeathConditions]
  _: [rid]
  _: i32
  _: i32
  _: bool
  _: bool
  _: rid
  _: [_]
  _: [_]
  _: [_]
  _: rid
  _: i32
  _: [_]
  _: bool
  _: [_]
  _: bool
  _: i32
}