type MonsterResistances {
  Id: string @unique
  Fire1: [i32]
  _: [i32]
  Fire2: [i32]
  _: [i32]
  Fire3: [i32]
  _: [i32]
  Fire4: [i32]
  Fire5: [i32]
  Cold1: [i32]
  _: [i32]
  Cold2: [i32]
  _: [i32]
  Cold3: [i32]
  _: [i32]
  Cold4: [i32]
  Cold5: [i32]
  Lightning1: [i32]
  _: [i32]
  Lightning2: [i32]
  _: [i32]
  Lightning3: [i32]
  _: [i32]
  Lightning4: [i32]
  Lightning5: [i32]
  Chaos1: [i32]
  _: [i32]
  Chaos2: [i32]
  _: [i32]
  Chaos3: [i32]
  _: [i32]
  Chaos4: [i32]
  Chaos5: [i32]
}
