# Added 4.1
type MoveDaemon {
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: f32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: string
  _: i32
  _: bool
  _: bool
  _: i32
  _: bool
  _: f32
  _: i32
  _: bool
}