type PassiveSkills {
  Id: string @unique
  Icon_DDSFile: string @file(ext: ".dds")
  Stats: [Stats]
  Stat1Value: i32
  Stat2Value: i32
  Stat3Value: i32
  Stat4Value: i32
  "Id used by PassiveSkillGraph.psg"
  PassiveSkillGraphId: u16 @unique
  Name: string
  Characters: [Characters]
  IsKeystone: bool
  IsNotable: bool
  FlavourText: string
  IsJustIcon: bool
  AchievementItem: AchievementItems
  IsJewelSocket: bool
  Ascendancy: Ascendancy
  IsAscendancyStartingNode: bool
  ReminderStrings: [ReminderText]
  SkillPointsGranted: i32
  IsMultipleChoice: bool
  IsMultipleChoiceOption: bool
  Stat5Value: i32
  PassiveSkillBuffs: [BuffTemplates]
  IsAnointmentOnly: bool
  _: i32
  IsExpansion: bool
  IsProxyPassive: bool
  SkillType: PassiveSkillTypes
  MasteryGroup: PassiveSkillMasteryGroups
  Group: AtlasPassiveSkillTreeGroupType
  SoundEffect: SoundEffects
  AtlasnodeGroup: string
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: [rid]
  _: i32
  _: [rid]
  _: bool
  KeystoneId: rid
  _: bool
  IsAttribute: bool
  AtlasSubTree: AtlasPassiveSkillSubTrees
  IsRootOfAtlasTree: bool
  GrantedSkill: SkillGems
  WeaponPointsGranted: i32
  IsFree: bool
  _: bool # Smith of Kitava body armour passives, maybe DoNotDraw(Connection)Line?
  _: [PassiveSkills]
  AscendancyUnlock: [Ascendancy]
  _: bool
  _: rid
}
