type PassiveSkillTreeUIArtAscendancy {
  Id: string
  StartNode: string
  PassiveFrameNormal: string
  PassiveFrameCanAllocate: string
  PassiveFrameActive: string
  PassiveFrameMask: string
  NotableFrameNormal: string
  NotableFrameCanAllocate: string
  NotableFrameActive: string
  NotableFrameMask: string
  SocketFrameNormal: string
  SocketFrameCanAllocate: string
  SocketFrameActive: string
  SocketFrameMask: string
}
