# Added 4.3
type PassiveJewelRadiiArt {
  Id: string @unique
  Circle1: string
  Circle2: string
  Glow: string
  _: passivejewelradiiart
  _: i32
  _: i32
  Inverse1: string
  _: i32
  _: i32
  Inverse2: string
}
