type PassiveSkillTrees {
  Id: string
  PassiveSkillGraph: string
  _: i32
  _: f32
  _: f32
  _: f32
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  Name: ClientStrings
  UIArt: PassiveSkillTreeUIArt
  _: rid
  _: rid
  _: f32
  _: f32
  _: f32
}
