type QuestItems {
  BaseItemType: BaseItemTypes @unique
  TriggeredQuestFlag: QuestFlags
  _: QuestFlags
  _: i32
  _: [_] # All rows empty
  _: bool
  _: bool
  HelpText: ClientStrings
  Description: ClientStrings
  Script: string
  _: rid
  _: rid
  _: i32
}
