type ShapeShiftForms {
  Id: string @unique
  AOFile: string @file(ext: ".ao")
  StatsKeys: [Stats]
  StatsValues: [i32]
  _: rid
  _: i32
  _: string
  _: i32
  _: f32
  _: f32
  _: f32
  SkillStat: Stats
  _: i32
  _: bool
  Status: string
  _: f32
  _: bool
}
