type SocketableStashTabLayout {
  Id: string @unique
  StoredItem: BaseItemTypes
  XOffset: i32
  YOffset: i32
  FirstSlotIndex: i32 @unique
  Width: i32
  Height: i32
  _: bool
  _: i32
  SlotIcon: DynamicStashSlots
}