type SoulCores {
  BaseItemType: BaseItemTypes
  StatsMartialWeapon: [Stats]
  StatsValuesMartialWeapon: [i32]
  StatsArmour: [Stats]
  StatsValuesArmour: [i32]
  Rank: i32
  StatsCasterWeapon: [Stats]
  StatsValuesCasterWeapon: [i32]
}