enum StashId @indexing(first: 0) {
  NORMAL
  PREMIUM
  TRADE
  CURRENCY
  UNIQUE
  MAP
  DIVINATION_CARD
  QUAD
  ESSENCE
  FRAGMENT
  PC_BANG_PREMIUM
  PC_BANG_ESSENCE
  DELVE
  BLIGHT
  ULTIMATUM
  DELIRIUM
  FOLDER
  FLASK
  GEM
  SOCKETABLE
  EXPEDITION
  RITUAL
}