type SupportGems {
  SkillGem: SkillGems @unique
  _: i32
  Icon: string  @file(ext: ".dds")
  Family: [SupportGemFamily]
  IsLineage: bool
  FlavourText: FlavourText
  _: rid
  VisualIdentity: SupportGemSocketedVisualIdentity
}
