type TableMonsterSpawners {
  Metadata: string
  AreaLevel: i32
  SpawnsMonsters: [MonsterVarieties]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: bool
  _: bool
  Script1: string
  _: bool
  _: bool
  Script2: string
  _: [i32]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}
