
type UltimatumModifiers {
  Id: string @unique
  Types: [UltimatumModifierTypes]
  ExtraMods: [Mods]
  TypesFiltered: [UltimatumModifierTypes]
  PreviousTier: [UltimatumModifiers]
  _: bool
  Name: string
  Icon: string
  HASH16: u16
  _: i16
  _: [string]
  BuffTemplates: [BuffTemplates]
  Tier: i32
  Description: string
  _: [_]
  TextAudio: NPCTextAudio
  _: rid
  MapStats: [Stats]
  MapStatValues: [i32]
  MapMods: [Mods]
}
