# Added 3.25
type VillageAssignWorkerTextAudio {
  _: rid
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
  _: NPCTextAudio
}
