type WieldableClasses {
  ItemClass: ItemClasses
  _: bool
  _: bool
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: i32
}
