type WorldAreas {
  Id: string
  Name: string
  Act: i32
  IsTown: bool
  HasWaypoint: bool
  Connections: [WorldAreas]
  AreaLevel: i32
  HASH16: i16
  _: i32
  _: i32
  LoadingScreens: [string]
  FlagOnEntered: [QuestFlags]
  RequiredFlags: [QuestFlags]
  _: i32
  Topologies: [Topologies]
  ParentTown: WorldAreas
  _: i32
  _: rid
  _: rid
  Bosses: [MonsterVarieties]
  _: [_]
  _: [_]
  _: [_]
  IsMapArea: bool
  _: [_]
  _: rid
  _: rid
  AreaMods: [Mods]
  _: i32
  _: bool
  MaxLevel: i32
  _: i32
  IsHideout: bool
  _: i32
  _: i32
  Tags: [Tags]
  _: rid
  _: rid
  _: i32
  _: i32
  _: rid
  _: [string]
  IsUniqueMapArea: bool
  _: rid
  _: rid
  _: i32
  _: i32
  _: i32
  Environment: Environments
  _: i32
  TerrainPlugins: TerrainPlugins
}
